/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConectaBanco;
import Controle.ControleFornecedor;
import Modelo.ModeloFornecedor;
import com.lowagie.text.Font;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.LineBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author NOTBOOK DE MAYCON
 */
public class FrmAddFornecedor extends javax.swing.JDialog {
    ModeloFornecedor modFor = new ModeloFornecedor();
    ControleFornecedor controleFor = new ControleFornecedor();
    ConectaBanco conecBanco = new ConectaBanco();
     int opBairro;
    public FrmAddFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        
          Locale.setDefault(new Locale("pt","BR"));
          UIManager.put("OptionPane.messageFont", new FontUIResource( "Arial", Font.NORMAL, 17));
             UIManager.put("OptionPane.yesButtonText", "Confirma");
              UIManager.put("OptionPane.noButtonText", "Cancelar");
        
                 try {
           MaskFormatter form = new MaskFormatter("##.###.###/####-##"); // elemento para criar formatato de mascara
           ct_cnpj.setFormatterFactory(new DefaultFormatterFactory(form)); //atribui a mascara ao campo
           
        } catch (ParseException ex) {
          
        }
        try {
          MaskFormatter form    = new MaskFormatter("(##)#####-####"); // elemento para criar formatato de mascara
          ct_telefone.setFormatterFactory(new DefaultFormatterFactory(form)); //atribui a mascara ao campo
        } catch (ParseException ex) {
          
        }
        
        preencherCombobox();
        cbox_bairro.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        btn_novo1 = new javax.swing.JButton();
        btn_salvar1 = new javax.swing.JButton();
        btn_cancelar1 = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel105 = new javax.swing.JPanel();
        ct_telefone = new javax.swing.JFormattedTextField();
        jPanel104 = new javax.swing.JPanel();
        ct_cnpj = new javax.swing.JFormattedTextField();
        jPanel102 = new javax.swing.JPanel();
        ct_endereco = new javax.swing.JTextField();
        jPanel101 = new javax.swing.JPanel();
        ct_nomeFornecedor = new javax.swing.JTextField();
        jPanel106 = new javax.swing.JPanel();
        cbox_bairro = new javax.swing.JComboBox<>();
        btn_addMarcaSemNota = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar Novo Fornecedor");
        setResizable(false);

        jDesktopPane1.setBackground(new java.awt.Color(102, 102, 255));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        jPanel8.setForeground(new java.awt.Color(102, 102, 102));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));

        btn_novo1.setBackground(new java.awt.Color(255, 255, 255));
        btn_novo1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_novo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/NOVO.png"))); // NOI18N
        btn_novo1.setToolTipText("NOVO");
        btn_novo1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_novo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novo1ActionPerformed(evt);
            }
        });

        btn_salvar1.setBackground(new java.awt.Color(255, 255, 255));
        btn_salvar1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_salvar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        btn_salvar1.setToolTipText("SALVAR");
        btn_salvar1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_salvar1.setEnabled(false);
        btn_salvar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar1ActionPerformed(evt);
            }
        });

        btn_cancelar1.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancelar1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_cancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        btn_cancelar1.setToolTipText("CANCELAR");
        btn_cancelar1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_cancelar1.setEnabled(false);
        btn_cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_novo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salvar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_novo1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_salvar1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDesktopPane2.setBackground(new java.awt.Color(102, 0, 255));
        jDesktopPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jPanel105.setBackground(new java.awt.Color(197, 196, 195));
        jPanel105.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Telefone", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 15), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel105.setOpaque(false);

        ct_telefone.setBackground(new java.awt.Color(255, 255, 102));
        ct_telefone.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_telefone.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_telefone.setEnabled(false);
        ct_telefone.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel105Layout = new javax.swing.GroupLayout(jPanel105);
        jPanel105.setLayout(jPanel105Layout);
        jPanel105Layout.setHorizontalGroup(
            jPanel105Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_telefone, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        jPanel105Layout.setVerticalGroup(
            jPanel105Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_telefone, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
        );

        jPanel104.setBackground(new java.awt.Color(197, 196, 195));
        jPanel104.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "CNPJ", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 15), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel104.setOpaque(false);

        ct_cnpj.setBackground(new java.awt.Color(255, 255, 102));
        ct_cnpj.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_cnpj.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_cnpj.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_cnpj.setEnabled(false);
        ct_cnpj.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel104Layout = new javax.swing.GroupLayout(jPanel104);
        jPanel104.setLayout(jPanel104Layout);
        jPanel104Layout.setHorizontalGroup(
            jPanel104Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_cnpj, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
        );
        jPanel104Layout.setVerticalGroup(
            jPanel104Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_cnpj, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
        );

        jPanel102.setBackground(new java.awt.Color(197, 196, 195));
        jPanel102.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Endereço", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 15), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel102.setOpaque(false);

        ct_endereco.setBackground(new java.awt.Color(255, 255, 102));
        ct_endereco.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ct_endereco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_endereco.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_endereco.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_endereco.setEnabled(false);
        ct_endereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_enderecoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel102Layout = new javax.swing.GroupLayout(jPanel102);
        jPanel102.setLayout(jPanel102Layout);
        jPanel102Layout.setHorizontalGroup(
            jPanel102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_endereco)
        );
        jPanel102Layout.setVerticalGroup(
            jPanel102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_endereco, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
        );

        jPanel101.setBackground(new java.awt.Color(197, 196, 195));
        jPanel101.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nome do Fornecedor", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 15), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel101.setOpaque(false);

        ct_nomeFornecedor.setBackground(new java.awt.Color(255, 255, 102));
        ct_nomeFornecedor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ct_nomeFornecedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_nomeFornecedor.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_nomeFornecedor.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_nomeFornecedor.setEnabled(false);
        ct_nomeFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_nomeFornecedorKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel101Layout = new javax.swing.GroupLayout(jPanel101);
        jPanel101.setLayout(jPanel101Layout);
        jPanel101Layout.setHorizontalGroup(
            jPanel101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_nomeFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );
        jPanel101Layout.setVerticalGroup(
            jPanel101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_nomeFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
        );

        jPanel106.setBackground(new java.awt.Color(197, 196, 195));
        jPanel106.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bairro", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 15), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel106.setOpaque(false);
        jPanel106.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel106MouseEntered(evt);
            }
        });

        cbox_bairro.setBackground(new java.awt.Color(255, 255, 102));
        cbox_bairro.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        cbox_bairro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cbox_bairro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbox_bairro.setEnabled(false);
        cbox_bairro.setOpaque(false);
        cbox_bairro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbox_bairroMousePressed(evt);
            }
        });
        cbox_bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_bairroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel106Layout = new javax.swing.GroupLayout(jPanel106);
        jPanel106.setLayout(jPanel106Layout);
        jPanel106Layout.setHorizontalGroup(
            jPanel106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbox_bairro, 0, 238, Short.MAX_VALUE)
        );
        jPanel106Layout.setVerticalGroup(
            jPanel106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbox_bairro, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );

        btn_addMarcaSemNota.setBackground(new java.awt.Color(204, 204, 204));
        btn_addMarcaSemNota.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_addMarcaSemNota.setForeground(new java.awt.Color(51, 204, 0));
        btn_addMarcaSemNota.setText("NOVO BAIRRO");
        btn_addMarcaSemNota.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_addMarcaSemNota.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_addMarcaSemNota.setOpaque(false);
        btn_addMarcaSemNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addMarcaSemNotaActionPerformed(evt);
            }
        });

        jDesktopPane2.setLayer(jPanel105, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel104, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel102, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel101, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel106, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btn_addMarcaSemNota, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel102, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addComponent(jPanel104, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel105, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_addMarcaSemNota)
                                    .addGap(5, 5, 5))
                                .addComponent(jPanel106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel104, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel105, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btn_addMarcaSemNota)
                .addContainerGap())
        );

        jDesktopPane1.setLayer(jPanel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jDesktopPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

            public void preencherCombobox(){
          conecBanco.conexaoBanco();
          conecBanco.executaSQL("select * from bairro order by nome_bairro");
          cbox_bairro.removeAllItems();
            try {
                conecBanco.rs.first();
                do{
                    cbox_bairro.addItem(""+conecBanco.rs.getString("nome_bairro"));
                } while(conecBanco.rs.next());
 
            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, "Erro ao preencher combobox Bairro"+ ex);
            }
          conecBanco.desconectar();
      }
            
    private void btn_novo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novo1ActionPerformed
        btn_salvar1.setEnabled(true);
        btn_cancelar1.setEnabled(true);
        btn_novo1.setEnabled(false);
        ct_nomeFornecedor.setEnabled(true);
        ct_nomeFornecedor.setText("");
        ct_endereco.setText("");
        ct_endereco.setEnabled(true);
        ct_cnpj.setText("");
        ct_cnpj.setEnabled(true);
        ct_telefone.setText("");
        ct_telefone.setEnabled(true);
        cbox_bairro.setSelectedItem(null);
        cbox_bairro.setEnabled(true);
    }//GEN-LAST:event_btn_novo1ActionPerformed

    private void btn_salvar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar1ActionPerformed
        int op1, op2, op3, op4, op5;
        String cnpjFornecedor="";

        conecBanco.conexaoBanco();
        try {
            conecBanco.executaSQL("select * from fornecedores where cnpj_fornecedor='"+ct_cnpj.getText().replaceAll("[^0-9]","")+"'");
            conecBanco.rs.first();
            cnpjFornecedor= conecBanco.rs.getString("cnpj_fornecedor");
        } catch (SQLException ex) {
//      JOptionPane.showMessageDialog(null, "Erro ao Verificar se o CNPJ Já Está Cadastrado!");
        }
        conecBanco.desconectar();
        

        if(ct_nomeFornecedor.getText().equals("")){
            ct_nomeFornecedor.setBackground(new Color(246,170,170));
            op1=1;
        }else{
            ct_nomeFornecedor.setBackground(new Color(252,252,146));
            op1=2;
        }
        
        if(ct_cnpj.getText().equals("")){
            ct_cnpj.setBackground(new Color(246,170,170));
            op2=1;
        }else{
            ct_cnpj.setBackground(new Color(252,252,146));
            op2=2;
        }
        
    if(cbox_bairro.getSelectedIndex()==-1){
    cbox_bairro.setBorder(new LineBorder(new Color(255,0,0)));
    op3=1;
  }else{
    cbox_bairro.setBorder(new LineBorder(new Color(197,196,195)));
    op3=2;
  }


          if(op1==2 && op2==2 && op3==2){
      if(ct_cnpj.getText().replaceAll("[^0-9]","").equals(cnpjFornecedor)){
    ct_cnpj.setBackground(new Color(246,170,170));
    JOptionPane.showMessageDialog(null,"CNPJ Já Cadastrado!","Erro ao Tentar Cadastrar",JOptionPane.ERROR_MESSAGE );      
    }else{
          int resposta=  JOptionPane.showConfirmDialog(null, "Finalizar Cadastro?", "Adicionar Fornecedor",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                if(resposta==JOptionPane.YES_NO_OPTION){
                    modFor.setBairro(""+cbox_bairro.getSelectedItem());
                    modFor.setCNPJ(ct_cnpj.getText().replaceAll("[^0-9]",""));
                    modFor.setTelefone1(ct_telefone.getText().replaceAll("[^0-9]",""));
                    modFor.setEndereco(ct_endereco.getText());
                    modFor.setNome(ct_nomeFornecedor.getText());
                   controleFor.gravar(modFor);

                    btn_salvar1.setEnabled(false);
                    btn_cancelar1.setEnabled(false);
                    btn_novo1.setEnabled(true);
                    ct_nomeFornecedor.setEnabled(false);
                    ct_nomeFornecedor.setText("");
                    ct_endereco.setText("");
                    ct_endereco.setEnabled(false);
                    ct_cnpj.setText("");
                    ct_cnpj.setEnabled(false);
                    ct_telefone.setText("");
                     ct_telefone.setEnabled(false);
                    cbox_bairro.setSelectedItem(null);
                    cbox_bairro.setEnabled(false);
                }else{
                }
           }
            }else{
              JOptionPane.showMessageDialog(null,"Campo obrigatório não preenchido!","Erro",JOptionPane.ERROR_MESSAGE); 
            }
            
//    }
    }//GEN-LAST:event_btn_salvar1ActionPerformed

    private void btn_cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar1ActionPerformed

        btn_salvar1.setEnabled(false);
        btn_cancelar1.setEnabled(false);
        btn_novo1.setEnabled(true);
        ct_nomeFornecedor.setEnabled(false);
        ct_nomeFornecedor.setText("");
        ct_endereco.setText("");
        ct_endereco.setEnabled(false);
        ct_cnpj.setText("");
        ct_cnpj.setEnabled(false);
        ct_telefone.setText("");
        ct_telefone.setEnabled(false);
        cbox_bairro.setSelectedItem(null);
        cbox_bairro.setEnabled(false);
        
        cbox_bairro.setBorder(new LineBorder(null));
        ct_cnpj.setBackground(new Color(255,255,102));
        ct_telefone.setBackground(new Color(255,255,102));
        ct_nomeFornecedor.setBackground(new Color(255,255,102));
        ct_endereco.setBackground(new Color(255,255,102));       
    }//GEN-LAST:event_btn_cancelar1ActionPerformed

    private void cbox_bairroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbox_bairroMousePressed
    
    }//GEN-LAST:event_cbox_bairroMousePressed

    private void cbox_bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_bairroActionPerformed

    }//GEN-LAST:event_cbox_bairroActionPerformed

    private void btn_addMarcaSemNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addMarcaSemNotaActionPerformed
      opBairro=1;
        FrmAddBairro dialog = new FrmAddBairro(new javax.swing.JFrame(), true);
       dialog.setVisible(true);       

    }//GEN-LAST:event_btn_addMarcaSemNotaActionPerformed

    private void ct_nomeFornecedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_nomeFornecedorKeyReleased
     if(ct_nomeFornecedor.getText().length()>=50){
        ct_nomeFornecedor.setText(ct_nomeFornecedor.getText().substring(0,50));
     }else{
     } 
        
    }//GEN-LAST:event_ct_nomeFornecedorKeyReleased

    private void ct_enderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_enderecoKeyReleased
     if(ct_endereco.getText().length()>=90){
        ct_endereco.setText(ct_endereco.getText().substring(0,90));
     }else{
     } 
    }//GEN-LAST:event_ct_enderecoKeyReleased

    private void jPanel106MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel106MouseEntered
        if(opBairro==1){
        preencherCombobox();
        cbox_bairro.setSelectedItem(null);
        opBairro=2;
        }else{ 
        }
        
    }//GEN-LAST:event_jPanel106MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAddFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAddFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAddFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAddFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmAddFornecedor dialog = new FrmAddFornecedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addMarcaSemNota;
    private javax.swing.JButton btn_cancelar1;
    private javax.swing.JButton btn_novo1;
    private javax.swing.JButton btn_salvar1;
    private javax.swing.JComboBox<String> cbox_bairro;
    private javax.swing.JFormattedTextField ct_cnpj;
    private javax.swing.JTextField ct_endereco;
    private javax.swing.JTextField ct_nomeFornecedor;
    private javax.swing.JFormattedTextField ct_telefone;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JPanel jPanel101;
    private javax.swing.JPanel jPanel102;
    private javax.swing.JPanel jPanel104;
    private javax.swing.JPanel jPanel105;
    private javax.swing.JPanel jPanel106;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
