/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConectaBanco;
import Controle.ControleBairro;
import Controle.ModeloTabela;
import Modelo.ModeloBairro;
import com.lowagie.text.Font;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.border.LineBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author NOTBOOK DE MAYCON
 */
public class FrmBairro extends javax.swing.JInternalFrame {
    ModeloBairro modBairro = new ModeloBairro();
    ControleBairro controlBai = new ControleBairro();
    ConectaBanco conecBanco= new ConectaBanco();
    ConectaBanco conecPesquisa = new ConectaBanco();
    String modoNavegar;
    public FrmBairro() {
        initComponents();
        Locale.setDefault(new Locale("pt","BR"));
         UIManager.put("OptionPane.messageFont", new FontUIResource( "Arial", Font.NORMAL, 17));
          UIManager.put("OptionPane.yesButtonText", "Confirma");
           UIManager.put("OptionPane.noButtonText", "Cancelar");
        
        preecherTabela("select * from bairro inner join cidade on bairro.id_cidade = cidade.id_cidade");
        AtualizaCombo();
        modoNavegar = "Inicializar";
        manipularInterface(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btn_novo = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        ct_pesquisaBairro = new javax.swing.JTextField();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel102 = new javax.swing.JPanel();
        cbox_cidade = new javax.swing.JComboBox<>();
        jPanel101 = new javax.swing.JPanel();
        ct_nome = new javax.swing.JTextField();
        jPanel103 = new javax.swing.JPanel();
        ct_codigo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_bairros = new javax.swing.JTable();

        setClosable(true);
        setTitle("FORMULÁRIO DE CADASTRO DE BAIRRO");

        jDesktopPane1.setBackground(new java.awt.Color(51, 102, 255));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        jPanel4.setForeground(new java.awt.Color(102, 102, 102));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        btn_novo.setBackground(new java.awt.Color(255, 255, 255));
        btn_novo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/NOVO.png"))); // NOI18N
        btn_novo.setToolTipText("NOVO");
        btn_novo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_editar.setBackground(new java.awt.Color(255, 255, 255));
        btn_editar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EDITAR.png"))); // NOI18N
        btn_editar.setToolTipText("EDITAR");
        btn_editar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_editar.setEnabled(false);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_salvar.setBackground(new java.awt.Color(255, 255, 255));
        btn_salvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        btn_salvar.setToolTipText("SALVAR");
        btn_salvar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_salvar.setEnabled(false);
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_excluir.setBackground(new java.awt.Color(255, 255, 255));
        btn_excluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir.png"))); // NOI18N
        btn_excluir.setToolTipText("EXCLUIR");
        btn_excluir.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_excluir.setEnabled(false);
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        btn_cancelar.setToolTipText("CANCELAR");
        btn_cancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_cancelar.setEnabled(false);
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_novo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_editar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ct_pesquisaBairro.setBackground(new java.awt.Color(0, 238, 255));
        ct_pesquisaBairro.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ct_pesquisaBairro.setText("Pesquisar bairro");
        ct_pesquisaBairro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));
        ct_pesquisaBairro.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_pesquisaBairro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ct_pesquisaBairroMouseClicked(evt);
            }
        });
        ct_pesquisaBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct_pesquisaBairroActionPerformed(evt);
            }
        });
        ct_pesquisaBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_pesquisaBairroKeyReleased(evt);
            }
        });

        jDesktopPane2.setBackground(new java.awt.Color(51, 0, 255));
        jDesktopPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jPanel102.setBackground(new java.awt.Color(197, 196, 195));
        jPanel102.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Cidade", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel102.setOpaque(false);

        cbox_cidade.setBackground(new java.awt.Color(252, 252, 146));
        cbox_cidade.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        cbox_cidade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cbox_cidade.setEnabled(false);
        cbox_cidade.setFocusable(false);
        cbox_cidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbox_cidadeMouseClicked(evt);
            }
        });
        cbox_cidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbox_cidadeKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel102Layout = new javax.swing.GroupLayout(jPanel102);
        jPanel102.setLayout(jPanel102Layout);
        jPanel102Layout.setHorizontalGroup(
            jPanel102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbox_cidade, 0, 299, Short.MAX_VALUE)
        );
        jPanel102Layout.setVerticalGroup(
            jPanel102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbox_cidade)
        );

        jPanel101.setBackground(new java.awt.Color(197, 196, 195));
        jPanel101.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nome do Bairro", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel101.setOpaque(false);

        ct_nome.setBackground(new java.awt.Color(255, 255, 102));
        ct_nome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ct_nome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_nome.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_nome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_nome.setEnabled(false);
        ct_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_nomeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel101Layout = new javax.swing.GroupLayout(jPanel101);
        jPanel101.setLayout(jPanel101Layout);
        jPanel101Layout.setHorizontalGroup(
            jPanel101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
        );
        jPanel101Layout.setVerticalGroup(
            jPanel101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel103.setBackground(new java.awt.Color(197, 196, 195));
        jPanel103.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Código", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel103.setOpaque(false);

        ct_codigo.setEditable(false);
        ct_codigo.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        ct_codigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ct_codigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_codigo.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        ct_codigo.setEnabled(false);

        javax.swing.GroupLayout jPanel103Layout = new javax.swing.GroupLayout(jPanel103);
        jPanel103.setLayout(jPanel103Layout);
        jPanel103Layout.setHorizontalGroup(
            jPanel103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel103Layout.setVerticalGroup(
            jPanel103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jDesktopPane2.setLayer(jPanel102, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel101, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel103, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 43, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "Lista de Bairro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 17))); // NOI18N
        jPanel1.setOpaque(false);

        tbl_bairros.setBackground(new java.awt.Color(248, 246, 244));
        tbl_bairros.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbl_bairros.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tbl_bairros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_bairros.setIntercellSpacing(new java.awt.Dimension(0, 4));
        tbl_bairros.setOpaque(false);
        tbl_bairros.setSelectionBackground(new java.awt.Color(255, 255, 102));
        tbl_bairros.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tbl_bairros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bairrosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_bairrosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_bairros);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDesktopPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ct_pesquisaBairro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jDesktopPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ct_pesquisaBairro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(ct_pesquisaBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        setSize(new java.awt.Dimension(1068, 572));
    }// </editor-fold>//GEN-END:initComponents

    
       public void manipularInterface(){ //MANIPULA A NAVEGAÇÃO 
        switch (modoNavegar){
            
             case "Inicializar":
                 ct_nome.setText("");
                 ct_codigo.setText("");
                 cbox_cidade.setSelectedItem(null);
                 ct_codigo.setEnabled(false);
                 ct_nome.setEnabled(false);
                 cbox_cidade.setEnabled(false);
                 btn_novo.setEnabled(true);;
                 btn_salvar.setEnabled(false);
                 btn_editar.setEnabled(false);
                 btn_excluir.setEnabled(false);
                 btn_cancelar.setEnabled(false);
                 ct_nome.setBackground(new Color(255,255,102));
                 cbox_cidade.setBorder(new LineBorder(null));
                 break;
            
            case "Navegar":
               ct_nome.setText("");
               ct_codigo.setText("");
               cbox_cidade.setSelectedItem(null);
               
                 ct_codigo.setEnabled(false);
                 ct_nome.setEnabled(false);
                 cbox_cidade.setEnabled(false);
                 btn_novo.setEnabled(true);;
                 btn_salvar.setEnabled(false);
                 btn_editar.setEnabled(true);
                 btn_excluir.setEnabled(true);
                 btn_cancelar.setEnabled(false);
                 ct_nome.setBackground(new Color(255,255,102));
                 cbox_cidade.setBorder(new LineBorder(null));
                 break;
                 
            case "Novo":
                 ct_nome.setText("");
                 ct_codigo.setText("");
                 ct_codigo.setEnabled(false);
                 ct_nome.setEnabled(true);
                 cbox_cidade.setEnabled(true);
                 cbox_cidade.setSelectedItem(null);     
                 btn_novo.setEnabled(false);;
                 btn_salvar.setEnabled(true);
                 btn_editar.setEnabled(false);
                 btn_excluir.setEnabled(false);
                 btn_cancelar.setEnabled(true);
                 ct_nome.setBackground(new Color(255,255,102));
                 cbox_cidade.setBorder(new LineBorder(null));
                 break;
           
            case "Editar":
                 ct_codigo.setEnabled(false);
                 ct_nome.setEnabled(true);
                 cbox_cidade.setEnabled(true);
                 btn_novo.setEnabled(true);;
                 btn_salvar.setEnabled(true);
                 btn_editar.setEnabled(false);
                 btn_excluir.setEnabled(true);
                 btn_cancelar.setEnabled(true);
                 ct_nome.setBackground(new Color(255,255,102));
                 cbox_cidade.setBorder(new LineBorder(null));
                 break;
                 
            default:
                break;
          }
    }
   
     public void AtualizaCombo(){
         conecBanco.conexaoBanco();
         cbox_cidade.removeAllItems();
        try {
            conecBanco.executaSQL("select * from cidade order by nome_cidades");
            conecBanco.rs.first();
            do{
               cbox_cidade.addItem(conecBanco.rs.getString("nome_cidades"));
           } while (conecBanco.rs.next());
        } catch (SQLException ex) {
         JOptionPane.showMessageDialog(rootPane, "Erro ao Preencher Combobox! \n"+ ex.getMessage());
        }
         conecBanco.desconectar();
     }
     
    public void preecherTabela(String SQL){ // METODO PARA PREENCHER TABELA NA INTERFACE
        conecBanco.conexaoBanco();
        ArrayList dados = new ArrayList();
        String [] Colunas  = new String []{"Código","Bairro", "Cidade"};
        
        conecBanco.executaSQL(SQL);
      try {
          conecBanco.rs.first();
          do {
              dados.add(new Object[]{conecBanco.rs.getInt("id_bairro"),conecBanco.rs.getString("nome_bairro"),conecBanco.rs.getString("nome_cidades")});
          }while (conecBanco.rs.next());
          
      } catch (SQLException ex) {
//         JOptionPane.showMessageDialog(rootPane, "Erro ao Preencher o ArrayList! \n"+ ex.getMessage());
      }
      
       ModeloTabela modelo = new ModeloTabela(dados,Colunas);
       
        tbl_bairros.setModel(modelo);
        DefaultTableCellRenderer headerRenderer2 = new DefaultTableCellRenderer(); 
        headerRenderer2.setOpaque(true); 
        headerRenderer2.setBackground(new Color(0,0,51));
        headerRenderer2.setFont(new java.awt.Font("Arial Black", Font.BOLD, 23));
        headerRenderer2.setForeground(new Color(255,255,255));
        for (int i = 0; i < tbl_bairros.getModel().getColumnCount(); 
         i++) { tbl_bairros.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer2); }

            tbl_bairros.setRowHeight(31); //  TAMANHO DA JANELA PRA CADA ITEM
 
        tbl_bairros.getColumnModel().getColumn(0).setPreferredWidth(63);
        tbl_bairros.getColumnModel().getColumn(0).setResizable(false);
        tbl_bairros.getColumnModel().getColumn(1).setPreferredWidth(210);
        tbl_bairros.getColumnModel().getColumn(1).setResizable(false);
        tbl_bairros.getColumnModel().getColumn(2).setPreferredWidth(150);
        tbl_bairros.getColumnModel().getColumn(2).setResizable(false);
        tbl_bairros.getTableHeader().setReorderingAllowed(false);
//        tbl_bairros.setAutoResizeMode(tbl_bairros.AUTO_RESIZE_OFF);
        tbl_bairros.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conecBanco.desconectar();
    }//  FINAL METODO PARA IMPRIMIR TABELA NA INTERFACE
             
    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        modoNavegar = "Novo";
        manipularInterface();
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        modoNavegar = "Editar";
        manipularInterface();
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
     int op1, op2, op3;
     String nomeVerifica="";
     conecBanco.conexaoBanco();
        try {
            conecBanco.executaSQL("select * from bairro where nome_bairro='"+ct_nome.getText()+"'");
            conecBanco.rs.first();
            nomeVerifica= conecBanco.rs.getString("nome_bairro");
        } catch (SQLException ex) {
        }
     conecBanco.desconectar();
     
      if(ct_nome.getText().equals("")){
        ct_nome.setBackground(new Color(246,170,170));
        op1=1;       
      }else{
        ct_nome.setBackground(new Color(255,255,102));
        op1=2;        
      }
      
      if(cbox_cidade.getSelectedIndex()==-1){
        cbox_cidade .setBorder(new LineBorder(new Color(255,0,0))); 
        op2=1;      
      }else{
        cbox_cidade.setBorder(new LineBorder(null));
        op2=2;            
      }
     
      if(ct_nome.getText().equals(nomeVerifica)){
          op3=1; 
      }else{
          op3=2;
      }
      
        if(op1==2 && op2==2){
            if(modoNavegar.equals("Novo")){
                if(op3==1){
                 JOptionPane.showMessageDialog(null,"Nome do bairro já cadastrado! \nTente outro nome.","Erro",JOptionPane.ERROR_MESSAGE);    
                }else{
                    int resposta=  JOptionPane.showConfirmDialog(null, "Salvar novo bairro?", "Novo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);    
                    if(resposta== JOptionPane.YES_NO_OPTION){
                        modBairro.setNome(ct_nome.getText());
                        modBairro.setCidade("" + cbox_cidade.getSelectedItem());
                        controlBai.Gravar(modBairro);
                        modoNavegar = "Inicializar";
                        manipularInterface();
                    }
                }
            }
            
            if(modoNavegar.equals("Editar")){
                int resposta=  JOptionPane.showConfirmDialog(null, "Deseja salvar as alterações?", "Alteração",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);    
                if(resposta== JOptionPane.YES_NO_OPTION){
                    modBairro.setNome(ct_nome.getText());
                    modBairro.setCidade("" + cbox_cidade.getSelectedItem());
                    modBairro.setCod(Integer.parseInt(ct_codigo.getText()));
                    controlBai.Editar(modBairro);
                    modoNavegar = "Navegar";
                    manipularInterface();
                }
            }
            
            preecherTabela("select * from bairro inner join cidade on bairro.id_cidade = cidade.id_cidade");
        }else{
          JOptionPane.showMessageDialog(null,"Campo obrigatório não preenchido!","Erro",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        int respost=JOptionPane.showConfirmDialog(null,"Deseja excluir bairro?","Excluir",JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(respost==JOptionPane.YES_NO_OPTION){
           modBairro.setCod(Integer.parseInt(ct_codigo.getText()));
           controlBai.Excluir(modBairro);
           
           preecherTabela("select * from bairro inner join cidade on bairro.id_cidade = cidade.id_cidade");
           modoNavegar = "Inicializar";
           manipularInterface();
        }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        modoNavegar = "Inicializar";
        manipularInterface();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void cbox_cidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbox_cidadeMouseClicked
        AtualizaCombo(); //ATUALIZA COMBOBOX DE CIDADES
    }//GEN-LAST:event_cbox_cidadeMouseClicked

    private void cbox_cidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbox_cidadeKeyPressed

    }//GEN-LAST:event_cbox_cidadeKeyPressed

    private void ct_pesquisaBairroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ct_pesquisaBairroMouseClicked

    }//GEN-LAST:event_ct_pesquisaBairroMouseClicked

    private void ct_pesquisaBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct_pesquisaBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct_pesquisaBairroActionPerformed

    private void ct_pesquisaBairroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_pesquisaBairroKeyReleased
        conecBanco.conexaoBanco();
        preecherTabela("select * from bairro inner join cidade on bairro.id_cidade = cidade.id_cidade where nome_bairro like '%" + ct_pesquisaBairro.getText() +"%'");
        conecBanco.desconectar();
    }//GEN-LAST:event_ct_pesquisaBairroKeyReleased

    private void tbl_bairrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bairrosMouseClicked
 
    }//GEN-LAST:event_tbl_bairrosMouseClicked

    private void tbl_bairrosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bairrosMousePressed
        modoNavegar = "Navegar";
        manipularInterface();
        String codBairro =""+ tbl_bairros.getValueAt(tbl_bairros.getSelectedRow(), 0);
        conecBanco.conexaoBanco();
        conecPesquisa.conexaoBanco();

        try {
            conecBanco.executaSQL("select * from bairro where id_bairro='"+codBairro+"'");
            conecBanco.rs.first();
            ct_codigo.setText(String.valueOf(conecBanco.rs.getInt("id_bairro")));
            ct_nome.setText(conecBanco.rs.getString("nome_bairro"));
            int id_cidade=conecBanco.rs.getInt("id_cidade");
            conecPesquisa.executaSQL("select * from cidade where id_cidade='"+id_cidade+"'");
            conecPesquisa.rs.first();
            cbox_cidade.setSelectedItem(conecPesquisa.rs.getString("nome_cidades"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Selecionar os Dados!"+ex);
        }
        conecBanco.desconectar();
        conecPesquisa.desconectar();
    }//GEN-LAST:event_tbl_bairrosMousePressed

    private void ct_nomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_nomeKeyReleased
     if(ct_nome.getText().length()>=25){
          ct_nome.setText(ct_nome.getText().substring(0,25));
     }else{
     } 
    }//GEN-LAST:event_ct_nomeKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JComboBox<String> cbox_cidade;
    private javax.swing.JTextField ct_codigo;
    private javax.swing.JTextField ct_nome;
    private javax.swing.JTextField ct_pesquisaBairro;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel101;
    private javax.swing.JPanel jPanel102;
    private javax.swing.JPanel jPanel103;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_bairros;
    // End of variables declaration//GEN-END:variables
}
