/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConectaBanco;
import Controle.ControleCidade;
import Controle.ModeloTabela;
import Modelo.ModeloCidade;
import com.lowagie.text.Font;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.border.LineBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author NOTBOOK DE MAYCON
 */
public class FrmCidade extends javax.swing.JInternalFrame {
       String modoNavegar;
       ConectaBanco conecBanco = new ConectaBanco();
       ModeloCidade mod = new ModeloCidade(); 
       ControleCidade controCi = new ControleCidade();

    
    public FrmCidade() {
        initComponents();
        Locale.setDefault(new Locale("pt","BR"));
        UIManager.put("OptionPane.messageFont", new FontUIResource( "Arial", Font.NORMAL, 17));
        UIManager.put("OptionPane.yesButtonText", "Confirma");
        UIManager.put("OptionPane.noButtonText", "Cancelar");
        
       preecherTabela("select * from cidade inner join estados on cidade.id_estado = estados.id_estado");
       preencheComboCidade();
          
           modoNavegar = "Inicializar";
           manipularInterface();
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        ct_pesquisaCidade = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btn_novo_Ci = new javax.swing.JButton();
        btn_salvar_Ci = new javax.swing.JButton();
        btn_editar_Ci = new javax.swing.JButton();
        btn_deletar_ci = new javax.swing.JButton();
        btn_cancelar_Ci = new javax.swing.JButton();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel102 = new javax.swing.JPanel();
        Cb_estado_Ci = new javax.swing.JComboBox<>();
        jPanel101 = new javax.swing.JPanel();
        c_nome_Ci = new javax.swing.JTextField();
        jPanel103 = new javax.swing.JPanel();
        c_codigo_Ci = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cidade_Ci = new javax.swing.JTable();

        setClosable(true);
        setTitle("FORMULÁRIO DE CADASTRO DE CIDADE");

        jDesktopPane1.setBackground(new java.awt.Color(102, 102, 255));

        ct_pesquisaCidade.setBackground(new java.awt.Color(0, 238, 255));
        ct_pesquisaCidade.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ct_pesquisaCidade.setText("Caixa de Pesquisa...");
        ct_pesquisaCidade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));
        ct_pesquisaCidade.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_pesquisaCidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ct_pesquisaCidadeMouseClicked(evt);
            }
        });
        ct_pesquisaCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct_pesquisaCidadeActionPerformed(evt);
            }
        });
        ct_pesquisaCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_pesquisaCidadeKeyReleased(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btn_novo_Ci.setBackground(new java.awt.Color(255, 255, 255));
        btn_novo_Ci.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_novo_Ci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/NOVO.png"))); // NOI18N
        btn_novo_Ci.setToolTipText("NOVO");
        btn_novo_Ci.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_novo_Ci.setPreferredSize(new java.awt.Dimension(45, 43));
        btn_novo_Ci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novo_CiActionPerformed(evt);
            }
        });

        btn_salvar_Ci.setBackground(new java.awt.Color(255, 255, 255));
        btn_salvar_Ci.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_salvar_Ci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        btn_salvar_Ci.setToolTipText("SALVAR");
        btn_salvar_Ci.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_salvar_Ci.setEnabled(false);
        btn_salvar_Ci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar_CiActionPerformed(evt);
            }
        });

        btn_editar_Ci.setBackground(new java.awt.Color(255, 255, 255));
        btn_editar_Ci.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_editar_Ci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EDITAR.png"))); // NOI18N
        btn_editar_Ci.setToolTipText("EDITAR");
        btn_editar_Ci.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_editar_Ci.setEnabled(false);
        btn_editar_Ci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editar_CiActionPerformed(evt);
            }
        });

        btn_deletar_ci.setBackground(new java.awt.Color(255, 255, 255));
        btn_deletar_ci.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_deletar_ci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir.png"))); // NOI18N
        btn_deletar_ci.setToolTipText("EXCLUIR");
        btn_deletar_ci.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_deletar_ci.setEnabled(false);
        btn_deletar_ci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deletar_ciActionPerformed(evt);
            }
        });

        btn_cancelar_Ci.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancelar_Ci.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_cancelar_Ci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        btn_cancelar_Ci.setToolTipText("CENCELAR");
        btn_cancelar_Ci.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_cancelar_Ci.setEnabled(false);
        btn_cancelar_Ci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar_CiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_novo_Ci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_salvar_Ci, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editar_Ci, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_deletar_ci, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar_Ci, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btn_novo_Ci, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_salvar_Ci, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_editar_Ci, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_deletar_ci, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cancelar_Ci, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jDesktopPane2.setBackground(new java.awt.Color(102, 0, 255));
        jDesktopPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jPanel102.setBackground(new java.awt.Color(197, 196, 195));
        jPanel102.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Estado", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel102.setOpaque(false);

        Cb_estado_Ci.setBackground(new java.awt.Color(252, 252, 146));
        Cb_estado_Ci.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        Cb_estado_Ci.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Cb_estado_Ci.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        Cb_estado_Ci.setEnabled(false);

        javax.swing.GroupLayout jPanel102Layout = new javax.swing.GroupLayout(jPanel102);
        jPanel102.setLayout(jPanel102Layout);
        jPanel102Layout.setHorizontalGroup(
            jPanel102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cb_estado_Ci, 0, 297, Short.MAX_VALUE)
        );
        jPanel102Layout.setVerticalGroup(
            jPanel102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cb_estado_Ci, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
        );

        jPanel101.setBackground(new java.awt.Color(197, 196, 195));
        jPanel101.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nome da Cidade", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel101.setOpaque(false);

        c_nome_Ci.setBackground(new java.awt.Color(255, 255, 102));
        c_nome_Ci.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        c_nome_Ci.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        c_nome_Ci.setCaretColor(new java.awt.Color(255, 0, 0));
        c_nome_Ci.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        c_nome_Ci.setEnabled(false);
        c_nome_Ci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_nome_CiActionPerformed(evt);
            }
        });
        c_nome_Ci.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                c_nome_CiKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel101Layout = new javax.swing.GroupLayout(jPanel101);
        jPanel101.setLayout(jPanel101Layout);
        jPanel101Layout.setHorizontalGroup(
            jPanel101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(c_nome_Ci, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
        );
        jPanel101Layout.setVerticalGroup(
            jPanel101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(c_nome_Ci, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
        );

        jPanel103.setBackground(new java.awt.Color(197, 196, 195));
        jPanel103.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Código", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel103.setOpaque(false);

        c_codigo_Ci.setEditable(false);
        c_codigo_Ci.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        c_codigo_Ci.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c_codigo_Ci.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        c_codigo_Ci.setCaretColor(new java.awt.Color(102, 102, 102));
        c_codigo_Ci.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        c_codigo_Ci.setEnabled(false);

        javax.swing.GroupLayout jPanel103Layout = new javax.swing.GroupLayout(jPanel103);
        jPanel103.setLayout(jPanel103Layout);
        jPanel103Layout.setHorizontalGroup(
            jPanel103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(c_codigo_Ci, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel103Layout.setVerticalGroup(
            jPanel103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(c_codigo_Ci, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
        );

        jDesktopPane2.setLayer(jPanel102, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel101, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel103, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "Lista de Cidades", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 17))); // NOI18N
        jPanel1.setOpaque(false);

        tbl_cidade_Ci.setBackground(new java.awt.Color(248, 246, 244));
        tbl_cidade_Ci.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbl_cidade_Ci.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tbl_cidade_Ci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_cidade_Ci.setIntercellSpacing(new java.awt.Dimension(0, 4));
        tbl_cidade_Ci.setOpaque(false);
        tbl_cidade_Ci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_cidade_CiMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_cidade_CiMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_cidade_Ci);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jDesktopPane1.setLayer(ct_pesquisaCidade, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jDesktopPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ct_pesquisaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ct_pesquisaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        setSize(new java.awt.Dimension(1068, 572));
    }// </editor-fold>//GEN-END:initComponents

    
        public void manipularInterface(){ //MANIPULA A NAVEGAÇÃO 
        switch (modoNavegar){
            
            
            case "Inicializar":
                 c_codigo_Ci.setText("");
                 c_nome_Ci.setText("");
                 Cb_estado_Ci.setSelectedItem(null);
                 c_nome_Ci.setEnabled(false);
                 c_codigo_Ci.setEnabled(false);
                 Cb_estado_Ci.setEnabled(false);
                 btn_deletar_ci.setEnabled(false);
                 btn_editar_Ci.setEnabled(false);
                 btn_novo_Ci.setEnabled(true);
                 btn_salvar_Ci.setEnabled(false);
                 btn_cancelar_Ci.setEnabled(false);
                 c_nome_Ci.setBackground(new Color(255,255,102));
                 Cb_estado_Ci.setBorder(new LineBorder(null));        
                 break;
            
            
            case "Navegar":
                 c_nome_Ci.setEnabled(false);
                 c_codigo_Ci.setEnabled(false);
                 Cb_estado_Ci.setEnabled(false);
                 btn_deletar_ci.setEnabled(true);
                 btn_editar_Ci.setEnabled(true);
                 btn_novo_Ci.setEnabled(true);
                 btn_salvar_Ci.setEnabled(false);
                 btn_cancelar_Ci.setEnabled(true);
                 c_nome_Ci.setBackground(new Color(255,255,102));
                 Cb_estado_Ci.setBorder(new LineBorder(null)); 
                 break;
                 
            case "Novo":
                 c_nome_Ci.setEnabled(true);
                 c_codigo_Ci.setEnabled(false);
                 c_codigo_Ci.setText("");
                 c_nome_Ci.setText(""); 
                 Cb_estado_Ci.setSelectedItem(null);
                  Cb_estado_Ci.setEnabled(true);
                 btn_deletar_ci.setEnabled(false);
                 btn_editar_Ci.setEnabled(false);
                 btn_novo_Ci.setEnabled(false);
                 btn_salvar_Ci.setEnabled(true);
                 btn_cancelar_Ci.setEnabled(true);
                 c_nome_Ci.setBackground(new Color(255,255,102));
                 Cb_estado_Ci.setBorder(new LineBorder(null)); 
                 break;
       
            case "Editar":
                 c_nome_Ci.setEnabled(true);
                 c_codigo_Ci.setEnabled(false);
                 Cb_estado_Ci.setEnabled(true);
                 btn_deletar_ci.setEnabled(true);
                 btn_editar_Ci.setEnabled(false);
                 btn_novo_Ci.setEnabled(false);
                 btn_salvar_Ci.setEnabled(true);
                 btn_cancelar_Ci.setEnabled(true);
                 c_nome_Ci.setBackground(new Color(255,255,102));
                 Cb_estado_Ci.setBorder(new LineBorder(null)); 
                 break;
                 
            default:
                break;
          }
    }
        
    public void preencheComboCidade(){
        conecBanco.conexaoBanco();
          conecBanco.executaSQL("select * from estados order by nome_estado");
            Cb_estado_Ci.removeAllItems(); // LIMPRA COMBOBOX PARA RECEBER OS DADOS
           try {
               conecBanco.rs.first();
               do{
                   Cb_estado_Ci.addItem(conecBanco.rs.getString("nome_estado"));
               }while(conecBanco.rs.next());          
           } catch (SQLException ex) {
               JOptionPane.showMessageDialog(rootPane,"Erro ao preencher combobox estados! "+ex);
               
           }
        conecBanco.desconectar();
    }     
                    
 
    public void preecherTabela(String SQL){ // METODO PARA PREENCHER TABELA NA INTERFACE
        conecBanco.conexaoBanco();
        ArrayList dados = new ArrayList();
        String [] Colunas  = new String []{"Código", "Cidade", "Estado"};
        
        conecBanco.executaSQL(SQL);
      try {
          conecBanco.rs.first();
          do {
              dados.add(new Object[]{conecBanco.rs.getInt("id_cidade"),conecBanco.rs.getString("nome_cidades"),conecBanco.rs.getString("sigla_estado")});
          }while (conecBanco.rs.next());
          
      } catch (SQLException ex) {
//         JOptionPane.showMessageDialog(rootPane, "Erro ao Preencher o ArrayList! \n"+ ex.getMessage());
      }
      
       ModeloTabela modelo = new ModeloTabela(dados,Colunas);
       
        tbl_cidade_Ci.setModel(modelo);
         DefaultTableCellRenderer headerRenderer2 = new DefaultTableCellRenderer(); 
        headerRenderer2.setOpaque(true); 
        headerRenderer2.setBackground(new Color(0,0,51));
        headerRenderer2.setFont(new java.awt.Font("Arial Black", Font.BOLD, 23));
        headerRenderer2.setForeground(new Color(255,255,255));
        for (int i = 0; i < tbl_cidade_Ci.getModel().getColumnCount(); 
         i++) { tbl_cidade_Ci.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer2); }

            tbl_cidade_Ci.setRowHeight(30); //  TAMANHO DA JANELA PRA CADA ITEM
            
      tbl_cidade_Ci.getColumnModel().getColumn(0).setPreferredWidth(63);
        tbl_cidade_Ci.getColumnModel().getColumn(0).setResizable(false);
        tbl_cidade_Ci.getColumnModel().getColumn(1).setPreferredWidth(320);
        tbl_cidade_Ci.getColumnModel().getColumn(1).setResizable(false);
        tbl_cidade_Ci.getColumnModel().getColumn(2).setPreferredWidth(63);
       tbl_cidade_Ci.getColumnModel().getColumn(2).setResizable(false);
       tbl_cidade_Ci.getTableHeader().setReorderingAllowed(false);
//        tbl_cidade_Ci.setAutoResizeMode(tbl_cidade_Ci.AUTO_RESIZE_OFF);
     tbl_cidade_Ci.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
     
       conecBanco.desconectar();
    }
             
    private void btn_novo_CiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novo_CiActionPerformed
        modoNavegar = "Novo";
        manipularInterface();
    }//GEN-LAST:event_btn_novo_CiActionPerformed

    private void btn_salvar_CiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar_CiActionPerformed
        conecBanco.conexaoBanco();
         int op1, op2, op3;
        String nomeCidadeVerif="";
        conecBanco.conexaoBanco();
        try {
            conecBanco.executaSQL("select * from cidade where nome_cidades='"+c_nome_Ci.getText()+"'");
            conecBanco.rs.first();
            nomeCidadeVerif=conecBanco.rs.getString("nome_cidades");
        } catch (SQLException ex) {
        }

        if(c_nome_Ci.getText().equals("")){
            c_nome_Ci.setBackground(new Color(246,170,170));
            op1=1;
        }else{
            c_nome_Ci.setBackground(new Color(255,255,102));
            op1=2;
        }
        
        if(Cb_estado_Ci.getSelectedIndex()==-1){
            Cb_estado_Ci.setBorder(new LineBorder(new Color(255,0,0)));
            op2=1;
        }else{
            Cb_estado_Ci.setBorder(new LineBorder(null));
            op2=2;
        }
        
        if(c_nome_Ci.getText().equals(nomeCidadeVerif)){
            op3=1;
        }else{
            op3=2;
        }
        
        
        if(modoNavegar.equals("Novo")) {
            if(op1==2 && op2==2){
                if(op3==1){
                JOptionPane.showMessageDialog(null,"Nome de cidade já cadastrado! \n Tente outro nome.","Erro",JOptionPane.ERROR_MESSAGE);
                }else{
                    int resposta=  JOptionPane.showConfirmDialog(null, "Salvar nova cidade?", "Novo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);    
                    if(resposta== JOptionPane.YES_NO_OPTION){
                    try {
                        mod.setNome(c_nome_Ci.getText());
                        conecBanco.executaSQL("select * from estados where nome_estado='"+Cb_estado_Ci.getSelectedItem()+"'");
                        conecBanco.rs.first();
                        mod.setCod_estado(conecBanco.rs.getInt("id_estado"));
                        controCi.InserirCidade(mod);

                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "Erro ao salvar "+ex);
                    }
                    modoNavegar = "Inicializar";
                    manipularInterface();
                    }else{
                        
                    }
                }
            }else{
               JOptionPane.showMessageDialog(null,"Campo obrigatório não preenchido!","Erro",JOptionPane.ERROR_MESSAGE);                
            }
        }else { 
        } 
        
        if(modoNavegar.equals("Editar")){
            if(op1==2 && op2==2){
                int resposta=  JOptionPane.showConfirmDialog(null, "Deseja salvar as alterações?", "Alteração",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);    
                if(resposta== JOptionPane.YES_NO_OPTION){
                    try {
                        mod.setCod(Integer.parseInt(c_codigo_Ci.getText()));
                        mod.setNome(c_nome_Ci.getText());
                        conecBanco.executaSQL("select * from estados where nome_estado='"+Cb_estado_Ci.getSelectedItem()+"'");
                        conecBanco.rs.first();
                        mod.setCod_estado(conecBanco.rs.getInt("id_estado"));
                        controCi.AlterarCidade(mod);
                        modoNavegar = "Navegar";
                        manipularInterface();
                    } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Erro ao salvar "+ex);
                    }
                }else{
                }
            }else{
            JOptionPane.showMessageDialog(null,"Campo obrigatório não preenchido!","Erro",JOptionPane.ERROR_MESSAGE);  
            }
        }
        preecherTabela("select * from cidade inner join estados on cidade.id_estado = estados.id_estado");
        conecBanco.desconectar();
        
    }//GEN-LAST:event_btn_salvar_CiActionPerformed

    private void btn_editar_CiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editar_CiActionPerformed
        modoNavegar ="Editar";
        manipularInterface();

    }//GEN-LAST:event_btn_editar_CiActionPerformed

    private void btn_deletar_ciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deletar_ciActionPerformed
        conecBanco.conexaoBanco();
        int resporta = JOptionPane.showConfirmDialog(null,"Tem certeza que deseja excluir?","Excluir",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(resporta==JOptionPane.YES_NO_OPTION){
            mod.setCod(Integer.parseInt(c_codigo_Ci.getText()));
            controCi.excluirCidade(mod);
        }else{
        }
        preecherTabela("select * from cidade inner join estados on cidade.id_estado = estados.id_estado");
        conecBanco.desconectar();
        modoNavegar = "Inicializar";
        manipularInterface();
    }//GEN-LAST:event_btn_deletar_ciActionPerformed

    private void btn_cancelar_CiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar_CiActionPerformed
        modoNavegar = "Inicializar";
        manipularInterface();
    }//GEN-LAST:event_btn_cancelar_CiActionPerformed

    private void c_nome_CiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_nome_CiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_nome_CiActionPerformed

    private void ct_pesquisaCidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ct_pesquisaCidadeMouseClicked
 
    }//GEN-LAST:event_ct_pesquisaCidadeMouseClicked

    private void ct_pesquisaCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct_pesquisaCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct_pesquisaCidadeActionPerformed

    private void ct_pesquisaCidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_pesquisaCidadeKeyReleased
       conecBanco.conexaoBanco();
        preecherTabela("select * from cidade inner join estados on cidade.id_estado = estados.id_estado where nome_cidades like '%" + ct_pesquisaCidade.getText() +"%'");
        conecBanco.desconectar();
    }//GEN-LAST:event_ct_pesquisaCidadeKeyReleased

    private void tbl_cidade_CiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_cidade_CiMouseClicked

    }//GEN-LAST:event_tbl_cidade_CiMouseClicked

    private void tbl_cidade_CiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_cidade_CiMousePressed
        modoNavegar ="Navegar";
        manipularInterface();
        try {
            String  codCidade = ""+tbl_cidade_Ci.getValueAt(tbl_cidade_Ci.getSelectedRow(), 0);
            conecBanco.conexaoBanco();
            conecBanco.executaSQL("select * from cidade where id_cidade='"+codCidade+"'");
            conecBanco.rs.first();
            c_codigo_Ci.setText(String.valueOf(conecBanco.rs.getInt("id_cidade")));
            c_nome_Ci.setText(conecBanco.rs.getString("nome_cidades"));
            conecBanco.executaSQL("select * from estados where id_estado="+conecBanco.rs.getInt("id_estado"));
            conecBanco.rs.first();
            Cb_estado_Ci.setSelectedItem(conecBanco.rs.getString("nome_estado"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao clicar \n"+ ex.getMessage());
        }
        conecBanco.desconectar();
    }//GEN-LAST:event_tbl_cidade_CiMousePressed

    private void c_nome_CiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c_nome_CiKeyReleased
        if(c_nome_Ci.getText().length()>=25){
             c_nome_Ci.setText(c_nome_Ci.getText().substring(0,25));
        }else{
     } 
    }//GEN-LAST:event_c_nome_CiKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cb_estado_Ci;
    private javax.swing.JButton btn_cancelar_Ci;
    private javax.swing.JButton btn_deletar_ci;
    private javax.swing.JButton btn_editar_Ci;
    private javax.swing.JButton btn_novo_Ci;
    private javax.swing.JButton btn_salvar_Ci;
    private javax.swing.JTextField c_codigo_Ci;
    private javax.swing.JTextField c_nome_Ci;
    private javax.swing.JTextField ct_pesquisaCidade;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel101;
    private javax.swing.JPanel jPanel102;
    private javax.swing.JPanel jPanel103;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_cidade_Ci;
    // End of variables declaration//GEN-END:variables
}
