/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConectaBanco;
import Controle.ControleCliente;
import Controle.ModeloTabela;
import Modelo.ModeloCliente;
import com.lowagie.text.Font;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.border.LineBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author NOTBOOK DE MAYCON
 */
public class FrmCliente extends javax.swing.JInternalFrame {
        String modoNavegar;
        ConectaBanco conecBanco = new ConectaBanco();
        ConectaBanco conecBancoBairro = new ConectaBanco();
        ModeloCliente mod = new ModeloCliente();
        ControleCliente contrCli = new ControleCliente();
 
    public FrmCliente() {
        initComponents();
          Locale.setDefault(new Locale("pt","BR"));
           UIManager.put("OptionPane.messageFont", new FontUIResource( "Arial", Font.NORMAL, 17));
             UIManager.put("OptionPane.yesButtonText", "Confirma");
              UIManager.put("OptionPane.noButtonText", "Cancelar");
              
             try {
          MaskFormatter form    = new MaskFormatter("###.###.###-##"); // elemento para criar formatato de mascara
             ct_cpf.setFormatterFactory(new DefaultFormatterFactory(form)); //atribui a mascara ao campo
             
                        form    = new MaskFormatter("##.###.###-##"); // elemento para criar formatato de mascara
             ct_rg.setFormatterFactory(new DefaultFormatterFactory(form)); //atribui a mascara ao campo
             
                        form    = new MaskFormatter("(##)#####-####"); // elemento para criar formatato de mascara
             ct_telefone1.setFormatterFactory(new DefaultFormatterFactory(form)); //atribui a mascara ao campo
             
                        form    = new MaskFormatter("(##)#####-####"); // elemento para criar formatato de mascara
             ct_telefone2.setFormatterFactory(new DefaultFormatterFactory(form)); //atribui a mascara ao campo
                                    
        } catch (ParseException ex) {
        }
             
        preencherCombobox();
        preecherTabela("select * from clientes  order by nome_cliente");        
        
       modoNavegar = "Inicializar";
       manipularInterface();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btn_novo = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel102 = new javax.swing.JPanel();
        ct_apelido = new javax.swing.JFormattedTextField();
        jPanel101 = new javax.swing.JPanel();
        ct_nome = new javax.swing.JTextField();
        jPanel103 = new javax.swing.JPanel();
        ct_codigo = new javax.swing.JTextField();
        jPanel104 = new javax.swing.JPanel();
        ct_telefone1 = new javax.swing.JFormattedTextField();
        jPanel105 = new javax.swing.JPanel();
        ct_cpf = new javax.swing.JFormattedTextField();
        jPanel106 = new javax.swing.JPanel();
        ct_rg = new javax.swing.JFormattedTextField();
        jPanel107 = new javax.swing.JPanel();
        cbox_bairro = new javax.swing.JComboBox<>();
        jPanel109 = new javax.swing.JPanel();
        ct_endereco = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_addNovoBairro = new javax.swing.JButton();
        jPanel110 = new javax.swing.JPanel();
        ct_referencia = new javax.swing.JTextField();
        jPanel108 = new javax.swing.JPanel();
        ct_telefone2 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_clientes = new javax.swing.JTable();
        ct_pesquisaCli = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setTitle("FORMULÁRIO DE CADASTRO DE CLIENTE");

        jDesktopPane2.setBackground(new java.awt.Color(0, 102, 255));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        jPanel4.setForeground(new java.awt.Color(102, 102, 102));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        btn_novo.setBackground(new java.awt.Color(255, 255, 255));
        btn_novo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/NOVO.png"))); // NOI18N
        btn_novo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_salvar.setBackground(new java.awt.Color(255, 255, 255));
        btn_salvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        btn_salvar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_salvar.setEnabled(false);
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_editar.setBackground(new java.awt.Color(255, 255, 255));
        btn_editar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EDITAR.png"))); // NOI18N
        btn_editar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_editar.setEnabled(false);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_excluir.setBackground(new java.awt.Color(255, 255, 255));
        btn_excluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir.png"))); // NOI18N
        btn_excluir.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_excluir.setEnabled(false);
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        btn_cancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_cancelar.setEnabled(false);
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_novo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        jDesktopPane1.setBackground(new java.awt.Color(51, 0, 255));
        jDesktopPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jPanel102.setBackground(new java.awt.Color(197, 196, 195));
        jPanel102.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Apelido", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel102.setOpaque(false);

        ct_apelido.setBackground(new java.awt.Color(255, 255, 102));
        ct_apelido.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_apelido.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_apelido.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_apelido.setEnabled(false);
        ct_apelido.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ct_apelido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_apelidoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel102Layout = new javax.swing.GroupLayout(jPanel102);
        jPanel102.setLayout(jPanel102Layout);
        jPanel102Layout.setHorizontalGroup(
            jPanel102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_apelido)
        );
        jPanel102Layout.setVerticalGroup(
            jPanel102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_apelido)
        );

        jPanel101.setBackground(new java.awt.Color(197, 196, 195));
        jPanel101.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nome do Cliente*", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel101.setOpaque(false);

        ct_nome.setBackground(new java.awt.Color(255, 255, 102));
        ct_nome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ct_nome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_nome.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_nome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_nome.setEnabled(false);
        ct_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_nomeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel101Layout = new javax.swing.GroupLayout(jPanel101);
        jPanel101.setLayout(jPanel101Layout);
        jPanel101Layout.setHorizontalGroup(
            jPanel101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );
        jPanel101Layout.setVerticalGroup(
            jPanel101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel101Layout.createSequentialGroup()
                .addComponent(ct_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel103.setBackground(new java.awt.Color(197, 196, 195));
        jPanel103.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Código", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel103.setOpaque(false);

        ct_codigo.setEditable(false);
        ct_codigo.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        ct_codigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ct_codigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_codigo.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        ct_codigo.setEnabled(false);

        javax.swing.GroupLayout jPanel103Layout = new javax.swing.GroupLayout(jPanel103);
        jPanel103.setLayout(jPanel103Layout);
        jPanel103Layout.setHorizontalGroup(
            jPanel103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        jPanel103Layout.setVerticalGroup(
            jPanel103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel104.setBackground(new java.awt.Color(197, 196, 195));
        jPanel104.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Telefone I", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel104.setOpaque(false);

        ct_telefone1.setBackground(new java.awt.Color(255, 255, 102));
        ct_telefone1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_telefone1.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_telefone1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_telefone1.setEnabled(false);
        ct_telefone1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel104Layout = new javax.swing.GroupLayout(jPanel104);
        jPanel104.setLayout(jPanel104Layout);
        jPanel104Layout.setHorizontalGroup(
            jPanel104Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_telefone1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel104Layout.setVerticalGroup(
            jPanel104Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel104Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ct_telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel105.setBackground(new java.awt.Color(197, 196, 195));
        jPanel105.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "CPF", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel105.setOpaque(false);

        ct_cpf.setBackground(new java.awt.Color(255, 255, 102));
        ct_cpf.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_cpf.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_cpf.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_cpf.setEnabled(false);
        ct_cpf.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ct_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct_cpfActionPerformed(evt);
            }
        });
        ct_cpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_cpfKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel105Layout = new javax.swing.GroupLayout(jPanel105);
        jPanel105.setLayout(jPanel105Layout);
        jPanel105Layout.setHorizontalGroup(
            jPanel105Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel105Layout.setVerticalGroup(
            jPanel105Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel105Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ct_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel106.setBackground(new java.awt.Color(197, 196, 195));
        jPanel106.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "RG", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel106.setOpaque(false);

        ct_rg.setBackground(new java.awt.Color(255, 255, 102));
        ct_rg.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_rg.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_rg.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_rg.setEnabled(false);
        ct_rg.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ct_rg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_rgKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel106Layout = new javax.swing.GroupLayout(jPanel106);
        jPanel106.setLayout(jPanel106Layout);
        jPanel106Layout.setHorizontalGroup(
            jPanel106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel106Layout.setVerticalGroup(
            jPanel106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel106Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ct_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel107.setBackground(new java.awt.Color(197, 196, 195));
        jPanel107.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bairro*", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel107.setOpaque(false);

        cbox_bairro.setBackground(new java.awt.Color(252, 252, 139));
        cbox_bairro.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        cbox_bairro.setMaximumRowCount(10);
        cbox_bairro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cbox_bairro.setEnabled(false);
        cbox_bairro.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                cbox_bairroComponentAdded(evt);
            }
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                cbox_bairroComponentRemoved(evt);
            }
        });
        cbox_bairro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbox_bairroItemStateChanged(evt);
            }
        });
        cbox_bairro.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                cbox_bairroHierarchyChanged(evt);
            }
        });
        cbox_bairro.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                cbox_bairroAncestorMoved(evt);
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbox_bairroAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                cbox_bairroAncestorRemoved(evt);
            }
        });
        cbox_bairro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cbox_bairroMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                cbox_bairroMouseMoved(evt);
            }
        });
        cbox_bairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbox_bairroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbox_bairroFocusLost(evt);
            }
        });
        cbox_bairro.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
                cbox_bairroPopupMenuCanceled(evt);
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbox_bairro.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                cbox_bairroMouseWheelMoved(evt);
            }
        });
        cbox_bairro.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                cbox_bairroAncestorMoved1(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        cbox_bairro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbox_bairroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbox_bairroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbox_bairroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbox_bairroMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbox_bairroMouseReleased(evt);
            }
        });
        cbox_bairro.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                cbox_bairroComponentHidden(evt);
            }
            public void componentResized(java.awt.event.ComponentEvent evt) {
                cbox_bairroComponentResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                cbox_bairroComponentShown(evt);
            }
        });
        cbox_bairro.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                cbox_bairroCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                cbox_bairroInputMethodTextChanged(evt);
            }
        });
        cbox_bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_bairroActionPerformed(evt);
            }
        });
        cbox_bairro.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbox_bairroPropertyChange(evt);
            }
        });
        cbox_bairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbox_bairroKeyReleased(evt);
            }
        });
        cbox_bairro.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                cbox_bairroVetoableChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel107Layout = new javax.swing.GroupLayout(jPanel107);
        jPanel107.setLayout(jPanel107Layout);
        jPanel107Layout.setHorizontalGroup(
            jPanel107Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbox_bairro, javax.swing.GroupLayout.Alignment.TRAILING, 0, 247, Short.MAX_VALUE)
        );
        jPanel107Layout.setVerticalGroup(
            jPanel107Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbox_bairro, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel109.setBackground(new java.awt.Color(197, 196, 195));
        jPanel109.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Endereço", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel109.setOpaque(false);

        ct_endereco.setBackground(new java.awt.Color(255, 255, 102));
        ct_endereco.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ct_endereco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_endereco.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_endereco.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_endereco.setEnabled(false);
        ct_endereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_enderecoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel109Layout = new javax.swing.GroupLayout(jPanel109);
        jPanel109.setLayout(jPanel109Layout);
        jPanel109Layout.setHorizontalGroup(
            jPanel109Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_endereco)
        );
        jPanel109Layout.setVerticalGroup(
            jPanel109Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel109Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ct_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("OU");

        btn_addNovoBairro.setBackground(new java.awt.Color(204, 204, 204));
        btn_addNovoBairro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_addNovoBairro.setForeground(new java.awt.Color(51, 204, 0));
        btn_addNovoBairro.setText("NOVO BAIRRO");
        btn_addNovoBairro.setEnabled(false);
        btn_addNovoBairro.setOpaque(false);
        btn_addNovoBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addNovoBairroActionPerformed(evt);
            }
        });

        jPanel110.setBackground(new java.awt.Color(197, 196, 195));
        jPanel110.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Referência", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel110.setOpaque(false);

        ct_referencia.setBackground(new java.awt.Color(255, 255, 102));
        ct_referencia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ct_referencia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_referencia.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_referencia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_referencia.setEnabled(false);
        ct_referencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_referenciaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel110Layout = new javax.swing.GroupLayout(jPanel110);
        jPanel110.setLayout(jPanel110Layout);
        jPanel110Layout.setHorizontalGroup(
            jPanel110Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_referencia)
        );
        jPanel110Layout.setVerticalGroup(
            jPanel110Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel110Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ct_referencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel108.setBackground(new java.awt.Color(197, 196, 195));
        jPanel108.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Telefone II", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel108.setOpaque(false);

        ct_telefone2.setBackground(new java.awt.Color(255, 255, 102));
        ct_telefone2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_telefone2.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_telefone2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_telefone2.setEnabled(false);
        ct_telefone2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel108Layout = new javax.swing.GroupLayout(jPanel108);
        jPanel108.setLayout(jPanel108Layout);
        jPanel108Layout.setHorizontalGroup(
            jPanel108Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_telefone2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel108Layout.setVerticalGroup(
            jPanel108Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel108Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ct_telefone2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jDesktopPane1.setLayer(jPanel102, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel101, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel103, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel104, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel105, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel106, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel107, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel109, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btn_addNovoBairro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel110, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel108, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel109, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jPanel103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel102, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel110, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jPanel105, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel104, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel108, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel107, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_addNovoBairro)
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel101, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel102, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel106, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel104, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel108, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel107, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel105, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(btn_addNovoBairro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel109, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel110, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "Lista de Clientes", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 17))); // NOI18N
        jPanel1.setOpaque(false);

        tbl_clientes.setBackground(new java.awt.Color(248, 246, 244));
        tbl_clientes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbl_clientes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tbl_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_clientes.setIntercellSpacing(new java.awt.Dimension(0, 4));
        tbl_clientes.setOpaque(false);
        tbl_clientes.setSelectionBackground(new java.awt.Color(255, 255, 102));
        tbl_clientes.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tbl_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_clientesMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_clientesMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_clientes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        ct_pesquisaCli.setBackground(new java.awt.Color(0, 238, 255));
        ct_pesquisaCli.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ct_pesquisaCli.setText("Caixa de Pesquisa...");
        ct_pesquisaCli.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));
        ct_pesquisaCli.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_pesquisaCli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ct_pesquisaCliMouseClicked(evt);
            }
        });
        ct_pesquisaCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct_pesquisaCliActionPerformed(evt);
            }
        });
        ct_pesquisaCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_pesquisaCliKeyReleased(evt);
            }
        });

        jDesktopPane2.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jDesktopPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(ct_pesquisaCli, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                        .addGap(0, 534, Short.MAX_VALUE)
                        .addComponent(ct_pesquisaCli, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDesktopPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ct_pesquisaCli, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2)
        );

        setSize(new java.awt.Dimension(1068, 572));
    }// </editor-fold>//GEN-END:initComponents

    
            public void manipularInterface(){ //MANIPULA A NAVEGAÇÃO 
        switch (modoNavegar){
 
            case "Inicializar":
                 ct_codigo.setText("");
                 ct_nome.setText("");
                 ct_endereco.setText("");
                 ct_rg.setText("");
                 ct_cpf.setText("");
                 ct_apelido.setText("");
                 ct_telefone1.setText("");
                 ct_telefone2.setText("");
                 ct_referencia.setText("");
                  
                 btn_addNovoBairro.setVisible(false);                 
                 ct_telefone1.setEnabled(false);
                 ct_telefone2.setEnabled(false);
                 ct_referencia.setEnabled(false);
                 
                 cbox_bairro.setSelectedItem(null);
                 cbox_bairro.setSelectedItem(null);
      
                 ct_apelido.setEnabled(false);
                 ct_codigo.setEnabled(false);
                 ct_nome.setEnabled(false);
                 ct_endereco.setEnabled(false);
                 ct_rg.setEnabled(false);
                 ct_cpf.setEnabled(false);
                 cbox_bairro.setEnabled(false);
                 btn_novo.setEnabled(true);;
                 btn_salvar.setEnabled(false);
                 btn_editar.setEnabled(false);
                 btn_excluir.setEnabled(false);
                 btn_cancelar.setEnabled(false);
                 cbox_bairro.setBorder(new LineBorder(null));
                 ct_nome.setBackground(new Color(255,255,102));
                 break;
            
            case "Navegar":
                 ct_codigo.setText("");
                 ct_nome.setText("");
                 ct_endereco.setText("");
                 ct_rg.setText("");
                 ct_cpf.setText("");
                 ct_apelido.setText("");
                 ct_telefone1.setText("");
                 ct_telefone2.setText("");
                 ct_referencia.setText("");
 
                 btn_addNovoBairro.setVisible(false);                 
                 ct_telefone1.setEnabled(false);
                 ct_telefone2.setEnabled(false);
                 ct_referencia.setEnabled(false);
                      
                 ct_codigo.setEnabled(false);
                 ct_nome.setEnabled(false);
                 ct_apelido.setEnabled(false);
                 ct_endereco.setEnabled(false);
                 ct_rg.setEnabled(false);
                 ct_cpf.setEnabled(false);
                 cbox_bairro.setEnabled(false);

                 btn_novo.setEnabled(true);;
                 btn_salvar.setEnabled(false);
                 btn_editar.setEnabled(true);
                 btn_excluir.setEnabled(true);
                 btn_cancelar.setEnabled(false);
                 cbox_bairro.setBorder(new LineBorder(null));
                 ct_nome.setBackground(new Color(255,255,102));
                 break;
                 
            case "Novo":
                 ct_codigo.setText("");
                 ct_nome.setText("");
                 ct_endereco.setText("");
                 ct_rg.setText("");
                 ct_cpf.setText("");
                 ct_apelido.setText("");
                 
                 ct_telefone1.setText("");
                 ct_telefone2.setText("");
                 ct_referencia.setText("");
                  
                 btn_addNovoBairro.setVisible(true);                 
                 ct_telefone1.setEnabled(true);
                 ct_telefone2.setEnabled(true);
                 ct_referencia.setEnabled(true);
                 
                 cbox_bairro.setSelectedItem(null);

                 ct_codigo.setEnabled(false);
                 ct_nome.setEnabled(true);
                ct_apelido.setEnabled(true);

                 ct_endereco.setEnabled(true);
                 ct_rg.setEnabled(true);
                 ct_cpf.setEnabled(true);
                 cbox_bairro.setEnabled(true);

                 btn_novo.setEnabled(false);;
                 btn_salvar.setEnabled(true);
                 btn_editar.setEnabled(false);
                 btn_excluir.setEnabled(false);
                 btn_cancelar.setEnabled(true);
                 cbox_bairro.setBorder(new LineBorder(null));
                 ct_nome.setBackground(new Color(255,255,102));
                 break;
     
            case "Editar":
                  
                 ct_telefone1.setEnabled(true);
                 ct_telefone2.setEnabled(true);
                 ct_referencia.setEnabled(true);
                 btn_addNovoBairro.setVisible(true);
                 
                 ct_codigo.setEnabled(false);
                 ct_nome.setEnabled(true);
                 ct_apelido.setEnabled(true);

                 ct_endereco.setEnabled(true);
                 ct_rg.setEnabled(true);
                 ct_cpf.setEnabled(true);
                 cbox_bairro.setEnabled(true);
                 btn_novo.setEnabled(true);;
                 btn_salvar.setEnabled(true);
                 btn_editar.setEnabled(false);
                 btn_excluir.setEnabled(true);
                 btn_cancelar.setEnabled(true);
                 cbox_bairro.setBorder(new LineBorder(null));
                 ct_nome.setBackground(new Color(255,255,102));
                 break;
                 
            default:
                break;
          }
    }
            
    public void preecherTabela(String SQL){ // METODO PARA PREENCHER TABELA NA INTERFACE
        ArrayList dados = new ArrayList();
        
        String [] Colunas  = new String []{"Nome", "Apelido", "Telefone I","CPF","RG", "Bairro"};
        conecBanco.conexaoBanco();
        conecBanco.executaSQL(SQL);
      try {
          conecBanco.rs.first();
          do {
              conecBancoBairro.conexaoBanco();
              conecBancoBairro.executaSQL("select * from bairro where id_bairro="+conecBanco.rs.getString("id_bairro")+"");
              conecBancoBairro.rs.first();
              conecBancoBairro.desconectar();
             
              dados.add(new Object[]{conecBanco.rs.getString("nome_cliente"),conecBanco.rs.getString("apelido_cliente"),conecBanco.rs.getString("telefone_1"),conecBanco.rs.getString("cpf_cliente"),conecBanco.rs.getString("rg_cliente"),conecBancoBairro.rs.getString("nome_bairro")});
          }while (conecBanco.rs.next());
          
      } catch (SQLException ex) {
//         JOptionPane.showMessageDialog(rootPane, "Erro ao Preencher o ArrayList! \n"+ ex);
      }
      
       ModeloTabela modelo = new ModeloTabela(dados,Colunas);
       
        tbl_clientes.setModel(modelo);
        DefaultTableCellRenderer headerRenderer2 = new DefaultTableCellRenderer(); 
        headerRenderer2.setOpaque(true); 
        headerRenderer2.setBackground(new Color(0,0,51));
        headerRenderer2.setFont(new java.awt.Font("Arial Black", Font.BOLD, 23));
        headerRenderer2.setForeground(new Color(255,255,255));
        for (int i = 0; i < tbl_clientes.getModel().getColumnCount(); 
         i++) { tbl_clientes.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer2); }

            tbl_clientes.setRowHeight(31); //  TAMANHO DA JANELA PRA CADA ITEM
            
        tbl_clientes.getColumnModel().getColumn(0).setPreferredWidth(240);
        tbl_clientes.getColumnModel().getColumn(0).setResizable(false);
        tbl_clientes.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbl_clientes.getColumnModel().getColumn(1).setResizable(false);
        tbl_clientes.getColumnModel().getColumn(2).setPreferredWidth(110);
        tbl_clientes.getColumnModel().getColumn(2).setResizable(false);
        tbl_clientes.getColumnModel().getColumn(3).setPreferredWidth(110);
        tbl_clientes.getColumnModel().getColumn(3).setResizable(false);
        tbl_clientes.getColumnModel().getColumn(4).setPreferredWidth(110);
        tbl_clientes.getColumnModel().getColumn(4).setResizable(false);
        tbl_clientes.getColumnModel().getColumn(5).setPreferredWidth(150);
        tbl_clientes.getColumnModel().getColumn(5).setResizable(false);
        tbl_clientes.getTableHeader().setReorderingAllowed(false);
//        tbl_clientes.setAutoResizeMode(tbl_clientes.AUTO_RESIZE_OFF);
        tbl_clientes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conecBanco.desconectar();
    }//  FINAL METODO PARA IMPRIMIR TABELA NA INTERFACE
                    
     public void preencherCombobox(){
          cbox_bairro.removeAllItems();
          conecBanco.conexaoBanco();
            try {
          conecBanco.executaSQL("select * from bairro order by nome_bairro");
                conecBanco.rs.first();
                do{
                    cbox_bairro.addItem(conecBanco.rs.getString("nome_bairro"));
                } while(conecBanco.rs.next());
   
            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, "Erro ao preencher combobox"+ ex);
            }
          conecBanco.desconectar();   
      }                   
                    
            
    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        modoNavegar = "Novo";
        manipularInterface();

    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
      int op1, op2, op3;
      String verificaNome = "";
      conecBanco.conexaoBanco();
            try {
                conecBanco.executaSQL("select * from clientes where nome_cliente='"+ct_nome.getText()+"'");
                conecBanco.rs.first();
                verificaNome= conecBanco.rs.getString("nome_cliente");
            } catch (SQLException ex) {
            }
      
      conecBanco.desconectar();
        if(ct_nome.getText().equals("")){
            ct_nome.setBackground(new Color(246,170,170));
            op1=1;        
        }else{
            ct_nome.setBackground(new Color(255,255,102));
            op1=2; 
        }

         if(cbox_bairro.getSelectedIndex()==-1){
            cbox_bairro.setBorder(new LineBorder(new Color(255,0,0)));
            op2=1;        
        }else{
            cbox_bairro.setBorder(new LineBorder(null));
            op2=2; 
        }
        
        if(ct_nome.getText().equals(verificaNome)){
            op3=1;
        }else{
            op3=2;
        }
        
        if(op1==2 && op2==2){
                if(modoNavegar.equals("Novo")){
                    if(op3==1){
                       JOptionPane.showMessageDialog(null,"Nome de cliente já cadastrado! \nTente outro nome.","Erro",JOptionPane.ERROR_MESSAGE);    
                    }else{
                       int resposta=  JOptionPane.showConfirmDialog(null, "Salvar novo cliente?", "Novo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);    
                       if(resposta== JOptionPane.YES_NO_OPTION){
                        mod.setNome(ct_nome.getText());
                        mod.setTelefone1(ct_telefone1.getText().replaceAll("[^0-9]", ""));
                        mod.setTelefone2(ct_telefone2.getText().replaceAll("[^0-9]", ""));
                        mod.setEndereco(ct_endereco.getText());
                        mod.setRg(ct_rg.getText().replaceAll("[^0-9]", ""));
                        mod.setCpf(ct_cpf.getText().replaceAll("[^0-9]", ""));
                        mod.setBairro(""+cbox_bairro.getSelectedItem());
                        mod.setApelido(ct_apelido.getText());
                        mod.setReferencia(ct_referencia.getText());
                        contrCli.Gravar(mod);
                        modoNavegar = "Inicializar";
                        manipularInterface();
                       }
                    }
                }

                if(modoNavegar.equals("Editar")){
                   int resposta=  JOptionPane.showConfirmDialog(null, "Deseja salvar as alterações?", "Alteração",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);    
                   if(resposta== JOptionPane.YES_NO_OPTION){
                    mod.setId(Integer.parseInt(ct_codigo.getText()));
                    mod.setNome(ct_nome.getText());
                    mod.setTelefone1(ct_telefone1.getText().replaceAll("[^0-9]", ""));
                    mod.setTelefone2(ct_telefone2.getText().replaceAll("[^0-9]", ""));
                    mod.setEndereco(ct_endereco.getText());
                    mod.setRg(ct_rg.getText().replaceAll("[^0-9]", ""));
                    mod.setCpf(ct_cpf.getText().replaceAll("[^0-9]", ""));
                    mod.setBairro("" + cbox_bairro.getSelectedItem());
                    mod.setApelido(ct_apelido.getText());
                    mod.setReferencia(ct_referencia.getText());
                    contrCli.Editar(mod);
                    modoNavegar = "Navegar";
                    manipularInterface();
                   }
                }
                preecherTabela("select * from clientes  order by nome_cliente");
        }else{
         JOptionPane.showMessageDialog(null,"Campo obrigatório não preenchido!","Erro",JOptionPane.ERROR_MESSAGE);    
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        modoNavegar = "Editar";
        manipularInterface();
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
       int respost=JOptionPane.showConfirmDialog(null,"Deseja excluir o cliente?","Excluir",JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE);
       if(respost==JOptionPane.YES_NO_OPTION){
        mod.setId(Integer.parseInt(ct_codigo.getText()));
        contrCli.Excluir(mod);
        
        preecherTabela("select * from clientes  order by nome_cliente");
        modoNavegar = "Inicializar";
        manipularInterface();
       }
       
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        modoNavegar = "Inicializar";
        manipularInterface();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void cbox_bairroComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_cbox_bairroComponentAdded

    }//GEN-LAST:event_cbox_bairroComponentAdded

    private void cbox_bairroComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_cbox_bairroComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_bairroComponentRemoved

    private void cbox_bairroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbox_bairroItemStateChanged

    }//GEN-LAST:event_cbox_bairroItemStateChanged

    private void cbox_bairroHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_cbox_bairroHierarchyChanged

    }//GEN-LAST:event_cbox_bairroHierarchyChanged

    private void cbox_bairroAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbox_bairroAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_bairroAncestorMoved

    private void cbox_bairroAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbox_bairroAncestorAdded

    }//GEN-LAST:event_cbox_bairroAncestorAdded

    private void cbox_bairroAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbox_bairroAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_bairroAncestorRemoved

    private void cbox_bairroMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbox_bairroMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_bairroMouseDragged

    private void cbox_bairroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbox_bairroMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_bairroMouseMoved

    private void cbox_bairroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbox_bairroFocusGained

    }//GEN-LAST:event_cbox_bairroFocusGained

    private void cbox_bairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbox_bairroFocusLost

    }//GEN-LAST:event_cbox_bairroFocusLost

    private void cbox_bairroPopupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbox_bairroPopupMenuCanceled
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_bairroPopupMenuCanceled

    private void cbox_bairroMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_cbox_bairroMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_bairroMouseWheelMoved

    private void cbox_bairroAncestorMoved1(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_cbox_bairroAncestorMoved1
       
    }//GEN-LAST:event_cbox_bairroAncestorMoved1

    private void cbox_bairroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbox_bairroMouseClicked
    
    }//GEN-LAST:event_cbox_bairroMouseClicked

    private void cbox_bairroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbox_bairroMouseEntered
      
    }//GEN-LAST:event_cbox_bairroMouseEntered

    private void cbox_bairroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbox_bairroMouseExited
    
    }//GEN-LAST:event_cbox_bairroMouseExited

    private void cbox_bairroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbox_bairroMousePressed

    }//GEN-LAST:event_cbox_bairroMousePressed

    private void cbox_bairroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbox_bairroMouseReleased

    }//GEN-LAST:event_cbox_bairroMouseReleased

    private void cbox_bairroComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cbox_bairroComponentHidden

    }//GEN-LAST:event_cbox_bairroComponentHidden

    private void cbox_bairroComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cbox_bairroComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_bairroComponentResized

    private void cbox_bairroComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cbox_bairroComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_bairroComponentShown

    private void cbox_bairroCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cbox_bairroCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_bairroCaretPositionChanged

    private void cbox_bairroInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_cbox_bairroInputMethodTextChanged

    }//GEN-LAST:event_cbox_bairroInputMethodTextChanged

    private void cbox_bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_bairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_bairroActionPerformed

    private void cbox_bairroPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbox_bairroPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_bairroPropertyChange

    private void cbox_bairroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbox_bairroKeyReleased

    }//GEN-LAST:event_cbox_bairroKeyReleased

    private void cbox_bairroVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_cbox_bairroVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_cbox_bairroVetoableChange

    private void tbl_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_clientesMouseClicked

    }//GEN-LAST:event_tbl_clientesMouseClicked

    private void ct_pesquisaCliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ct_pesquisaCliMouseClicked
        ct_pesquisaCli.selectAll();
    }//GEN-LAST:event_ct_pesquisaCliMouseClicked

    private void ct_pesquisaCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct_pesquisaCliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct_pesquisaCliActionPerformed

    private void ct_pesquisaCliKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_pesquisaCliKeyReleased
        conecBanco.conexaoBanco();
        preecherTabela("select * from clientes where nome_cliente like '%"+ct_pesquisaCli.getText()+"%'");
        conecBanco.desconectar();
    }//GEN-LAST:event_ct_pesquisaCliKeyReleased

    private void btn_addNovoBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addNovoBairroActionPerformed
//        opMarcaSemNota=1;
        FrmAddMarca dialog = new FrmAddMarca(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btn_addNovoBairroActionPerformed

    private void ct_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct_cpfActionPerformed

    private void tbl_clientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_clientesMousePressed
            modoNavegar= "Navegar";
        manipularInterface();
        conecBanco.conexaoBanco();
        conecBancoBairro.conexaoBanco();
        
        String  mouse = ""+ tbl_clientes.getValueAt(tbl_clientes.getSelectedRow(), 0);

        try {
            conecBanco.executaSQL("select * from clientes where nome_cliente ='"+mouse+"'");
            conecBanco.rs.first();
    
            ct_apelido.setText(conecBanco.rs.getString("apelido_cliente"));
            ct_codigo.setText(String.valueOf(conecBanco.rs.getInt("id_cliente")));
            ct_nome.setText(conecBanco.rs.getString("nome_cliente"));
            ct_telefone1.setText(conecBanco.rs.getString("telefone_1"));
            ct_telefone2.setText(conecBanco.rs.getString("telefone_2"));
            ct_referencia.setText(conecBanco.rs.getString("referencia"));
            ct_endereco.setText(conecBanco.rs.getString("endereco_cliente"));
            ct_rg.setText(conecBanco.rs.getString("rg_cliente"));
            ct_cpf.setText(conecBanco.rs.getString("cpf_cliente"));

            conecBancoBairro.executaSQL("select * from bairro where id_bairro='"+conecBanco.rs.getInt("id_bairro")+"'");
            conecBancoBairro.rs.first();
            cbox_bairro.setSelectedItem(conecBancoBairro.rs.getString("nome_bairro"));

        } catch (SQLException ex) {
           
        }
        conecBanco.desconectar();
        conecBancoBairro.desconectar();
    }//GEN-LAST:event_tbl_clientesMousePressed

    private void ct_nomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_nomeKeyReleased
        if(ct_nome.getText().length()>=50){
          ct_nome.setText(ct_nome.getText().substring(0,50));
        }else{
        } 
    }//GEN-LAST:event_ct_nomeKeyReleased

    private void ct_apelidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_apelidoKeyReleased
     if(ct_apelido.getText().length()>=25){
        ct_apelido.setText(ct_apelido.getText().substring(0,25));
     }else{
     } 
    }//GEN-LAST:event_ct_apelidoKeyReleased

    private void ct_enderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_enderecoKeyReleased
     if(ct_endereco.getText().length()>=90){
       ct_endereco.setText(ct_endereco.getText().substring(0,90));
     }else{
     } 
    }//GEN-LAST:event_ct_enderecoKeyReleased

    private void ct_referenciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_referenciaKeyReleased
      if(ct_referencia.getText().length()>=90){
        ct_referencia.setText(ct_referencia.getText().substring(0,90));
     }else{
     } 
    }//GEN-LAST:event_ct_referenciaKeyReleased

    private void ct_rgKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_rgKeyReleased
        ct_cpf.setText("");
    }//GEN-LAST:event_ct_rgKeyReleased

    private void ct_cpfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_cpfKeyReleased
       ct_rg.setText("");
    }//GEN-LAST:event_ct_cpfKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addNovoBairro;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JComboBox<String> cbox_bairro;
    private javax.swing.JFormattedTextField ct_apelido;
    private javax.swing.JTextField ct_codigo;
    private javax.swing.JFormattedTextField ct_cpf;
    private javax.swing.JTextField ct_endereco;
    private javax.swing.JTextField ct_nome;
    private javax.swing.JTextField ct_pesquisaCli;
    private javax.swing.JTextField ct_referencia;
    private javax.swing.JFormattedTextField ct_rg;
    private javax.swing.JFormattedTextField ct_telefone1;
    private javax.swing.JFormattedTextField ct_telefone2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel101;
    private javax.swing.JPanel jPanel102;
    private javax.swing.JPanel jPanel103;
    private javax.swing.JPanel jPanel104;
    private javax.swing.JPanel jPanel105;
    private javax.swing.JPanel jPanel106;
    private javax.swing.JPanel jPanel107;
    private javax.swing.JPanel jPanel108;
    private javax.swing.JPanel jPanel109;
    private javax.swing.JPanel jPanel110;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_clientes;
    // End of variables declaration//GEN-END:variables
}
