/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConectaBanco;
import Controle.ModeloTabela;
import com.lowagie.text.Font;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author NOTBOOK DE MAYCON
 */
public class FrmEstoque extends javax.swing.JInternalFrame {
    ConectaBanco conecBanc = new ConectaBanco();
    ConectaBanco conecEstoq= new ConectaBanco();
  int idProd;
  String modoNavegar;
     NumberFormat numberFormat = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
     NumberFormat numberFormat2 = NumberFormat.getNumberInstance(new Locale("en", "US"));
     
     //PEGA DATA DO SISTEMA
   NumberFormat formant;
   SimpleDateFormat forma = new SimpleDateFormat("dd/MM/yyyy");
      Date hoje = new Date();
      
    public FrmEstoque() {
        initComponents();
       conecBanc.conexaoBanco();
        preecherTabela("select * from produto");
        conecBanc.desconectar();
      numberFormat2.setMaximumFractionDigits(2);
      numberFormat2.setMinimumFractionDigits(2);
      numberFormat2.setMaximumFractionDigits(2);
      numberFormat2.setMinimumFractionDigits(2);
      
      modoNavegar = "Inicializar";
      manipularInterface();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ct_preco_compra = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ct_preco_venda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ct_codBarra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ct_produto = new javax.swing.JTextField();
        ct_quantidade = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        ct_data = new javax.swing.JTextField();
        ct_qtdAnterior = new javax.swing.JTextField();
        ct_qtdTotal = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_estoque = new javax.swing.JTable();
        ct_pesquisar = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btn_add = new javax.swing.JButton();
        btn_confirma = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ct_addEstoque = new javax.swing.JTextField();
        jPanel20 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 13, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("FORMULÁRIO DE ADICINAR ESTOQUE");

        jPanel1.setBackground(new java.awt.Color(197, 196, 195));

        jPanel3.setBackground(new java.awt.Color(197, 196, 195));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ct_preco_compra.setEditable(false);
        ct_preco_compra.setBackground(new java.awt.Color(252, 252, 146));
        ct_preco_compra.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        ct_preco_compra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ct_preco_compra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ct_preco_compra.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_preco_compra.setEnabled(false);
        ct_preco_compra.setFocusable(false);
        ct_preco_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct_preco_compraActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("PREÇO DE COMPRA");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("PREÇO DE VENDA");

        ct_preco_venda.setEditable(false);
        ct_preco_venda.setBackground(new java.awt.Color(252, 252, 146));
        ct_preco_venda.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        ct_preco_venda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ct_preco_venda.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ct_preco_venda.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_preco_venda.setEnabled(false);
        ct_preco_venda.setFocusable(false);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("QUANTIDADE");

        ct_codBarra.setEditable(false);
        ct_codBarra.setBackground(new java.awt.Color(252, 252, 146));
        ct_codBarra.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ct_codBarra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ct_codBarra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ct_codBarra.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_codBarra.setEnabled(false);
        ct_codBarra.setFocusable(false);
        ct_codBarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct_codBarraActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("COD/BARRA:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("NOME:");

        ct_produto.setEditable(false);
        ct_produto.setBackground(new java.awt.Color(252, 252, 146));
        ct_produto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ct_produto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ct_produto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_produto.setEnabled(false);
        ct_produto.setFocusable(false);

        ct_quantidade.setEditable(false);
        ct_quantidade.setBackground(new java.awt.Color(252, 252, 146));
        ct_quantidade.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        ct_quantidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ct_quantidade.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ct_quantidade.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_quantidade.setEnabled(false);
        ct_quantidade.setFocusable(false);

        jPanel10.setBackground(new java.awt.Color(197, 196, 195));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel17.setBackground(new java.awt.Color(237, 237, 244));
        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel12.setText("DADOS ANTERIORES");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel17Layout.createSequentialGroup()
                    .addGap(0, 90, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addGap(0, 90, Short.MAX_VALUE)))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel17Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        ct_data.setEditable(false);
        ct_data.setBackground(new java.awt.Color(255, 153, 153));
        ct_data.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        ct_data.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ct_data.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ct_data.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_data.setEnabled(false);
        ct_data.setFocusable(false);
        ct_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct_dataActionPerformed(evt);
            }
        });

        ct_qtdAnterior.setEditable(false);
        ct_qtdAnterior.setBackground(new java.awt.Color(255, 153, 153));
        ct_qtdAnterior.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        ct_qtdAnterior.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ct_qtdAnterior.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ct_qtdAnterior.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_qtdAnterior.setEnabled(false);
        ct_qtdAnterior.setFocusable(false);

        ct_qtdTotal.setEditable(false);
        ct_qtdTotal.setBackground(new java.awt.Color(255, 153, 153));
        ct_qtdTotal.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        ct_qtdTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ct_qtdTotal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ct_qtdTotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_qtdTotal.setEnabled(false);
        ct_qtdTotal.setFocusable(false);

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("TOTAL FINAL:");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("ADICIONADO:");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("DATA:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ct_data, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ct_qtdAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ct_qtdTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ct_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ct_qtdAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ct_qtdTotal)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(ct_preco_compra, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(ct_preco_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(ct_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ct_codBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ct_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ct_codBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ct_produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ct_quantidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ct_preco_compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ct_preco_venda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tbl_estoque.setBackground(new java.awt.Color(248, 246, 244));
        tbl_estoque.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbl_estoque.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tbl_estoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_estoque.setGridColor(new java.awt.Color(51, 0, 255));
        tbl_estoque.setIntercellSpacing(new java.awt.Dimension(0, 4));
        tbl_estoque.setOpaque(false);
        tbl_estoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_estoqueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_estoque);

        ct_pesquisar.setBackground(new java.awt.Color(0, 238, 255));
        ct_pesquisar.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        ct_pesquisar.setText("Pesquisar produto");
        ct_pesquisar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ct_pesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ct_pesquisarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ct_pesquisarMouseEntered(evt);
            }
        });
        ct_pesquisar.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                ct_pesquisarComponentResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ct_pesquisarComponentShown(evt);
            }
        });
        ct_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct_pesquisarActionPerformed(evt);
            }
        });
        ct_pesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_pesquisarKeyReleased(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        btn_add.setBackground(new java.awt.Color(204, 204, 204));
        btn_add.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/NOVO.png"))); // NOI18N
        btn_add.setToolTipText("ADICIONAR");
        btn_add.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_confirma.setBackground(new java.awt.Color(204, 204, 204));
        btn_confirma.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_confirma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/confirma_estoque.png"))); // NOI18N
        btn_confirma.setToolTipText("CONFIRMA");
        btn_confirma.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_confirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmaActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(204, 204, 204));
        btn_cancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar_estoque.png"))); // NOI18N
        btn_cancelar.setToolTipText("CANCELAR");
        btn_cancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(btn_confirma, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btn_cancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_confirma, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cancelar)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 84, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("QUANTIDADE");

        ct_addEstoque.setBackground(new java.awt.Color(252, 252, 146));
        ct_addEstoque.setFont(new java.awt.Font("Arial Black", 1, 30)); // NOI18N
        ct_addEstoque.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jPanel20.setBackground(new java.awt.Color(0, 238, 255));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("ADICIONAR NO ESTOQUE");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(67, 67, 67))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ct_addEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ct_addEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel18.setBackground(new java.awt.Color(237, 237, 244));

        jLabel11.setBackground(new java.awt.Color(237, 237, 244));
        jLabel11.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ATUALIZAR ESTOQUE");
        jLabel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel19.setBackground(new java.awt.Color(237, 237, 244));
        jPanel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("LISTA DE PRODUTOS");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ct_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ct_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1064, 545));
    }// </editor-fold>//GEN-END:initComponents

            public void manipularInterface(){ //MANIPULA A NAVEGAÇÃO 
        switch (modoNavegar){
            
            case "Inicializar":
                 ct_data.setText("");
                 ct_produto.setText("");
                 ct_quantidade.setText("");
                 ct_preco_compra.setText("");
                 ct_preco_venda.setText("");
                 ct_codBarra.setText("");
                 ct_qtdAnterior.setText("");
                 ct_qtdTotal.setText("");
                 ct_addEstoque.setText("");
                 ct_addEstoque.setEnabled(false);
                 
                 btn_add.setEnabled(false);
                 btn_confirma.setEnabled(false);
                 btn_cancelar.setEnabled(false);
                 
                 break;
                 
            case "Navegar":
                 ct_data.setText("");
                 ct_produto.setText("");
                 ct_quantidade.setText("");
                 ct_preco_compra.setText("");
                 ct_preco_venda.setText("");
                 ct_codBarra.setText("");
                 ct_qtdAnterior.setText("");
                 ct_qtdTotal.setText("");
                 ct_addEstoque.setText("");
                 ct_addEstoque.setEnabled(false);
                 
                 btn_add.setEnabled(true);
                 btn_confirma.setEnabled(false);
                 btn_cancelar.setEnabled(false);
                 break;
                 
            case "btn_add":
                
                 ct_addEstoque.setEnabled(true);
                 
                 btn_add.setEnabled(false);
                 btn_confirma.setEnabled(true);
                 btn_cancelar.setEnabled(true);
                 break;
                 
            case "btn_cancelar":
                 ct_data.setText("");
                 ct_produto.setText("");
                 ct_quantidade.setText("");
                 ct_preco_compra.setText("");
                 ct_preco_venda.setText("");
                 ct_codBarra.setText("");
                 ct_qtdAnterior.setText("");
                 ct_qtdTotal.setText("");
                 ct_addEstoque.setText("");
                 ct_addEstoque.setEnabled(false);
                 
                 btn_add.setEnabled(false);
                 btn_confirma.setEnabled(true);
                 btn_cancelar.setEnabled(true);
                 break;                 
                 
            default:
                break;
          }
    }
     
        public void preecherTabela(String SQL){ // METODO PARA PREENCHER TABELA NA INTERFACE
        ArrayList dados = new ArrayList();
        
//        String [] Colunas  = new String []{"Cod. Barra", "Nome ","P. Compra","P. Venda","Qtd"};
        String [] Colunas  = new String []{"Cod. Barra", "Nome ","Qtd"};
        conecBanc.conexaoBanco();
        conecBanc.executaSQL(SQL);
        
      try {
          conecBanc.rs.first();
          do {
//              dados.add(new Object[]{conecBanc.rs.getString("codbarra"), conecBanc.rs.getString("nome_produto"),(numberFormat.format(conecBanc.rs.getFloat("preco_compra"))),(numberFormat.format(conecBanc.rs.getFloat("preco_venda"))),conecBanc.rs.getInt("quantidade")});
      dados.add(new Object[]{conecBanc.rs.getString("codbarra"), conecBanc.rs.getString("nome_produto"),conecBanc.rs.getInt("quantidade")});
              
          }while (conecBanc.rs.next());
          
      } catch (SQLException ex) {
//         JOptionPane.showMessageDialog(rootPane, "Erro ao Preencher o ArrayList! \n"+ ex);
      }
      
       ModeloTabela modelo = new ModeloTabela(dados,Colunas);
       
        tbl_estoque.setModel(modelo);
        DefaultTableCellRenderer headerRenderer2 = new DefaultTableCellRenderer(); 
        headerRenderer2.setOpaque(true); 
        headerRenderer2.setBackground(new Color(0,0,51));
        headerRenderer2.setFont(new java.awt.Font("Arial Black", Font.BOLD, 23));
        headerRenderer2.setForeground(new Color(255,255,255));
        for (int i = 0; i < tbl_estoque.getModel().getColumnCount(); 
         i++) { tbl_estoque.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer2); }

            tbl_estoque.setRowHeight(40); //  TAMANHO DA JANELA PRA CADA ITEM
            
        tbl_estoque.getColumnModel().getColumn(0).setPreferredWidth(130);
        tbl_estoque.getColumnModel().getColumn(0).setResizable(false);
        tbl_estoque.getColumnModel().getColumn(1).setPreferredWidth(400);
        tbl_estoque.getColumnModel().getColumn(1).setResizable(false);
        tbl_estoque.getColumnModel().getColumn(2).setPreferredWidth(70);
        tbl_estoque.getColumnModel().getColumn(2).setResizable(false); 
//        tbl_estoque.getColumnModel().getColumn(3).setPreferredWidth(60);
//        tbl_estoque.getColumnModel().getColumn(3).setResizable(false);
//        tbl_estoque.getColumnModel().getColumn(4).setPreferredWidth(20);
//        tbl_estoque.getColumnModel().getColumn(4).setResizable(false);
        tbl_estoque.getTableHeader().setReorderingAllowed(false);
//        tbl_estoque.setAutoResizeMode(tbl_estoque.AUTO_RESIZE_OFF);
        tbl_estoque.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conecBanc.desconectar();
    }//  FINAL METODO PARA IMPRIMIR TABELA NA INTERFACE
        
    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        modoNavegar= "btn_add";
        manipularInterface();
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_confirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmaActionPerformed

        ct_data.setText(forma.format(hoje)); // CAIXA DE TEXTO RECEBE A DATA
        int qtdAtual=0;
        int novaQtd=0;
        int qtdAnterior=0;
        conecEstoq.conexaoBanco();
        conecBanc.conexaoBanco();
        try {
            qtdAtual = conecBanc.rs.getInt("quantidade");
            novaQtd = qtdAtual + Integer.parseInt(ct_addEstoque.getText());
            qtdAnterior = Integer.parseInt(ct_addEstoque.getText());

            PreparedStatement pst = conecBanc.conn.prepareStatement("update produto set quantidade=? where id_produto=?");
            pst.setInt(1,novaQtd);
            pst.setInt(2, idProd);
            pst.execute();

            conecEstoq.executaSQL("select from estoque where id_produto='"+idProd+"'");
            pst = conecEstoq.conn.prepareStatement("update estoque set qtd_adicionada=?, data_alteracao=?, qtd_total=? where id_produto=?");
            pst.setInt(1, Integer.parseInt(ct_addEstoque.getText()));
            pst.setString(2, ct_data.getText());
            pst.setInt(3, novaQtd);
            pst.setInt(4, idProd);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Estoque Atualizado");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao Alterar Produto!"+ex);
        }
        preecherTabela("select * from produto");
        conecBanc.desconectar();
        conecEstoq.desconectar();

        modoNavegar ="Inicializar";
        manipularInterface();
    }//GEN-LAST:event_btn_confirmaActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        modoNavegar = "Inicializar";
        manipularInterface();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void ct_preco_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct_preco_compraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct_preco_compraActionPerformed

    private void ct_codBarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct_codBarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct_codBarraActionPerformed

    private void ct_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct_dataActionPerformed

    private void tbl_estoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_estoqueMouseClicked
        modoNavegar = "Navegar";
        manipularInterface();

        String nome_produto =""+ tbl_estoque.getValueAt(tbl_estoque.getSelectedRow(), 1);
        conecBanc.conexaoBanco();
        conecEstoq.conexaoBanco();

        try {
            conecBanc.executaSQL("select * from produto where nome_produto='" +nome_produto+"'");
            conecBanc.rs.first();
            idProd = conecBanc.rs.getInt("id_produto");
            ct_codBarra.setText(conecBanc.rs.getString("codbarra"));
            ct_produto.setText(conecBanc.rs.getString("nome_produto"));
            ct_quantidade.setText(String.valueOf(conecBanc.rs.getInt("quantidade")));
            ct_preco_compra.setText((String.valueOf(numberFormat.format(conecBanc.rs.getFloat("preco_compra")))));
            ct_preco_venda.setText(String.valueOf(numberFormat.format(conecBanc.rs.getFloat("preco_venda"))));

            conecEstoq.executaSQL("select * from estoque where id_produto='"+idProd+"'");
            conecEstoq.rs.first();

            ct_qtdAnterior.setText(String.valueOf(conecEstoq.rs.getInt("qtd_adicionada")));
            ct_data.setText(conecEstoq.rs.getString("data_alteracao"));
            ct_qtdTotal.setText(String.valueOf(conecEstoq.rs.getInt("qtd_total")));

            conecBanc.desconectar();
            conecEstoq.desconectar();

            // JOptionPane.showMessageDialog(rootPane, nome_tabela);
        } catch (SQLException ex) {
            //              JOptionPane.showMessageDialog(rootPane, "Erro ao Selecionar os Dados!"+ex);
        }

    }//GEN-LAST:event_tbl_estoqueMouseClicked

    private void ct_pesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ct_pesquisarMouseClicked
        ct_pesquisar.selectAll();
    }//GEN-LAST:event_ct_pesquisarMouseClicked

    private void ct_pesquisarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ct_pesquisarMouseEntered

    }//GEN-LAST:event_ct_pesquisarMouseEntered

    private void ct_pesquisarComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ct_pesquisarComponentResized

    }//GEN-LAST:event_ct_pesquisarComponentResized

    private void ct_pesquisarComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ct_pesquisarComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_ct_pesquisarComponentShown

    private void ct_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct_pesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct_pesquisarActionPerformed

    private void ct_pesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_pesquisarKeyReleased
        //        modoNavegar = "Navegar";
        //        manipularInterface();
        preecherTabela("select * from produto where nome_produto like '%" + ct_pesquisar.getText() + "%' or codbarra like '%"+ct_pesquisar.getText()+"'");
    }//GEN-LAST:event_ct_pesquisarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_confirma;
    private javax.swing.JTextField ct_addEstoque;
    private javax.swing.JTextField ct_codBarra;
    private javax.swing.JTextField ct_data;
    private javax.swing.JTextField ct_pesquisar;
    private javax.swing.JTextField ct_preco_compra;
    private javax.swing.JTextField ct_preco_venda;
    private javax.swing.JTextField ct_produto;
    private javax.swing.JTextField ct_qtdAnterior;
    private javax.swing.JTextField ct_qtdTotal;
    private javax.swing.JTextField ct_quantidade;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_estoque;
    // End of variables declaration//GEN-END:variables
}
