/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConectaBanco;
import Controle.ModeloTabela;
import com.lowagie.text.Font;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author NOTBOOK DE MAYCON
 */
public class FrmEstado extends javax.swing.JInternalFrame {
    String modoNavegar; //VARIAVEL DE NAVEGAÇÃO NA INTERFACE
    ConectaBanco conecBanco = new ConectaBanco(); // INSTANCIA DA CLASSE DE CONEXÃO 

    public FrmEstado() {
        initComponents();
       Locale.setDefault(new Locale("pt","BR"));
          UIManager.put("OptionPane.messageFont", new FontUIResource( "Arial", Font.NORMAL, 17));
             UIManager.put("OptionPane.yesButtonText", "Confirma");
              UIManager.put("OptionPane.noButtonText", "Cancelar");
              
        conecBanco.conexaoBanco(); // CHAMADA DO MÉTODO DE CONEXÃO
        preecherTabela("select * from estados order by  id_estado");
        modoNavegar = "Inicializar";
        manipularInterface();
        conecBanco.desconectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        ct_pesquisaEstado = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstado = new javax.swing.JTable();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel103 = new javax.swing.JPanel();
        jTextFieldCod = new javax.swing.JTextField();
        jPanel101 = new javax.swing.JPanel();
        jTextFieldNome = new javax.swing.JTextField();
        jPanel102 = new javax.swing.JPanel();
        jTextFieldSigla = new javax.swing.JTextField();

        setClosable(true);
        setTitle("FORMULÁRIO DE CADASTRO DE ESTADO");
        setPreferredSize(new java.awt.Dimension(1068, 576));

        jDesktopPane1.setBackground(new java.awt.Color(102, 102, 255));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButtonNovo.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNovo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/NOVO.png"))); // NOI18N
        jButtonNovo.setToolTipText("NOVO CADASTRO");
        jButtonNovo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jButtonNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        jButtonSalvar.setToolTipText("SALVAR");
        jButtonSalvar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jButtonSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonEditar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonEditar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EDITAR.png"))); // NOI18N
        jButtonEditar.setToolTipText("EDITAR");
        jButtonEditar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jButtonEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonDeletar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonDeletar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir.png"))); // NOI18N
        jButtonDeletar.setToolTipText("EXCLUIR");
        jButtonDeletar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jButtonDeletar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        jButtonCancelar.setToolTipText("CANCELAR");
        jButtonCancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        jButtonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        ct_pesquisaEstado.setBackground(new java.awt.Color(0, 238, 255));
        ct_pesquisaEstado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ct_pesquisaEstado.setText("Caixa de Pesquisa...");
        ct_pesquisaEstado.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));
        ct_pesquisaEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ct_pesquisaEstadoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ct_pesquisaEstadoMousePressed(evt);
            }
        });
        ct_pesquisaEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct_pesquisaEstadoActionPerformed(evt);
            }
        });
        ct_pesquisaEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_pesquisaEstadoKeyReleased(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "Lista de Estados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 17))); // NOI18N
        jPanel1.setOpaque(false);

        jTableEstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableEstado.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTableEstado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableEstado.setIntercellSpacing(new java.awt.Dimension(0, 4));
        jTableEstado.setOpaque(false);
        jTableEstado.setSelectionBackground(new java.awt.Color(255, 255, 102));
        jTableEstado.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTableEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEstadoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableEstadoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEstado);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jDesktopPane2.setBackground(new java.awt.Color(51, 0, 204));
        jDesktopPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jPanel103.setBackground(new java.awt.Color(197, 196, 195));
        jPanel103.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Código", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel103.setOpaque(false);

        jTextFieldCod.setEditable(false);
        jTextFieldCod.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        jTextFieldCod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jTextFieldCod.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTextFieldCod.setEnabled(false);
        jTextFieldCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel103Layout = new javax.swing.GroupLayout(jPanel103);
        jPanel103.setLayout(jPanel103Layout);
        jPanel103Layout.setHorizontalGroup(
            jPanel103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldCod, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
        );
        jPanel103Layout.setVerticalGroup(
            jPanel103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldCod, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
        );

        jPanel101.setBackground(new java.awt.Color(197, 196, 195));
        jPanel101.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nome do Estado", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel101.setOpaque(false);

        jTextFieldNome.setBackground(new java.awt.Color(255, 255, 102));
        jTextFieldNome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextFieldNome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jTextFieldNome.setCaretColor(new java.awt.Color(255, 0, 0));
        jTextFieldNome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldNome.setEnabled(false);
        jTextFieldNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNomeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel101Layout = new javax.swing.GroupLayout(jPanel101);
        jPanel101.setLayout(jPanel101Layout);
        jPanel101Layout.setHorizontalGroup(
            jPanel101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldNome, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
        );
        jPanel101Layout.setVerticalGroup(
            jPanel101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel102.setBackground(new java.awt.Color(197, 196, 195));
        jPanel102.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Sigla", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel102.setOpaque(false);

        jTextFieldSigla.setBackground(new java.awt.Color(255, 255, 102));
        jTextFieldSigla.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextFieldSigla.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldSigla.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jTextFieldSigla.setCaretColor(new java.awt.Color(255, 0, 0));
        jTextFieldSigla.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldSigla.setEnabled(false);
        jTextFieldSigla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSiglaActionPerformed(evt);
            }
        });
        jTextFieldSigla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSiglaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel102Layout = new javax.swing.GroupLayout(jPanel102);
        jPanel102.setLayout(jPanel102Layout);
        jPanel102Layout.setHorizontalGroup(
            jPanel102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextFieldSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel102Layout.setVerticalGroup(
            jPanel102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel102Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextFieldSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jDesktopPane2.setLayer(jPanel103, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel101, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel102, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jDesktopPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ct_pesquisaEstado, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jDesktopPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ct_pesquisaEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(305, Short.MAX_VALUE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ct_pesquisaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        setSize(new java.awt.Dimension(1068, 572));
    }// </editor-fold>//GEN-END:initComponents

    
        public void manipularInterface(){ //MANIPULA A NAVEGAÇÃO 
        switch (modoNavegar){
            
             case "Inicializar":
                 jTextFieldCod.setText("");
                 jTextFieldNome.setText("");
                 jTextFieldSigla.setText("");
                 
                 jButtonCancelar.setEnabled(false);
                 jButtonDeletar.setEnabled(false);
                 jButtonEditar.setEnabled(false);
                 jButtonNovo.setEnabled(true);
                 jButtonSalvar.setEnabled(false);;
                 jTextFieldCod.setEnabled(false);
                 jTextFieldNome.setEnabled(false);
                 jTextFieldSigla.setEnabled(false);
                 jTextFieldNome.setBackground(new Color(255,255,102));
                 jTextFieldSigla.setBackground(new Color(255,255,102));
                 break;
            
            case "Navegar":
                 jTextFieldCod.setText("");
                 jTextFieldNome.setText("");
                 jTextFieldSigla.setText("");
                 
                 jButtonDeletar.setEnabled(true);
                 jButtonEditar.setEnabled(true);
                 jButtonNovo.setEnabled(true);
                 jButtonSalvar.setEnabled(false);;
                 jButtonCancelar.setEnabled(true);
                 jTextFieldCod.setEnabled(false);
                 jTextFieldNome.setEnabled(false);
                 jTextFieldSigla.setEnabled(false);
                 jTextFieldNome.setBackground(new Color(255,255,102));
                 jTextFieldSigla.setBackground(new Color(255,255,102));
                 break;
                  
            case "Novo":
                 jButtonCancelar.setEnabled(true);
                 jTextFieldCod.setText("");
                 jTextFieldNome.setText("");
                 jTextFieldSigla.setText("");
                 jButtonDeletar.setEnabled(false);
                 jButtonEditar.setEnabled(false);
                 jButtonNovo.setEnabled(false);
                 jButtonSalvar.setEnabled(true);;
                 jTextFieldCod.setEnabled(false);
                 jTextFieldNome.setEnabled(true);
                 jTextFieldSigla.setEnabled(true);
                 jTextFieldNome.setBackground(new Color(255,255,102));
                 jTextFieldSigla.setBackground(new Color(255,255,102));
                 break;

            case "Editar":
                 jButtonCancelar.setEnabled(true);
                 jButtonDeletar.setEnabled(true);
                 jButtonEditar.setEnabled(false);
                 jButtonNovo.setEnabled(false);
                 jButtonSalvar.setEnabled(true);;
                 jTextFieldCod.setEnabled(false);
                 jTextFieldNome.setEnabled(true);
                 jTextFieldSigla.setEnabled(true);
                 jTextFieldNome.setBackground(new Color(255,255,102));
                 jTextFieldSigla.setBackground(new Color(255,255,102));
                 break;
                 
            default:
                break;
          }
   } //METODO DE DE NAVEGAÇÃO NA INTERFACE
        
    public void preecherTabela(String SQL){ // METODO PARA PREENCHER TABELA NA INTERFACE
        ArrayList dados = new ArrayList();
        String [] Colunas  = new String []{"Código", "Nome", "Sigla"};
        
        conecBanco.executaSQL(SQL);
      try {
          conecBanco.rs.first();
          do {
              dados.add(new Object[]{conecBanco.rs.getInt("id_estado"),conecBanco.rs.getString("nome_estado"),conecBanco.rs.getString("sigla_estado")});
          }while (conecBanco.rs.next());
          
      } catch (SQLException ex) {
//         JOptionPane.showMessageDialog(rootPane, "Erro ao Preencher o ArrayList! \n"+ ex.getMessage());
      }
      
       ModeloTabela modelo = new ModeloTabela(dados,Colunas);
       
        jTableEstado.setModel(modelo);
        DefaultTableCellRenderer headerRenderer2 = new DefaultTableCellRenderer(); 
        headerRenderer2.setOpaque(true); 
        headerRenderer2.setBackground(new Color(0,0,51));
        headerRenderer2.setFont(new java.awt.Font("Arial Black", Font.BOLD, 23));
        headerRenderer2.setForeground(new Color(255,255,255));
        for (int i = 0; i < jTableEstado.getModel().getColumnCount(); 
         i++) { jTableEstado.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer2); }

            jTableEstado.setRowHeight(30); //  TAMANHO DA JANELA PRA CADA ITEM
            
        jTableEstado.getColumnModel().getColumn(0).setPreferredWidth(63);
        jTableEstado.getColumnModel().getColumn(0).setResizable(false);
        jTableEstado.getColumnModel().getColumn(1).setPreferredWidth(320);
        jTableEstado.getColumnModel().getColumn(1).setResizable(false);
        jTableEstado.getColumnModel().getColumn(2).setPreferredWidth(65);
        jTableEstado.getColumnModel().getColumn(2).setResizable(false);
        jTableEstado.getTableHeader().setReorderingAllowed(false);
//        jTableEstado.setAutoResizeMode(jTableEstado.AUTO_RESIZE_OFF);
        jTableEstado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
    }//  FINAL METODO PARA IMPRIMIR TABELA NA INTERFACE
    
        
    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        modoNavegar = "Novo";
        manipularInterface();

    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        int op1, op2, op3;
        String nomeEstadoVerif="";
        conecBanco.conexaoBanco();
        try {
            conecBanco.executaSQL("select * from estados where nome_estado='"+jTextFieldNome.getText()+"'");
            conecBanco.rs.first();
            nomeEstadoVerif=conecBanco.rs.getString("nome_estado");
        } catch (SQLException ex) {
          
        }

        if(jTextFieldNome.getText().equals("")){
            jTextFieldNome.setBackground(new Color(246,170,170));
            op1=1;
        }else{
            jTextFieldNome.setBackground(new Color(255,255,102));
            op1=2;
        }
        
        if(jTextFieldSigla.getText().equals("")){
            jTextFieldSigla.setBackground(new Color(246,170,170));
            op2=1;
        }else{
            jTextFieldSigla.setBackground(new Color(255,255,102));
            op2=2;
        }
        
        if(jTextFieldNome.getText().equals(nomeEstadoVerif)){
            op3=1;
        }else{
            op3=2;
        }
        
        if(op1==2 && op2==2){
            if(modoNavegar.equals("Novo")){ // NOVO CADASTRO
                    if(op3==1){
                        JOptionPane.showMessageDialog(null,"Nome de estado já cadastrado! \nTente outro nome.","Erro",JOptionPane.ERROR_MESSAGE);
                    }else{
                        int resposta=  JOptionPane.showConfirmDialog(null, "Salvar novo estado?", "Novo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);    
                        if(resposta== JOptionPane.YES_NO_OPTION){
                            try {
                                PreparedStatement pst = conecBanco.conn.prepareStatement("insert into estados(nome_estado, sigla_estado)values(?,?)");// PASSAGEM DO SQL PARA DE INSERÇÃO DE DADOS
                                pst.setString(1, jTextFieldNome.getText()); // PASSAGEM DOS PARÁMETROS
                                pst.setString(2, jTextFieldSigla.getText());
                                pst.executeUpdate(); // EXECUTA A INSERÇÃO
                                JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso!");
                                modoNavegar ="Inicializar";
                                manipularInterface();

                            } catch (SQLException ex) {
                                JOptionPane.showMessageDialog(rootPane, "Erro na inserção \n"+ ex);
                            }
                        }else{ 
                        }
                    }

            }
            
            if(modoNavegar.equals("Editar")){ // EDITAR CADASTRO
                    int resposta=  JOptionPane.showConfirmDialog(null, "Deseja salvar as alterações?", "Alteração",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);    
                    if(resposta== JOptionPane.YES_NO_OPTION){
                        try {
                            PreparedStatement pst= conecBanco.conn.prepareStatement("update estados set nome_estado= ?, sigla_estado=? where id_estado=?");
                            pst.setString(1, jTextFieldNome.getText());
                            pst.setString(2, jTextFieldSigla.getText());
                            pst.setInt(3, Integer.parseInt(jTextFieldCod.getText()));
                            pst.execute();
                            JOptionPane.showMessageDialog(rootPane, "Alterado com sucesso!");
                            modoNavegar ="Navegar";
                            manipularInterface();
                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(rootPane, "Erro ao Alterar \n"+ ex.getMessage());
                        }
                    }
                }
            
            preecherTabela("select * from estados order by  id_estado"); // IMPRIMI TABELA TODA VEZ QUE CHAMA UM MODO DE NAVEGAÇÃO
        }else{
         JOptionPane.showMessageDialog(null,"Campo obrigatório não preenchido!","Erro",JOptionPane.ERROR_MESSAGE);    
        }
        conecBanco.desconectar();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        modoNavegar = "Editar";
        manipularInterface();
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
       int respost=JOptionPane.showConfirmDialog(null,"Deseja excluir estado?","Excluir",JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE);
       if(respost==JOptionPane.YES_NO_OPTION){
        conecBanco.conexaoBanco();
        try {
            PreparedStatement pst= conecBanco.conn.prepareStatement("delete from estados where id_estado=?");
            pst.setInt(1, Integer.parseInt(jTextFieldCod.getText()));
            pst.execute();
            JOptionPane.showMessageDialog(rootPane, "Excluido com sucesso!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Excluir \n"+ ex);
        }
        preecherTabela("select * from estados order by  id_estado"); // IMPRIMI TABELA TODA VEZ QUE CHAMA UM MODO DE NAVEGAÇÃO
        conecBanco.desconectar();

        modoNavegar = "Inicializar";
        manipularInterface();
       }else{
           
       }
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        modoNavegar = "Inicializar";
        manipularInterface();

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextFieldCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodActionPerformed

    private void jTextFieldSiglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSiglaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSiglaActionPerformed

    private void jTableEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEstadoMouseClicked
 
    }//GEN-LAST:event_jTableEstadoMouseClicked

    private void ct_pesquisaEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ct_pesquisaEstadoMouseClicked
    
    }//GEN-LAST:event_ct_pesquisaEstadoMouseClicked

    private void ct_pesquisaEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct_pesquisaEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct_pesquisaEstadoActionPerformed

    private void ct_pesquisaEstadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_pesquisaEstadoKeyReleased
        conecBanco.conexaoBanco();
        preecherTabela("select * from estados where nome_estado like '%" +ct_pesquisaEstado.getText() +"%' or sigla_estado like '%" +ct_pesquisaEstado.getText()+"%'"+"");
        conecBanco.desconectar();
    }//GEN-LAST:event_ct_pesquisaEstadoKeyReleased

    private void jTableEstadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEstadoMousePressed
        modoNavegar ="Navegar";
        manipularInterface();
        String codigoEstado = ""+jTableEstado.getValueAt(jTableEstado.getSelectedRow(), 0);
        conecBanco.conexaoBanco();
            try {
                conecBanco.executaSQL("select * from estados where id_estado='"+codigoEstado+"'");
                conecBanco.rs.first();
                jTextFieldCod.setText(String.valueOf(conecBanco.rs.getInt("id_estado")));
                jTextFieldNome.setText(conecBanco.rs.getString("nome_estado"));
                jTextFieldSigla.setText(conecBanco.rs.getString("sigla_estado"));
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao clicar \n"+ ex.getMessage());
            }
        conecBanco.desconectar(); // DESLIGA CONEXÃO (NAO CONSEGUE FAZER ALGUMAS FUNÇÃO COMO EDITAR, CASO ESTEJA ATIVA).
    }//GEN-LAST:event_jTableEstadoMousePressed

    private void jTextFieldSiglaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSiglaKeyReleased
         if(jTextFieldSigla.getText().length()>=2){
          jTextFieldSigla.setText(jTextFieldSigla.getText().substring(0,2));
     }else{
     } 
        
    }//GEN-LAST:event_jTextFieldSiglaKeyReleased

    private void jTextFieldNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeKeyReleased
     if(jTextFieldNome.getText().length()>=25){
        jTextFieldNome.setText(jTextFieldNome.getText().substring(0,25));
     }else{
     } 
    }//GEN-LAST:event_jTextFieldNomeKeyReleased

    private void ct_pesquisaEstadoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ct_pesquisaEstadoMousePressed
 
    }//GEN-LAST:event_ct_pesquisaEstadoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ct_pesquisaEstado;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel101;
    private javax.swing.JPanel jPanel102;
    private javax.swing.JPanel jPanel103;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEstado;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldSigla;
    // End of variables declaration//GEN-END:variables
}
