/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConectaBanco;
import Controle.ControleFornecedor;
import Controle.ModeloTabela;
import Modelo.ModeloFornecedor;
import com.lowagie.text.Font;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.border.LineBorder;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author NOTBOOK DE MAYCON
 */
public class FrmFornecedor extends javax.swing.JInternalFrame {
   ConectaBanco conecBanco = new ConectaBanco();
   ModeloFornecedor mod = new ModeloFornecedor();
   ControleFornecedor control = new ControleFornecedor();
    String modoNavegar;
    int opBairro;
    
    public FrmFornecedor() {
        initComponents();
         Locale.setDefault(new Locale("pt","BR"));
          UIManager.put("OptionPane.messageFont", new FontUIResource( "Arial", Font.NORMAL, 17));
            UIManager.put("OptionPane.yesButtonText", "Confirma");
             UIManager.put("OptionPane.noButtonText", "Cancelar");
             
         try {
           MaskFormatter form = new MaskFormatter("##.###.###/####-##"); // elemento para criar formatato de mascara
           ctFor_cnpj.setFormatterFactory(new DefaultFormatterFactory(form)); //atribui a mascara ao campo
           
        } catch (ParseException ex) {
           
        }
        try {
          MaskFormatter form    = new MaskFormatter("(##)9.####-####"); // elemento para criar formatato de mascara
          ctFor_telefone1.setFormatterFactory(new DefaultFormatterFactory(form)); //atribui a mascara ao campo
           MaskFormatter form2    = new MaskFormatter("(##)9.####-####"); // elemento para criar formatato de mascara
          ctFoR_telefone2.setFormatterFactory(new DefaultFormatterFactory(form2)); //atribui a mascara ao campo
        } catch (ParseException ex) {
           
        }
        
        preencherCombobox();
        preecherTabela("select * from fornecedores");
        modoNavegar = "Inicializar";
        manipularInterface();       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btn_novo = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        ct_pesquisaFor = new javax.swing.JTextField();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel103 = new javax.swing.JPanel();
        ct_ID = new javax.swing.JTextField();
        jPanel105 = new javax.swing.JPanel();
        ct_nome = new javax.swing.JTextField();
        jPanel106 = new javax.swing.JPanel();
        ct_endereco = new javax.swing.JTextField();
        jPanel104 = new javax.swing.JPanel();
        ctFor_telefone1 = new javax.swing.JFormattedTextField();
        jPanel108 = new javax.swing.JPanel();
        ctFoR_telefone2 = new javax.swing.JFormattedTextField();
        jPanel109 = new javax.swing.JPanel();
        ctFor_cnpj = new javax.swing.JFormattedTextField();
        jPanel110 = new javax.swing.JPanel();
        ct_nomefantasia = new javax.swing.JFormattedTextField();
        jPanel107 = new javax.swing.JPanel();
        cbox_bairro = new javax.swing.JComboBox<>();
        btn_addNovoBairro = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cadastroForn = new javax.swing.JTable();

        setClosable(true);
        setTitle("FORMULÁRIA DE CADASTRO FORNECEDOR");

        jDesktopPane1.setBackground(new java.awt.Color(51, 102, 255));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        jPanel6.setForeground(new java.awt.Color(102, 102, 102));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        btn_novo.setBackground(new java.awt.Color(255, 255, 255));
        btn_novo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/NOVO.png"))); // NOI18N
        btn_novo.setToolTipText("NOVO");
        btn_novo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_salvar.setBackground(new java.awt.Color(255, 255, 255));
        btn_salvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        btn_salvar.setToolTipText("SALVAR");
        btn_salvar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_salvar.setEnabled(false);
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_editar.setBackground(new java.awt.Color(255, 255, 255));
        btn_editar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EDITAR.png"))); // NOI18N
        btn_editar.setToolTipText("EDITAR");
        btn_editar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_editar.setEnabled(false);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_excluir.setBackground(new java.awt.Color(255, 255, 255));
        btn_excluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir.png"))); // NOI18N
        btn_excluir.setToolTipText("EXCLUIR");
        btn_excluir.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_excluir.setEnabled(false);
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        btn_cancelar.setToolTipText("CANCELAR");
        btn_cancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_cancelar.setEnabled(false);
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_novo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        ct_pesquisaFor.setBackground(new java.awt.Color(0, 238, 255));
        ct_pesquisaFor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ct_pesquisaFor.setText("Pesquisar fornecedor");
        ct_pesquisaFor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));
        ct_pesquisaFor.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_pesquisaFor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ct_pesquisaForMouseClicked(evt);
            }
        });
        ct_pesquisaFor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct_pesquisaForActionPerformed(evt);
            }
        });
        ct_pesquisaFor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_pesquisaForKeyReleased(evt);
            }
        });

        jDesktopPane2.setBackground(new java.awt.Color(102, 0, 255));
        jDesktopPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jPanel103.setBackground(new java.awt.Color(197, 196, 195));
        jPanel103.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Código", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel103.setOpaque(false);

        ct_ID.setEditable(false);
        ct_ID.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        ct_ID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ct_ID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_ID.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        ct_ID.setEnabled(false);

        javax.swing.GroupLayout jPanel103Layout = new javax.swing.GroupLayout(jPanel103);
        jPanel103.setLayout(jPanel103Layout);
        jPanel103Layout.setHorizontalGroup(
            jPanel103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        jPanel103Layout.setVerticalGroup(
            jPanel103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel103Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ct_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel105.setBackground(new java.awt.Color(197, 196, 195));
        jPanel105.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nome do Fornecedor*", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel105.setOpaque(false);

        ct_nome.setBackground(new java.awt.Color(255, 255, 102));
        ct_nome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ct_nome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_nome.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_nome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_nome.setEnabled(false);
        ct_nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_nomeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel105Layout = new javax.swing.GroupLayout(jPanel105);
        jPanel105.setLayout(jPanel105Layout);
        jPanel105Layout.setHorizontalGroup(
            jPanel105Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel105Layout.setVerticalGroup(
            jPanel105Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_nome, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel106.setBackground(new java.awt.Color(197, 196, 195));
        jPanel106.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Endereço", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel106.setOpaque(false);

        ct_endereco.setBackground(new java.awt.Color(255, 255, 102));
        ct_endereco.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ct_endereco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_endereco.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_endereco.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_endereco.setEnabled(false);
        ct_endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct_enderecoActionPerformed(evt);
            }
        });
        ct_endereco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_enderecoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel106Layout = new javax.swing.GroupLayout(jPanel106);
        jPanel106.setLayout(jPanel106Layout);
        jPanel106Layout.setHorizontalGroup(
            jPanel106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_endereco)
        );
        jPanel106Layout.setVerticalGroup(
            jPanel106Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel106Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ct_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel104.setBackground(new java.awt.Color(197, 196, 195));
        jPanel104.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Telefone I", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel104.setOpaque(false);

        ctFor_telefone1.setBackground(new java.awt.Color(255, 255, 102));
        ctFor_telefone1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ctFor_telefone1.setCaretColor(new java.awt.Color(255, 0, 0));
        ctFor_telefone1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ctFor_telefone1.setEnabled(false);
        ctFor_telefone1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel104Layout = new javax.swing.GroupLayout(jPanel104);
        jPanel104.setLayout(jPanel104Layout);
        jPanel104Layout.setHorizontalGroup(
            jPanel104Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ctFor_telefone1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        );
        jPanel104Layout.setVerticalGroup(
            jPanel104Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel104Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ctFor_telefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel108.setBackground(new java.awt.Color(197, 196, 195));
        jPanel108.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Telefone II", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel108.setOpaque(false);

        ctFoR_telefone2.setBackground(new java.awt.Color(255, 255, 102));
        ctFoR_telefone2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ctFoR_telefone2.setCaretColor(new java.awt.Color(255, 0, 0));
        ctFoR_telefone2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ctFoR_telefone2.setEnabled(false);
        ctFoR_telefone2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel108Layout = new javax.swing.GroupLayout(jPanel108);
        jPanel108.setLayout(jPanel108Layout);
        jPanel108Layout.setHorizontalGroup(
            jPanel108Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ctFoR_telefone2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        );
        jPanel108Layout.setVerticalGroup(
            jPanel108Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel108Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ctFoR_telefone2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel109.setBackground(new java.awt.Color(197, 196, 195));
        jPanel109.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "CNPJ*", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel109.setOpaque(false);

        ctFor_cnpj.setBackground(new java.awt.Color(255, 255, 102));
        ctFor_cnpj.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ctFor_cnpj.setCaretColor(new java.awt.Color(255, 0, 0));
        ctFor_cnpj.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ctFor_cnpj.setEnabled(false);
        ctFor_cnpj.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel109Layout = new javax.swing.GroupLayout(jPanel109);
        jPanel109.setLayout(jPanel109Layout);
        jPanel109Layout.setHorizontalGroup(
            jPanel109Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ctFor_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel109Layout.setVerticalGroup(
            jPanel109Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel109Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ctFor_cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel110.setBackground(new java.awt.Color(197, 196, 195));
        jPanel110.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nome Fantasia", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel110.setOpaque(false);

        ct_nomefantasia.setBackground(new java.awt.Color(255, 255, 102));
        ct_nomefantasia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_nomefantasia.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_nomefantasia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_nomefantasia.setEnabled(false);
        ct_nomefantasia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ct_nomefantasia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_nomefantasiaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel110Layout = new javax.swing.GroupLayout(jPanel110);
        jPanel110.setLayout(jPanel110Layout);
        jPanel110Layout.setHorizontalGroup(
            jPanel110Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_nomefantasia)
        );
        jPanel110Layout.setVerticalGroup(
            jPanel110Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_nomefantasia, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel107.setBackground(new java.awt.Color(197, 196, 195));
        jPanel107.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Bairro*", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel107.setOpaque(false);
        jPanel107.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel107MouseEntered(evt);
            }
        });

        cbox_bairro.setBackground(new java.awt.Color(252, 252, 146));
        cbox_bairro.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        cbox_bairro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbox_bairro.setToolTipText("");
        cbox_bairro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cbox_bairro.setEnabled(false);
        cbox_bairro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbox_bairroMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbox_bairroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbox_bairroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbox_bairroMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbox_bairroMouseReleased(evt);
            }
        });
        cbox_bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_bairroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel107Layout = new javax.swing.GroupLayout(jPanel107);
        jPanel107.setLayout(jPanel107Layout);
        jPanel107Layout.setHorizontalGroup(
            jPanel107Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbox_bairro, 0, 263, Short.MAX_VALUE)
        );
        jPanel107Layout.setVerticalGroup(
            jPanel107Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cbox_bairro, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        btn_addNovoBairro.setBackground(new java.awt.Color(204, 204, 204));
        btn_addNovoBairro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_addNovoBairro.setForeground(new java.awt.Color(51, 204, 0));
        btn_addNovoBairro.setText("NOVO BAIRRO");
        btn_addNovoBairro.setEnabled(false);
        btn_addNovoBairro.setOpaque(false);
        btn_addNovoBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addNovoBairroActionPerformed(evt);
            }
        });

        jDesktopPane2.setLayer(jPanel103, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel105, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel106, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel104, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel108, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel109, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel110, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel107, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btn_addNovoBairro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel106, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addComponent(jPanel103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel105, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel110, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                                .addComponent(jPanel109, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel104, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel108, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel107, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 725, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_addNovoBairro)
                                .addGap(4, 4, 4)))
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel103, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel110, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel105, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel107, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel108, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel104, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel109, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(2, 2, 2)
                .addComponent(btn_addNovoBairro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel106, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "Lista de Fornecedor", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 17))); // NOI18N
        jPanel1.setOpaque(false);

        tbl_cadastroForn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbl_cadastroForn.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tbl_cadastroForn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_cadastroForn.setIntercellSpacing(new java.awt.Dimension(0, 4));
        tbl_cadastroForn.setOpaque(false);
        tbl_cadastroForn.setSelectionBackground(new java.awt.Color(255, 255, 102));
        tbl_cadastroForn.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tbl_cadastroForn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_cadastroFornMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_cadastroFornMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_cadastroForn);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(jPanel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ct_pesquisaFor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jDesktopPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ct_pesquisaFor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(ct_pesquisaFor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        setSize(new java.awt.Dimension(1068, 572));
    }// </editor-fold>//GEN-END:initComponents

        public void manipularInterface(){ //MANIPULA A NAVEGAÇÃO 
        switch (modoNavegar){
            
            
            case "Inicializar":
                 ct_ID.setText("");
                 ct_nome.setText("");
                 ct_nomefantasia.setText("");
                 ctFor_cnpj.setText("");
                 ctFor_telefone1.setText("");
                 ctFoR_telefone2.setText("");
                 cbox_bairro.setSelectedItem(null);
                 ct_endereco.setText("");

                 ctFoR_telefone2.setEnabled(false);
                 ctFor_telefone1.setEnabled(false);
                 ct_ID.setEnabled(false);
                 ct_nome.setEnabled(false);
                 ct_endereco.setEnabled(false);
                 ctFor_cnpj.setEnabled(false);
                 cbox_bairro.setEnabled(false);
                 ct_nomefantasia.setText("");
                 ct_nomefantasia.setEnabled(false);
                 btn_novo.setEnabled(true);;
                 btn_salvar.setEnabled(false);
                 btn_editar.setEnabled(false);
                 btn_excluir.setEnabled(false);
                 btn_cancelar.setEnabled(false);
                 btn_addNovoBairro.setEnabled(false);
                 btn_addNovoBairro.setVisible(false);
                 cbox_bairro.setBorder(new LineBorder(null));
                 ct_nome.setBackground(new Color(255,255,102));
                 ctFor_cnpj.setBackground(new Color(255,255,102));
                 
                 break;
                 
            case "Navegar":
                 ct_ID.setText("");
                 ct_nome.setText("");
                 ct_nomefantasia.setText("");
                 ctFor_cnpj.setText("");
                 ctFor_telefone1.setText("");
                 ctFoR_telefone2.setText("");
                 cbox_bairro.setSelectedItem(null);
                 ct_endereco.setText("");
                 
                 ctFor_telefone1.setEnabled(false);
                 btn_addNovoBairro.setEnabled(false);
                 ct_ID.setEnabled(false);
                 ct_nome.setEnabled(false);
                 ct_endereco.setEnabled(false);
                 ctFor_cnpj.setEnabled(false);
                 cbox_bairro.setEnabled(false);
                 ctFoR_telefone2.setEnabled(false);
                 ct_nomefantasia.setEnabled(false);
                 btn_novo.setEnabled(true);;
                 btn_salvar.setEnabled(false);
                 btn_editar.setEnabled(true);
                 btn_excluir.setEnabled(true);
                 btn_cancelar.setEnabled(false);
                 btn_addNovoBairro.setVisible(false);
                 cbox_bairro.setBorder(new LineBorder(null));
                 ct_nome.setBackground(new Color(255,255,102));
                 ctFor_cnpj.setBackground(new Color(255,255,102));
                 
                 break;
                 
            case "Novo":
                 ct_ID.setText("");
                 ct_nome.setText("");
                 ct_nomefantasia.setText("");
                 ctFor_cnpj.setText("");
                 ctFor_telefone1.setText("");
                 ctFoR_telefone2.setText("");
                 cbox_bairro.setSelectedItem(null);
                 ct_endereco.setText("");

                 ctFor_telefone1.setEnabled(true);
                 ct_ID.setEnabled(false);
                 ct_nome.setEnabled(true);
                 ct_endereco.setEnabled(true);
                 ctFor_cnpj.setEnabled(true);
                 cbox_bairro.setEnabled(true);
                 ctFoR_telefone2.setEnabled(true);
                 ct_nomefantasia.setEnabled(true);
                 btn_novo.setEnabled(false);;
                 btn_salvar.setEnabled(true);
                 btn_editar.setEnabled(false);
                 btn_addNovoBairro.setEnabled(true);
                 btn_excluir.setEnabled(false);
                 btn_cancelar.setEnabled(true);
                 btn_addNovoBairro.setVisible(true);
                 cbox_bairro.setBorder(new LineBorder(null));
                 ct_nome.setBackground(new Color(255,255,102));
                 ctFor_cnpj.setBackground(new Color(255,255,102));
                 break;
           
            case "Editar":
                 ctFor_telefone1.setEnabled(true);
                 ct_ID.setEnabled(false);
                 ct_nome.setEnabled(true);
                 ct_endereco.setEnabled(true);
                 ctFor_cnpj.setEnabled(true);
                 cbox_bairro.setEnabled(true);
                 btn_novo.setEnabled(false);;
                 btn_salvar.setEnabled(true);
                 btn_editar.setEnabled(false);
                 btn_excluir.setEnabled(true);
                 btn_cancelar.setEnabled(true);
                 btn_addNovoBairro.setEnabled(true);
                 btn_addNovoBairro.setVisible(true);
                 ct_nomefantasia.setEnabled(true);
                 ctFoR_telefone2.setEnabled(true);
                 cbox_bairro.setBorder(new LineBorder(null));
                 ct_nome.setBackground(new Color(255,255,102));
                 ctFor_cnpj.setBackground(new Color(255,255,102));
                 break;
                 
            default:
                break;
          }
    }
    
    public void preecherTabela(String SQL){ // METODO PARA PREENCHER TABELA NA INTERFACE
        ArrayList dados = new ArrayList();
        String [] Colunas  = new String []{"Código","Nome", "Fantasia","CNPJ", "Telefone I"};
        conecBanco.conexaoBanco();
        conecBanco.executaSQL(SQL);
      try {
          conecBanco.rs.first();
          do {
              dados.add(new Object[]{conecBanco.rs.getString("id_fornecedor"),conecBanco.rs.getString("nome_fornecedor"),conecBanco.rs.getString("cnpj_fornecedor"), conecBanco.rs.getString("telefone_1"),conecBanco.rs.getString("telefone_2")});
          }while (conecBanco.rs.next());
          
      } catch (SQLException ex) {
      }
      
       ModeloTabela modelo = new ModeloTabela(dados,Colunas);
       
        tbl_cadastroForn.setModel(modelo);
        DefaultTableCellRenderer headerRenderer2 = new DefaultTableCellRenderer(); 
        headerRenderer2.setOpaque(true); 
        headerRenderer2.setBackground(new Color(0,0,51));
        headerRenderer2.setFont(new java.awt.Font("Arial Black", Font.BOLD, 23));
        headerRenderer2.setForeground(new Color(255,255,255));
        for (int i = 0; i < tbl_cadastroForn.getModel().getColumnCount(); 
         i++) { tbl_cadastroForn.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer2); }

            tbl_cadastroForn.setRowHeight(31); //  TAMANHO DA JANELA PRA CADA ITEM
           
        tbl_cadastroForn.getColumnModel().getColumn(0).setPreferredWidth(55);
        tbl_cadastroForn.getColumnModel().getColumn(0).setResizable(false);
        tbl_cadastroForn.getColumnModel().getColumn(1).setPreferredWidth(300);
        tbl_cadastroForn.getColumnModel().getColumn(1).setResizable(false);
        tbl_cadastroForn.getColumnModel().getColumn(2).setPreferredWidth(200);
        tbl_cadastroForn.getColumnModel().getColumn(2).setResizable(false);
        tbl_cadastroForn.getColumnModel().getColumn(3).setPreferredWidth(120);
        tbl_cadastroForn.getColumnModel().getColumn(3).setResizable(false);
        tbl_cadastroForn.getColumnModel().getColumn(3).setPreferredWidth(120);
        tbl_cadastroForn.getColumnModel().getColumn(3).setResizable(false);
        tbl_cadastroForn.getTableHeader().setReorderingAllowed(false);
        
        tbl_cadastroForn.setAutoResizeMode(tbl_cadastroForn.AUTO_RESIZE_OFF);
        tbl_cadastroForn.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        conecBanco.desconectar();
    }//  FINAL METODO PARA IMPRIMIR TABELA NA INTERFACE
    
        public void preencherCombobox(){
          conecBanco.conexaoBanco();
          conecBanco.executaSQL("select * from bairro order by nome_bairro");
          cbox_bairro.removeAllItems();
            try {
                conecBanco.rs.first();
                do{
                    cbox_bairro.addItem(""+conecBanco.rs.getString("nome_bairro"));
                } while(conecBanco.rs.next());
 
            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, "Erro ao preencher combobox Bairro"+ ex);
            }
          conecBanco.desconectar();
      }
        
    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        modoNavegar = "Novo";
        manipularInterface();
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
      int op1, op2, op3, op4, op5;
      String verificaCNPJ="", verificaNomeFor="";
       
       conecBanco.conexaoBanco();
       try {
           conecBanco.executaSQL("select * from fornecedores where cnpj_fornecedor='"+ctFor_cnpj.getText().replaceAll("[^0-9]","")+"'");
           conecBanco.rs.first();
           verificaCNPJ= conecBanco.rs.getString("cnpj_fornecedor");
           
       } catch (SQLException ex){
       }
          
       try {
           conecBanco.executaSQL("select * from fornecedores where nome_fornecedor='"+ct_nome.getText()+"'");
           conecBanco.rs.first();
           verificaNomeFor= conecBanco.rs.getString("nome_fornecedor");
       } catch (SQLException ex){
       }
       conecBanco.desconectar();
       
        if(ct_nome.getText().equals("")){
            ct_nome.setBackground(new Color(246,170,170));
            op1=1;       
        }else{
            ct_nome .setBackground(new Color(255,255,102));
            op1=2;  
        }
        
        if(ctFor_cnpj.getText().replaceAll("[^0-9]","").equals("")){
            ctFor_cnpj.setBackground(new Color(246,170,170));
            op2=1;       
        }else{
            ctFor_cnpj.setBackground(new Color(255,255,102));
            op2=2;  
        }
        
        if(cbox_bairro.getSelectedIndex()==-1){
            cbox_bairro.setBorder(new LineBorder(new Color(255,0,0)));
            op3=1;
        }else{
            cbox_bairro.setBorder(new LineBorder(null));
            op3=2;       
        }
        
        if(ctFor_cnpj.getText().replaceAll("[^0-9]","").equals(verificaCNPJ)){
           op4=1;
        }else{
           op4=2; 
        }
        
        if(ct_nome.getText().equals(verificaNomeFor)){
           op5=1;
        }else{
           op5=2; 
        }
            
        if(op1==2 && op2==2 && op3==2){
                 if(modoNavegar.equals("Novo")){
                    if(op4==2){                    
                        if(op5==2){
                           int resposta=  JOptionPane.showConfirmDialog(null, "Salvar novo fornecedor?", "Novo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);    
                           if(resposta== JOptionPane.YES_NO_OPTION){
                            mod.setNome(ct_nome.getText());
                            mod.setEndereco(ct_endereco.getText());
                            mod.setCNPJ(ctFor_cnpj.getText().replaceAll("[^0-9]","")); // .replaceAll("[^0-9].-/","") SO NÚMEROS ( 1 Á 9 . -)
                            mod.setTelefone1(ctFor_telefone1.getText().replaceAll("[^0-9]",""));
                            mod.setTelefone2(ctFoR_telefone2.getText().replaceAll("[^0-9]",""));
                            mod.setNomeFatasia(ct_nomefantasia.getText());
                            mod.setBairro(""+cbox_bairro.getSelectedItem());
                            control.gravar(mod);
                            modoNavegar = "Inicializar";
                            manipularInterface();
                           }
                        }else{
                          JOptionPane.showMessageDialog(null,"Nome já cadastrado! \nTente outro nome.","Erro",JOptionPane.ERROR_MESSAGE);
                        }
                    }else{
                      JOptionPane.showMessageDialog(null,"CNPJ já cadastrado! \nTente outro CNPJ.","Erro",JOptionPane.ERROR_MESSAGE); 
                    }
                }

                if(modoNavegar.equals("Editar")){
                   int resposta=  JOptionPane.showConfirmDialog(null, "Deseja salvar as alterações?", "Alteração",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);    
                   if(resposta== JOptionPane.YES_NO_OPTION){
                    mod.setId(Integer.parseInt(ct_ID.getText()));
                    mod.setNome(ct_nome.getText());
                    mod.setEndereco(ct_endereco.getText());
                    mod.setCNPJ(ctFor_cnpj.getText().replaceAll("[^0-9]",""));
                    mod.setBairro(""+cbox_bairro.getSelectedItem());
                    mod.setTelefone1(ctFor_telefone1.getText().replaceAll("[^0-9]",""));
                    mod.setTelefone2(ctFoR_telefone2.getText().replaceAll("[^0-9]",""));
                    mod.setNomeFatasia(ct_nomefantasia.getText());
                    control.Alterar(mod);
                    modoNavegar = "Navegar";
                    manipularInterface();
                   }
                } 
        preecherTabela("select * from fornecedores");
        }else{
         JOptionPane.showMessageDialog(null,"Campo obrigatório não preenchido!","Erro",JOptionPane.ERROR_MESSAGE);     
        }
        
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        modoNavegar = "Editar";
        manipularInterface();
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
      int respost=JOptionPane.showConfirmDialog(null,"Deseja excluir o fornecedor?","Excluir",JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE);
      if(respost==JOptionPane.YES_NO_OPTION){
        mod.setId(Integer.parseInt(ct_ID.getText()));
        control.Excluir(mod);
        
        preecherTabela("select * from fornecedores");
        modoNavegar = "Inicializar";
        manipularInterface();
      }
      
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        modoNavegar = "Inicializar";
        manipularInterface();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void cbox_bairroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbox_bairroMouseClicked

    }//GEN-LAST:event_cbox_bairroMouseClicked

    private void cbox_bairroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbox_bairroMouseEntered

    }//GEN-LAST:event_cbox_bairroMouseEntered

    private void cbox_bairroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbox_bairroMouseExited

    }//GEN-LAST:event_cbox_bairroMouseExited

    private void cbox_bairroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbox_bairroMousePressed

    }//GEN-LAST:event_cbox_bairroMousePressed

    private void cbox_bairroMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbox_bairroMouseReleased

    }//GEN-LAST:event_cbox_bairroMouseReleased

    private void cbox_bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_bairroActionPerformed


    }//GEN-LAST:event_cbox_bairroActionPerformed

    private void tbl_cadastroFornMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_cadastroFornMouseClicked


    }//GEN-LAST:event_tbl_cadastroFornMouseClicked

    private void ct_pesquisaForMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ct_pesquisaForMouseClicked
      
        
    }//GEN-LAST:event_ct_pesquisaForMouseClicked

    private void ct_pesquisaForActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct_pesquisaForActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct_pesquisaForActionPerformed

    private void ct_pesquisaForKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_pesquisaForKeyReleased
        conecBanco.conexaoBanco();
        preecherTabela("select * from fornecedores where nome_fornecedor like '%"+ct_pesquisaFor.getText()+"%'");
        conecBanco.desconectar();
    }//GEN-LAST:event_ct_pesquisaForKeyReleased

    private void tbl_cadastroFornMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_cadastroFornMousePressed
        modoNavegar = "Navegar";
        manipularInterface();

        String  codigo_forn = ""+ tbl_cadastroForn.getValueAt(tbl_cadastroForn.getSelectedRow(), 0);
        conecBanco.conexaoBanco();
        try {
            conecBanco.executaSQL("select * from fornecedores where id_fornecedor='"+codigo_forn+"'");
            conecBanco.rs.first();
            
            ct_ID.setText(String.valueOf(conecBanco.rs.getInt("id_fornecedor")));
            ct_nome.setText(conecBanco.rs.getString("nome_fornecedor"));
            ct_endereco.setText(conecBanco.rs.getString("endereco"));
            ctFor_cnpj.setText(conecBanco.rs.getString("cnpj_fornecedor"));
            ctFor_telefone1.setText(conecBanco.rs.getString("telefone_1"));
            ctFoR_telefone2.setText(conecBanco.rs.getString("telefone_2"));
            ct_nomefantasia.setText(conecBanco.rs.getString("nome_fantasia"));
            conecBanco.executaSQL("select * from bairro where id_bairro='"+conecBanco.rs.getInt("id_bairro")+"'");
            conecBanco.rs.first();
            cbox_bairro.setSelectedItem(conecBanco.rs.getString("nome_bairro"));

        } catch (SQLException ex) {

        }
        conecBanco.desconectar();
    }//GEN-LAST:event_tbl_cadastroFornMousePressed

    private void ct_enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct_enderecoActionPerformed

    private void ct_nomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_nomeKeyReleased
      if(ct_nome.getText().length()>=50){
        ct_nome.setText(ct_nome.getText().substring(0,50));
     }else{
     } 
    }//GEN-LAST:event_ct_nomeKeyReleased

    private void ct_nomefantasiaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_nomefantasiaKeyReleased
     if(ct_nomefantasia.getText().length()>=28){
        ct_nomefantasia.setText(ct_nomefantasia.getText().substring(0,28));
     }else{
     } 
    }//GEN-LAST:event_ct_nomefantasiaKeyReleased

    private void ct_enderecoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_enderecoKeyReleased
     if(ct_endereco.getText().length()>=90){
        ct_endereco.setText(ct_endereco.getText().substring(0,90));
     }else{
     } 
    }//GEN-LAST:event_ct_enderecoKeyReleased

    private void btn_addNovoBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addNovoBairroActionPerformed
      opBairro=1;
        FrmAddBairro dialog = new FrmAddBairro(new javax.swing.JFrame(), true);
       dialog.setVisible(true);
    }//GEN-LAST:event_btn_addNovoBairroActionPerformed

    private void jPanel107MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel107MouseEntered
       if(opBairro==1){
        preencherCombobox();
        cbox_bairro.setSelectedItem(null);
        opBairro=2;
        }else{ 
        }
    }//GEN-LAST:event_jPanel107MouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addNovoBairro;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JComboBox<String> cbox_bairro;
    private javax.swing.JFormattedTextField ctFoR_telefone2;
    private javax.swing.JFormattedTextField ctFor_cnpj;
    private javax.swing.JFormattedTextField ctFor_telefone1;
    private javax.swing.JTextField ct_ID;
    private javax.swing.JTextField ct_endereco;
    private javax.swing.JTextField ct_nome;
    private javax.swing.JFormattedTextField ct_nomefantasia;
    private javax.swing.JTextField ct_pesquisaFor;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel103;
    private javax.swing.JPanel jPanel104;
    private javax.swing.JPanel jPanel105;
    private javax.swing.JPanel jPanel106;
    private javax.swing.JPanel jPanel107;
    private javax.swing.JPanel jPanel108;
    private javax.swing.JPanel jPanel109;
    private javax.swing.JPanel jPanel110;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_cadastroForn;
    // End of variables declaration//GEN-END:variables
}
