/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConectaBanco;
import Controle.ModeloTabela;
import com.lowagie.text.Font;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author NOTBOOK DE MAYCON
 */
public class FrmGrupoProduto extends javax.swing.JInternalFrame {
    ConectaBanco conecBan = new ConectaBanco();
    String modoNavegar;
    
    public FrmGrupoProduto() {
        initComponents();
        Locale.setDefault(new Locale("pt","BR"));
          UIManager.put("OptionPane.messageFont", new FontUIResource( "Arial", Font.NORMAL, 17));
             UIManager.put("OptionPane.yesButtonText", "Confirma");
              UIManager.put("OptionPane.noButtonText", "Cancelar");
     
        preecherTabela("select * from grupo_produto order by nome_grupo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btn_novo = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        ct_pesquisaMarca = new javax.swing.JTextField();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel103 = new javax.swing.JPanel();
        ct_cod = new javax.swing.JTextField();
        jPanel101 = new javax.swing.JPanel();
        ct_nomeGrupo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_grupo = new javax.swing.JTable();

        setClosable(true);
        setTitle("FORMULÁRIOD DE CADASTRO DE GRUPO");

        jDesktopPane1.setBackground(new java.awt.Color(0, 51, 255));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        jPanel6.setForeground(new java.awt.Color(102, 102, 102));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        btn_novo.setBackground(new java.awt.Color(255, 255, 255));
        btn_novo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/NOVO.png"))); // NOI18N
        btn_novo.setToolTipText("NOVO");
        btn_novo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_salvar.setBackground(new java.awt.Color(255, 255, 255));
        btn_salvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        btn_salvar.setToolTipText("SALVAR");
        btn_salvar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_salvar.setEnabled(false);
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_editar.setBackground(new java.awt.Color(255, 255, 255));
        btn_editar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EDITAR.png"))); // NOI18N
        btn_editar.setToolTipText("EDITAR");
        btn_editar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_editar.setEnabled(false);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_excluir.setBackground(new java.awt.Color(255, 255, 255));
        btn_excluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir.png"))); // NOI18N
        btn_excluir.setToolTipText("EXCLUIR");
        btn_excluir.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_excluir.setEnabled(false);
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        btn_cancelar.setToolTipText("CANCELAR");
        btn_cancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_cancelar.setEnabled(false);
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_novo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        ct_pesquisaMarca.setBackground(new java.awt.Color(0, 238, 255));
        ct_pesquisaMarca.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        ct_pesquisaMarca.setText("Pesquisar grupo");
        ct_pesquisaMarca.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));
        ct_pesquisaMarca.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_pesquisaMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ct_pesquisaMarcaMouseClicked(evt);
            }
        });
        ct_pesquisaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct_pesquisaMarcaActionPerformed(evt);
            }
        });
        ct_pesquisaMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_pesquisaMarcaKeyReleased(evt);
            }
        });

        jDesktopPane2.setBackground(new java.awt.Color(102, 0, 255));
        jDesktopPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jPanel103.setBackground(new java.awt.Color(197, 196, 195));
        jPanel103.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Código", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel103.setOpaque(false);

        ct_cod.setEditable(false);
        ct_cod.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        ct_cod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ct_cod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_cod.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        ct_cod.setEnabled(false);
        ct_cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct_codActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel103Layout = new javax.swing.GroupLayout(jPanel103);
        jPanel103.setLayout(jPanel103Layout);
        jPanel103Layout.setHorizontalGroup(
            jPanel103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_cod, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
        );
        jPanel103Layout.setVerticalGroup(
            jPanel103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel103Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ct_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel101.setBackground(new java.awt.Color(197, 196, 195));
        jPanel101.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nome do Grupo", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel101.setOpaque(false);

        ct_nomeGrupo.setBackground(new java.awt.Color(255, 255, 102));
        ct_nomeGrupo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        ct_nomeGrupo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_nomeGrupo.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_nomeGrupo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_nomeGrupo.setEnabled(false);
        ct_nomeGrupo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_nomeGrupoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel101Layout = new javax.swing.GroupLayout(jPanel101);
        jPanel101.setLayout(jPanel101Layout);
        jPanel101Layout.setHorizontalGroup(
            jPanel101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_nomeGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        );
        jPanel101Layout.setVerticalGroup(
            jPanel101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel101Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ct_nomeGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jDesktopPane2.setLayer(jPanel103, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel101, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "Lista de Grupo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 17))); // NOI18N
        jPanel1.setOpaque(false);

        tbl_grupo.setBackground(new java.awt.Color(248, 246, 244));
        tbl_grupo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbl_grupo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        tbl_grupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_grupo.setIntercellSpacing(new java.awt.Dimension(0, 4));
        tbl_grupo.setOpaque(false);
        tbl_grupo.setSelectionBackground(new java.awt.Color(255, 255, 102));
        tbl_grupo.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tbl_grupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_grupoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_grupoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_grupo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jDesktopPane1.setLayer(jPanel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ct_pesquisaMarca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jDesktopPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ct_pesquisaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(ct_pesquisaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        setSize(new java.awt.Dimension(1068, 572));
    }// </editor-fold>//GEN-END:initComponents

                public void manipularInterface(){ //MANIPULA A NAVEGAÇÃO 
        switch (modoNavegar){
            
             case "Inicializar":
                ct_nomeGrupo.setText("");
                ct_cod.setText("");
                ct_nomeGrupo.setEnabled(false);
                btn_novo.setEnabled(true);;
                btn_salvar.setEnabled(false);
                btn_editar.setEnabled(false);
                btn_excluir.setEnabled(false);
                btn_cancelar.setEnabled(false);              
                ct_nomeGrupo.setBackground(new Color(255,255,102));
                 break;
                 
             case "Navegar":
                ct_nomeGrupo.setText("");
                ct_cod.setText("");
                ct_nomeGrupo.setEnabled(false);
                btn_novo.setEnabled(true);;
                btn_salvar.setEnabled(false);
                btn_editar.setEnabled(true);
                btn_excluir.setEnabled(true);
                btn_cancelar.setEnabled(true);  
                ct_nomeGrupo.setBackground(new Color(255,255,102));
                 break;
                 
             case "Novo":
                ct_nomeGrupo.setText("");
                ct_cod.setText("");
                ct_nomeGrupo.setEnabled(true);
                btn_novo.setEnabled(false);;
                btn_salvar.setEnabled(true);
                btn_editar.setEnabled(false);
                btn_excluir.setEnabled(false);
                btn_cancelar.setEnabled(true);  
                ct_nomeGrupo.setBackground(new Color(255,255,102));
                
                 break;
                 
             case "Editar":
                ct_nomeGrupo.setEnabled(true);               
                btn_novo.setEnabled(false);;
                btn_salvar.setEnabled(true);
                btn_editar.setEnabled(false);
                btn_excluir.setEnabled(false);
                btn_cancelar.setEnabled(true);  
                ct_nomeGrupo.setBackground(new Color(255,255,102));
                
                 break;    
                 
            default:
                break;
          }
   } //METODO DE DE NAVEGAÇÃO NA INTERFACE
                
      public void preecherTabela(String SQL){ // METODO PARA PREENCHER TABELA NA INTERFACE
        ArrayList dados = new ArrayList();
        String [] Colunas  = new String []{"Código", "Nome do Grupo"};
        conecBan.conexaoBanco();
        conecBan.executaSQL(SQL);
      try {
          conecBan.rs.first();
          do {
              dados.add(new Object[]{conecBan.rs.getInt("id_grupo"),conecBan.rs.getString("nome_grupo")});
          }while (conecBan.rs.next());
          
      } catch (SQLException ex) {
//         JOptionPane.showMessageDialog(rootPane, "Erro ao Preencher o ArrayList! \n"+ ex.getMessage());
      }
      
       ModeloTabela modelo = new ModeloTabela(dados,Colunas);
       
        tbl_grupo.setModel(modelo);
        DefaultTableCellRenderer headerRenderer2 = new DefaultTableCellRenderer(); 
        headerRenderer2.setOpaque(true); 
        headerRenderer2.setBackground(new Color(0,0,51));
        headerRenderer2.setFont(new java.awt.Font("Arial Black", Font.BOLD, 23));
        headerRenderer2.setForeground(new Color(255,255,255));
        for (int i = 0; i < tbl_grupo.getModel().getColumnCount(); 
         i++) { tbl_grupo.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer2); }

            tbl_grupo.setRowHeight(40); //  TAMANHO DA JANELA PRA CADA ITEM
            
        tbl_grupo.getColumnModel().getColumn(0).setPreferredWidth(130);
        tbl_grupo.getColumnModel().getColumn(0).setResizable(false);
        tbl_grupo.getColumnModel().getColumn(1).setPreferredWidth(302);
        tbl_grupo.getColumnModel().getColumn(1).setResizable(false);
        tbl_grupo.getTableHeader().setReorderingAllowed(false);
//        tbl_marca.setAutoResizeMode(tbl_marca.AUTO_RESIZE_OFF);
        tbl_grupo.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        conecBan.desconectar();
    }//  FINAL METODO PARA IMPRIMIR TABELA NA INTERFACE                  
                
    private void ct_codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct_codActionPerformed

    private void tbl_grupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_grupoMouseClicked

    }//GEN-LAST:event_tbl_grupoMouseClicked

    private void ct_pesquisaMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ct_pesquisaMarcaMouseClicked
      
        
    }//GEN-LAST:event_ct_pesquisaMarcaMouseClicked

    private void ct_pesquisaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct_pesquisaMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct_pesquisaMarcaActionPerformed

    private void ct_pesquisaMarcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_pesquisaMarcaKeyReleased
        conecBan.conexaoBanco();
        preecherTabela("select * from grupo_produto where nome_grupo like '%" + ct_pesquisaMarca.getText() +"%'");
        conecBan.desconectar();
    }//GEN-LAST:event_ct_pesquisaMarcaKeyReleased

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        modoNavegar = "Novo";
        manipularInterface();
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
         int op1, op2, op3;
         String verificGrupo="";
         
        conecBan.conexaoBanco();
        try {
            conecBan.executaSQL("select * from grupo_produto where nome_grupo='"+ct_nomeGrupo.getText()+"'");
            conecBan.rs.first();
            verificGrupo= conecBan.rs.getString("nome_grupo");
        } catch (SQLException ex) {
        }
        conecBan.desconectar();
        
    
        
        if(ct_nomeGrupo.getText().equals("")){
           ct_nomeGrupo.setBackground(new Color(246,170,170));
            op1=1;
        }else{
            ct_nomeGrupo.setBackground(new Color(255,255,102));
            op1=2;
        }
        
        if(ct_nomeGrupo.getText().equals(verificGrupo)){
            op2=1;
        }else{
            op2=2;
        }
        
        if(op1==2){
            conecBan.conexaoBanco();
            if(modoNavegar.equals("Novo")){
                if(op2==1){
                 JOptionPane.showMessageDialog(null,"Nome do grupo já cadastrado! \nTente outro nome.","Erro",JOptionPane.ERROR_MESSAGE);   
                }else{
                    int resposta=  JOptionPane.showConfirmDialog(null, "Salvar novo grupo?", "Novo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);    
                    if(resposta== JOptionPane.YES_NO_OPTION){
                        try {
                            PreparedStatement pst = conecBan.conn.prepareStatement("insert into grupo_produto(nome_grupo)values(?)");
                            pst.setString(1, ct_nomeGrupo.getText());
                            pst.execute();
                            JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso!");

                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(rootPane, "Erro ao adicionar grupo"+ ex);
                        }
                     modoNavegar="Inicializar";
                     manipularInterface();
                    }
                }
            }

            if(modoNavegar.equals("Editar")){
                int resposta=  JOptionPane.showConfirmDialog(null, "Deseja salvar as alterações?", "Alteração",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);    
                if(resposta== JOptionPane.YES_NO_OPTION){  
                    try {
                        PreparedStatement pst = conecBan.conn.prepareStatement("update grupo_produto set nome_grupo=? where id_grupo=?");
                        pst.setString(1, ct_nomeGrupo.getText());
                        pst.setInt(2,Integer.parseInt(ct_cod.getText()));
                        pst.execute();
                        JOptionPane.showMessageDialog(rootPane, "Alterado com sucesso!");
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(rootPane, "Erro ao editar grupo"+ ex);
                    }
                    modoNavegar="Navegar";
                    manipularInterface();
                }
            }
            
            preecherTabela("select * from grupo_produto order by nome_grupo");
            conecBan.desconectar();
        }else{
         JOptionPane.showMessageDialog(null,"Campo obrigatório não preenchido!","Erro",JOptionPane.ERROR_MESSAGE);    
        }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        modoNavegar= "Editar";
        manipularInterface();
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        
       int respost=JOptionPane.showConfirmDialog(null,"Deseja excluir grupo?","Excluir",JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE);
       if(respost==JOptionPane.YES_NO_OPTION){
        conecBan.conexaoBanco();
        try {
            PreparedStatement pst = conecBan.conn.prepareStatement("delete from grupo_produto where id_grupo=?");
            pst.setInt(1,Integer.parseInt(ct_cod.getText()));
            pst.execute();
            JOptionPane.showMessageDialog(rootPane, "Grupo excluido!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "erro ao excluir grupo"+ ex);
        }

        preecherTabela("select * from grupo_produto order by nome_grupo");
        conecBan.desconectar();
        modoNavegar = "Inicializar";
        manipularInterface();
      }
       
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        modoNavegar = "Inicializar";
        manipularInterface();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void ct_nomeGrupoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_nomeGrupoKeyReleased
      if(ct_nomeGrupo.getText().length()>=25){
         ct_nomeGrupo.setText(ct_nomeGrupo.getText().substring(0,25));
     }else{
     }   
    }//GEN-LAST:event_ct_nomeGrupoKeyReleased

    private void tbl_grupoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_grupoMousePressed
        modoNavegar = "Navegar";
        manipularInterface();
        
        String idGrupoClick = ""+ tbl_grupo.getValueAt(tbl_grupo.getSelectedRow(), 0);
        conecBan.conexaoBanco();
        try {
            conecBan.executaSQL("select * from grupo_produto where id_grupo='"+idGrupoClick+"'");
            conecBan.rs.first();
            ct_cod.setText(""+conecBan.rs.getInt("id_grupo"));
            ct_nomeGrupo.setText(conecBan.rs.getString("nome_grupo"));
        } catch (SQLException ex) {
        }
        conecBan.desconectar();

    }//GEN-LAST:event_tbl_grupoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JTextField ct_cod;
    private javax.swing.JTextField ct_nomeGrupo;
    private javax.swing.JTextField ct_pesquisaMarca;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel101;
    private javax.swing.JPanel jPanel103;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_grupo;
    // End of variables declaration//GEN-END:variables
}
