/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConectaBanco;
import Controle.ModeloTabela;
import com.lowagie.text.Font;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author NOTBOOK DE MAYCON
 */
public class FrmMarca extends javax.swing.JInternalFrame {
    ConectaBanco conecBan = new ConectaBanco();
  String modoNavegar;
    public FrmMarca() {
        initComponents();
         Locale.setDefault(new Locale("pt","BR"));
          UIManager.put("OptionPane.messageFont", new FontUIResource( "Arial", Font.NORMAL, 17));
            UIManager.put("OptionPane.yesButtonText", "Confirma");
             UIManager.put("OptionPane.noButtonText", "Cancelar");
             
        preecherTabela("select * from marca order by nome_marca");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        ct_pesquisaMarca = new javax.swing.JTextField();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel103 = new javax.swing.JPanel();
        ct_cod = new javax.swing.JTextField();
        jPanel104 = new javax.swing.JPanel();
        ct_nomeMarca = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btn_novo = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_marca = new javax.swing.JTable();

        setBackground(new java.awt.Color(197, 196, 195));
        setClosable(true);
        setTitle("FORMULÁRIO DE CADASTRO DE MARCA");

        jDesktopPane1.setBackground(new java.awt.Color(0, 51, 255));

        ct_pesquisaMarca.setBackground(new java.awt.Color(0, 238, 255));
        ct_pesquisaMarca.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ct_pesquisaMarca.setText("Pesquisar estado");
        ct_pesquisaMarca.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));
        ct_pesquisaMarca.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_pesquisaMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ct_pesquisaMarcaMouseClicked(evt);
            }
        });
        ct_pesquisaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct_pesquisaMarcaActionPerformed(evt);
            }
        });
        ct_pesquisaMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_pesquisaMarcaKeyReleased(evt);
            }
        });

        jDesktopPane2.setBackground(new java.awt.Color(102, 0, 255));
        jDesktopPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jPanel103.setBackground(new java.awt.Color(197, 196, 195));
        jPanel103.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Código", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel103.setOpaque(false);

        ct_cod.setEditable(false);
        ct_cod.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        ct_cod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ct_cod.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_cod.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        ct_cod.setEnabled(false);
        ct_cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct_codActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel103Layout = new javax.swing.GroupLayout(jPanel103);
        jPanel103.setLayout(jPanel103Layout);
        jPanel103Layout.setHorizontalGroup(
            jPanel103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_cod, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
        );
        jPanel103Layout.setVerticalGroup(
            jPanel103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel103Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ct_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel104.setBackground(new java.awt.Color(197, 196, 195));
        jPanel104.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nome da Marca", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel104.setOpaque(false);

        ct_nomeMarca.setBackground(new java.awt.Color(255, 255, 102));
        ct_nomeMarca.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        ct_nomeMarca.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_nomeMarca.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_nomeMarca.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ct_nomeMarca.setEnabled(false);
        ct_nomeMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_nomeMarcaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel104Layout = new javax.swing.GroupLayout(jPanel104);
        jPanel104.setLayout(jPanel104Layout);
        jPanel104Layout.setHorizontalGroup(
            jPanel104Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_nomeMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );
        jPanel104Layout.setVerticalGroup(
            jPanel104Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel104Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ct_nomeMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jDesktopPane2.setLayer(jPanel103, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel104, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel104, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel104, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        jPanel6.setForeground(new java.awt.Color(102, 102, 102));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        btn_novo.setBackground(new java.awt.Color(255, 255, 255));
        btn_novo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/NOVO.png"))); // NOI18N
        btn_novo.setToolTipText("NOVO");
        btn_novo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_salvar.setBackground(new java.awt.Color(255, 255, 255));
        btn_salvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        btn_salvar.setToolTipText("SALVAR");
        btn_salvar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_salvar.setEnabled(false);
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_editar.setBackground(new java.awt.Color(255, 255, 255));
        btn_editar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EDITAR.png"))); // NOI18N
        btn_editar.setToolTipText("EDITAR");
        btn_editar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_editar.setEnabled(false);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_excluir.setBackground(new java.awt.Color(255, 255, 255));
        btn_excluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir.png"))); // NOI18N
        btn_excluir.setToolTipText("EXCLUIR");
        btn_excluir.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_excluir.setEnabled(false);
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        btn_cancelar.setToolTipText("CANCELAR");
        btn_cancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_cancelar.setEnabled(false);
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_novo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "Lista de Marca", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 17), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);

        tbl_marca.setBackground(new java.awt.Color(248, 246, 244));
        tbl_marca.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbl_marca.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        tbl_marca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_marca.setIntercellSpacing(new java.awt.Dimension(0, 4));
        tbl_marca.setOpaque(false);
        tbl_marca.setSelectionBackground(new java.awt.Color(255, 255, 102));
        tbl_marca.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tbl_marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_marcaMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_marcaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_marca);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDesktopPane1.setLayer(ct_pesquisaMarca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jDesktopPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ct_pesquisaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ct_pesquisaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        setSize(new java.awt.Dimension(1068, 572));
    }// </editor-fold>//GEN-END:initComponents

    
            public void manipularInterface(){ //MANIPULA A NAVEGAÇÃO 
        switch (modoNavegar){
            
             case "Inicializar":
                ct_nomeMarca.setText("");
                ct_cod.setText("");
                 
                ct_nomeMarca.setEnabled(false);
                btn_novo.setEnabled(true);;
                btn_salvar.setEnabled(false);
                btn_editar.setEnabled(false);
                btn_excluir.setEnabled(false);
                btn_cancelar.setEnabled(false); 
                ct_nomeMarca.setBackground(new Color(255,255,102));
                
                 break;
                 
             case "Navegar":
                ct_nomeMarca.setText("");
                ct_cod.setText("");
                ct_nomeMarca.setEnabled(false);
                btn_novo.setEnabled(true);;
                btn_salvar.setEnabled(false);
                btn_editar.setEnabled(true);
                btn_excluir.setEnabled(true);
                btn_cancelar.setEnabled(true);  
                ct_nomeMarca.setBackground(new Color(255,255,102));
                
                 break;
                 
             case "Novo":
                ct_nomeMarca.setText("");
                ct_cod.setText("");
                ct_nomeMarca.setEnabled(true);
                btn_novo.setEnabled(false);;
                btn_salvar.setEnabled(true);
                btn_editar.setEnabled(false);
                btn_excluir.setEnabled(false);
                btn_cancelar.setEnabled(true);   
                ct_nomeMarca.setBackground(new Color(255,255,102));
                
                 break;
                 
             case "Editar":
                ct_nomeMarca.setEnabled(true);               
                btn_novo.setEnabled(false);;
                btn_salvar.setEnabled(true);
                btn_editar.setEnabled(false);
                btn_excluir.setEnabled(false);
                btn_cancelar.setEnabled(true);   
                ct_nomeMarca.setBackground(new Color(255,255,102));
                
                 break;    
                 
            default:
                break;
          }
   } //METODO DE DE NAVEGAÇÃO NA INTERFACE
            
            
     public void preecherTabela(String SQL){ // METODO PARA PREENCHER TABELA NA INTERFACE
        ArrayList dados = new ArrayList();
        String [] Colunas  = new String []{"Código", "Nome da Marca"};
        conecBan.conexaoBanco();
        conecBan.executaSQL(SQL);
      try {
          conecBan.rs.first();
          do {
              dados.add(new Object[]{conecBan.rs.getInt("id_marca"),conecBan.rs.getString("nome_marca")});
          }while (conecBan.rs.next());
          
      } catch (SQLException ex) {
//         JOptionPane.showMessageDialog(rootPane, "Erro ao Preencher o ArrayList! \n"+ ex.getMessage());
      }
      
       ModeloTabela modelo = new ModeloTabela(dados,Colunas);
       
        tbl_marca.setModel(modelo);
        DefaultTableCellRenderer headerRenderer2 = new DefaultTableCellRenderer(); 
        headerRenderer2.setOpaque(true); 
        headerRenderer2.setBackground(new Color(0,0,51));
        headerRenderer2.setFont(new java.awt.Font("Arial Black", Font.BOLD, 23));
        headerRenderer2.setForeground(new Color(255,255,255));
        for (int i = 0; i < tbl_marca.getModel().getColumnCount(); 
         i++) { tbl_marca.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer2); }

            tbl_marca.setRowHeight(40); //  TAMANHO DA JANELA PRA CADA ITEM
            
        tbl_marca.getColumnModel().getColumn(0).setPreferredWidth(130);
        tbl_marca.getColumnModel().getColumn(0).setResizable(false);
        tbl_marca.getColumnModel().getColumn(1).setPreferredWidth(302);
        tbl_marca.getColumnModel().getColumn(1).setResizable(false);
        tbl_marca.getTableHeader().setReorderingAllowed(false);
//        tbl_marca.setAutoResizeMode(tbl_marca.AUTO_RESIZE_OFF);
        tbl_marca.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conecBan.desconectar();
     }//  FINAL METODO PARA IMPRIMIR TABELA NA INTERFACE          
            
    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
     modoNavegar = "Novo";
     manipularInterface();
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
          int op1, op2, op3;
         String verificMarca="";
         
        conecBan.conexaoBanco();
        try {
            conecBan.executaSQL("select * from marca where nome_marca='"+ct_nomeMarca.getText()+"'");
            conecBan.rs.first();
            verificMarca= conecBan.rs.getString("nome_marca");
        } catch (SQLException ex) {
        }
        conecBan.desconectar();
        
        if(ct_nomeMarca.getText().equals("")){
           ct_nomeMarca.setBackground(new Color(246,170,170));
            op1=1;
        }else{
            ct_nomeMarca.setBackground(new Color(255,255,102));
            op1=2;
        }
        
        if(ct_nomeMarca.getText().equals(verificMarca)){
            op2=1;
        }else{
            op2=2;
        }
        
       
       
       if(op1==2){
        conecBan.conexaoBanco();
        
        if(modoNavegar.equals("Novo")){
            if(op2==1){
             JOptionPane.showMessageDialog(null,"Nome da marca já cadastrado! \nTente outro nome.","Erro",JOptionPane.ERROR_MESSAGE);      
            }else{
                int resposta=  JOptionPane.showConfirmDialog(null, "Salvar nova marca?", "Novo",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);    
                if(resposta== JOptionPane.YES_NO_OPTION){  
                 try {
                     PreparedStatement pst = conecBan.conn.prepareStatement("insert into marca(nome_marca)values(?)");
                     pst.setString(1, ct_nomeMarca.getText());
                     pst.execute();
                     JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso!");  

                 } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(rootPane, "Erro ao adicinar marca"+ ex);   
                 }
                modoNavegar="Inicializar";
                manipularInterface();
                }
            }
        }

        if(modoNavegar.equals("Editar")){
             int resposta=  JOptionPane.showConfirmDialog(null, "Deseja salvar as alterações?", "Alteração",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);    
             if(resposta== JOptionPane.YES_NO_OPTION){  
                 try {
                   PreparedStatement pst = conecBan.conn.prepareStatement("update marca set nome_marca=? where id_marca=?");
                      pst.setString(1, ct_nomeMarca.getText());
                      pst.setInt(2,Integer.parseInt(ct_cod.getText()));
                      pst.execute();
                      JOptionPane.showMessageDialog(rootPane, "Alterado com sucesso!");  
                 } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Erro ao editar marca"+ ex);  
                 }
                 modoNavegar="Navegar";
                 manipularInterface();
             }
        }
        preecherTabela("select * from marca order by nome_marca");
        conecBan.desconectar();
       }else{
       JOptionPane.showMessageDialog(null,"Campo obrigatório não preenchido!","Erro",JOptionPane.ERROR_MESSAGE);      
       }
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
       modoNavegar= "Editar";
       manipularInterface();
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
      int respost=JOptionPane.showConfirmDialog(null,"Deseja excluir marca?","Excluir",JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE);
      if(respost==JOptionPane.YES_NO_OPTION){
        conecBan.conexaoBanco();
        try {
            PreparedStatement pst = conecBan.conn.prepareStatement("delete from marca where id_marca=?");
            pst.setInt(1,Integer.parseInt(ct_cod.getText()));
            pst.execute();
           JOptionPane.showMessageDialog(rootPane, "Marca excluida!");  
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(rootPane, "Erro ao excluir marca"+ ex); 
        }
       
       preecherTabela("select * from marca order by nome_marca");
       conecBan.desconectar();
        modoNavegar = "Inicializar";
        manipularInterface();
      }
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        modoNavegar = "Inicializar";
        manipularInterface();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void ct_codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct_codActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct_codActionPerformed

    private void tbl_marcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_marcaMouseClicked

        
    }//GEN-LAST:event_tbl_marcaMouseClicked

    private void ct_pesquisaMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ct_pesquisaMarcaMouseClicked
    
        
    }//GEN-LAST:event_ct_pesquisaMarcaMouseClicked

    private void ct_pesquisaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct_pesquisaMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct_pesquisaMarcaActionPerformed

    private void ct_pesquisaMarcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_pesquisaMarcaKeyReleased
        conecBan.conexaoBanco();
        preecherTabela("select * from marca where nome_marca like '%" + ct_pesquisaMarca.getText() +"%'");
        conecBan.desconectar();
    }//GEN-LAST:event_ct_pesquisaMarcaKeyReleased

    private void ct_nomeMarcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_nomeMarcaKeyReleased
     if(ct_nomeMarca.getText().length()>=25){
        ct_nomeMarca.setText(ct_nomeMarca.getText().substring(0,25));
     }else{
     }   
    }//GEN-LAST:event_ct_nomeMarcaKeyReleased

    private void tbl_marcaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_marcaMousePressed
          modoNavegar = "Navegar";
          manipularInterface();
             
        String idmarcaClick = ""+ tbl_marca.getValueAt(tbl_marca.getSelectedRow(), 0);
        conecBan.conexaoBanco();
        try {
            conecBan.executaSQL("select * from marca where id_marca='"+idmarcaClick+"'");
            conecBan.rs.first();
            ct_cod.setText(""+conecBan.rs.getInt("id_marca"));
            ct_nomeMarca.setText(conecBan.rs.getString("nome_marca"));
            
        } catch (SQLException ex) {
        }
        conecBan.desconectar();
    }//GEN-LAST:event_tbl_marcaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JTextField ct_cod;
    private javax.swing.JTextField ct_nomeMarca;
    private javax.swing.JTextField ct_pesquisaMarca;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel103;
    private javax.swing.JPanel jPanel104;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_marca;
    // End of variables declaration//GEN-END:variables
}
