/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConectaBanco;
import Controle.ControleTelefone;
import Controle.ModeloTabela;
import Modelo.ModeloTelefone;
import com.lowagie.text.Font;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author NOTBOOK DE MAYCON
 */
public class FrmTelefone extends javax.swing.JInternalFrame {
     String modoNavegar;
     ModeloTelefone mod = new ModeloTelefone();
     ControleTelefone connTelefone= new ControleTelefone();
     ConectaBanco conecBanco= new ConectaBanco();
     
    public FrmTelefone() {
        initComponents();
      conecBanco.conexaoBanco();
       preecherTabela("select * from telefone order by id_telefone");
       conecBanco.desconectar();
         try {
          MaskFormatter form    = new MaskFormatter("(##)9.####-####"); // elemento para criar formatato de mascara
          ctFor_numero1.setFormatterFactory(new DefaultFormatterFactory(form)); //atribui a mascara ao campo
        } catch (ParseException ex) {
           
        }
         try {
          MaskFormatter form    = new MaskFormatter("(##)9.####-####"); // elemento para criar formatato de mascara
          ctFor_numero2.setFormatterFactory(new DefaultFormatterFactory(form)); //atribui a mascara ao campo
        } catch (ParseException ex) {
            
        }
         conecBanco.desconectar();
         
         modoNavegar = "Inicializar";
         manipularInterface();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btn_novo = new javax.swing.JButton();
        btn_salvar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        ct_pesquisaTel1 = new javax.swing.JTextField();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel103 = new javax.swing.JPanel();
        ct_codigo = new javax.swing.JTextField();
        jPanel101 = new javax.swing.JPanel();
        ctFor_numero1 = new javax.swing.JFormattedTextField();
        jPanel102 = new javax.swing.JPanel();
        ctFor_numero2 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_telefone = new javax.swing.JTable();

        setClosable(true);
        setTitle("FORMULÁRIO DE CADASTRO DE TELEFONE");

        jDesktopPane1.setBackground(new java.awt.Color(0, 102, 255));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 4));
        jPanel4.setForeground(new java.awt.Color(102, 102, 102));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        btn_novo.setBackground(new java.awt.Color(255, 255, 255));
        btn_novo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_novo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/NOVO.png"))); // NOI18N
        btn_novo.setToolTipText("Novo");
        btn_novo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_salvar.setBackground(new java.awt.Color(255, 255, 255));
        btn_salvar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/salvar.png"))); // NOI18N
        btn_salvar.setToolTipText("Salvar");
        btn_salvar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_salvar.setEnabled(false);
        btn_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvarActionPerformed(evt);
            }
        });

        btn_editar.setBackground(new java.awt.Color(255, 255, 255));
        btn_editar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EDITAR.png"))); // NOI18N
        btn_editar.setToolTipText("Editar");
        btn_editar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_editar.setEnabled(false);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_excluir.setBackground(new java.awt.Color(255, 255, 255));
        btn_excluir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/excluir.png"))); // NOI18N
        btn_excluir.setToolTipText("Excluir");
        btn_excluir.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_excluir.setEnabled(false);
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_cancelar.setBackground(new java.awt.Color(255, 255, 255));
        btn_cancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancelar.png"))); // NOI18N
        btn_cancelar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        btn_cancelar.setEnabled(false);
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_novo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salvar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_excluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btn_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        ct_pesquisaTel1.setBackground(new java.awt.Color(0, 238, 255));
        ct_pesquisaTel1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        ct_pesquisaTel1.setText("Pesquisar telefone");
        ct_pesquisaTel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 3, true));
        ct_pesquisaTel1.setCaretColor(new java.awt.Color(255, 0, 0));
        ct_pesquisaTel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ct_pesquisaTel1MouseClicked(evt);
            }
        });
        ct_pesquisaTel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ct_pesquisaTel1ActionPerformed(evt);
            }
        });
        ct_pesquisaTel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_pesquisaTel1KeyReleased(evt);
            }
        });

        jDesktopPane2.setBackground(new java.awt.Color(102, 0, 204));
        jDesktopPane2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jPanel103.setBackground(new java.awt.Color(197, 196, 195));
        jPanel103.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Código", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel103.setOpaque(false);

        ct_codigo.setEditable(false);
        ct_codigo.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        ct_codigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ct_codigo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ct_codigo.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        ct_codigo.setEnabled(false);

        javax.swing.GroupLayout jPanel103Layout = new javax.swing.GroupLayout(jPanel103);
        jPanel103.setLayout(jPanel103Layout);
        jPanel103Layout.setHorizontalGroup(
            jPanel103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ct_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel103Layout.setVerticalGroup(
            jPanel103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel103Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ct_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel101.setBackground(new java.awt.Color(197, 196, 195));
        jPanel101.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Telefone I", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel101.setOpaque(false);

        ctFor_numero1.setBackground(new java.awt.Color(255, 255, 102));
        ctFor_numero1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ctFor_numero1.setCaretColor(new java.awt.Color(255, 0, 0));
        ctFor_numero1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ctFor_numero1.setEnabled(false);
        ctFor_numero1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        ctFor_numero1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ctFor_numero1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel101Layout = new javax.swing.GroupLayout(jPanel101);
        jPanel101.setLayout(jPanel101Layout);
        jPanel101Layout.setHorizontalGroup(
            jPanel101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ctFor_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel101Layout.setVerticalGroup(
            jPanel101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel101Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ctFor_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel102.setBackground(new java.awt.Color(197, 196, 195));
        jPanel102.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Telefone II", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 16), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel102.setOpaque(false);

        ctFor_numero2.setBackground(new java.awt.Color(255, 255, 102));
        ctFor_numero2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        ctFor_numero2.setCaretColor(new java.awt.Color(255, 0, 0));
        ctFor_numero2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        ctFor_numero2.setEnabled(false);
        ctFor_numero2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        ctFor_numero2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ctFor_numero2KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel102Layout = new javax.swing.GroupLayout(jPanel102);
        jPanel102.setLayout(jPanel102Layout);
        jPanel102Layout.setHorizontalGroup(
            jPanel102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ctFor_numero2)
        );
        jPanel102Layout.setVerticalGroup(
            jPanel102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ctFor_numero2)
        );

        jDesktopPane2.setLayer(jPanel103, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel101, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jPanel102, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel101, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel102, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true), "Lista de Contato", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 17))); // NOI18N
        jPanel1.setOpaque(false);

        tbl_telefone.setBackground(new java.awt.Color(248, 246, 244));
        tbl_telefone.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tbl_telefone.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        tbl_telefone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_telefone.setIntercellSpacing(new java.awt.Dimension(0, 4));
        tbl_telefone.setOpaque(false);
        tbl_telefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_telefoneMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_telefone);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        jDesktopPane1.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(ct_pesquisaTel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jDesktopPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ct_pesquisaTel1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(ct_pesquisaTel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        setSize(new java.awt.Dimension(1068, 572));
    }// </editor-fold>//GEN-END:initComponents

    public void manipularInterface(){ //MANIPULA A NAVEGAÇÃO 
        switch (modoNavegar){
            
            case "Inicializar":
                 ctFor_numero1.setText("");
                 ct_codigo.setText("");
                 ctFor_numero2.setText("");
                 ct_codigo.setEnabled(false);
                 ctFor_numero1.setEnabled(false);
                 ctFor_numero2.setEnabled(false);
                 btn_novo.setEnabled(true);;
                 btn_salvar.setEnabled(false);
                 btn_cancelar.setEnabled(false);
                 btn_editar.setEnabled(false);
                 btn_excluir.setEnabled(false);
//                 btn_sair.setEnabled(true);
                 
                 break;

            case "Navegar":
              // ct_nome.setText("");
             //  ct_codigo.setText("");
                 ct_codigo.setEnabled(false);
                 ctFor_numero1.setEnabled(false);
                 ctFor_numero2.setEnabled(false);
                 btn_novo.setEnabled(true);;
                 btn_salvar.setEnabled(false);
                 btn_cancelar.setEnabled(false);
                 btn_editar.setEnabled(true);
                 btn_excluir.setEnabled(true);
//                 btn_sair.setEnabled(true);
                 
                 break;
                 
            case "Novo":
                 ctFor_numero1.setText("");
                 ct_codigo.setText("");
                 ctFor_numero2.setText("");
                 ct_codigo.setEnabled(false);
                 ctFor_numero1.setEnabled(true);
                 ctFor_numero2.setEnabled(true);
                 btn_novo.setEnabled(false);;
                 btn_salvar.setEnabled(true);
                 btn_cancelar.setEnabled(true);
                 btn_editar.setEnabled(false);
                 btn_excluir.setEnabled(false);
//                 btn_sair.setEnabled(true);
                 
                 break;
     
            case "Editar":
              // ct_nome.setText("");
             //  ct_codigo.setText("");
                 ct_codigo.setEnabled(false);
                 ctFor_numero1.setEnabled(true);
                 ctFor_numero2.setEnabled(true);
                 btn_novo.setEnabled(false);;
                 btn_salvar.setEnabled(true);
                 btn_cancelar.setEnabled(true);
                 btn_editar.setEnabled(false);
                 btn_excluir.setEnabled(true);
//                 btn_sair.setEnabled(true);
                 
                 break;
                 
            default:
                break;
          }
    }

    public void preecherTabela(String SQL){ // METODO PARA PREENCHER TABELA NA INTERFACE
        ArrayList dados = new ArrayList();
        String [] Colunas  = new String []{"ID", "Número Tel.","Número Whats."};
        
        conecBanco.executaSQL(SQL);
      try {
          conecBanco.rs.first();
          do {
              dados.add(new Object[]{conecBanco.rs.getInt("id_telefone"),conecBanco.rs.getString("numero_tel"),conecBanco.rs.getString("numero_whats")});
          }while (conecBanco.rs.next());
          
      } catch (SQLException ex) {
//         JOptionPane.showMessageDialog(rootPane, "Erro ao Preencher o ArrayList! \n"+ ex.getMessage());
      }
      
       ModeloTabela modelo = new ModeloTabela(dados,Colunas);
       
        tbl_telefone.setModel(modelo);
        DefaultTableCellRenderer headerRenderer2 = new DefaultTableCellRenderer(); 
        headerRenderer2.setOpaque(true); 
        headerRenderer2.setBackground(new Color(0,0,51));
        headerRenderer2.setFont(new java.awt.Font("Arial Black", Font.BOLD, 23));
        headerRenderer2.setForeground(new Color(255,255,255));
        for (int i = 0; i < tbl_telefone.getModel().getColumnCount(); 
         i++) { tbl_telefone.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer2); }

            tbl_telefone.setRowHeight(40); //  TAMANHO DA JANELA PRA CADA ITEM
            
        tbl_telefone.getColumnModel().getColumn(0).setPreferredWidth(45);
        tbl_telefone.getColumnModel().getColumn(0).setResizable(false);
        tbl_telefone.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbl_telefone.getColumnModel().getColumn(1).setResizable(false);
        tbl_telefone.getColumnModel().getColumn(2).setPreferredWidth(150);
        tbl_telefone.getColumnModel().getColumn(2).setResizable(false);
        tbl_telefone.getTableHeader().setReorderingAllowed(false);
//        tbl_telefone.setAutoResizeMode( tbl_telefone.AUTO_RESIZE_OFF);
        tbl_telefone.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
    }  
    
    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        modoNavegar = "Novo";
        manipularInterface();
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvarActionPerformed
        if(modoNavegar.equals("Novo")){
            mod.setTel(ctFor_numero1.getText());
            mod.setWhats(ctFor_numero2.getText());
            connTelefone.Gravar(mod);
            modoNavegar = "Inicializar";
            manipularInterface();
        }else{

        }if(modoNavegar.equals("Editar")){
            mod.setCod(Integer.parseInt(ct_codigo.getText()));
            mod.setTel(ctFor_numero1.getText());
            mod.setWhats(ctFor_numero2.getText());
            connTelefone.Editar(mod);
            modoNavegar = "Navegar";
            manipularInterface();
        }
        conecBanco.conexaoBanco();
        preecherTabela("select * from telefone order by id_telefone");
        conecBanco.desconectar();
    }//GEN-LAST:event_btn_salvarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        modoNavegar = "Editar";
        manipularInterface();
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        mod.setCod(Integer.parseInt(ct_codigo.getText()));
        connTelefone.Excluir(mod);
        conecBanco.conexaoBanco();
        preecherTabela("select * from telefone order by id_telefone");
        conecBanco.desconectar();
        modoNavegar = "Navegar";
        manipularInterface();

    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        modoNavegar = "Inicializar";
        manipularInterface();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    private void ct_pesquisaTel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ct_pesquisaTel1MouseClicked
        ct_pesquisaTel1.selectAll();
    }//GEN-LAST:event_ct_pesquisaTel1MouseClicked

    private void ct_pesquisaTel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ct_pesquisaTel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ct_pesquisaTel1ActionPerformed

    private void ct_pesquisaTel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_pesquisaTel1KeyReleased
        conecBanco.conexaoBanco();
        preecherTabela("select * from telefone where numero_tel like '%"+ct_pesquisaTel1.getText() +"%' or numero_whats like '%"+ct_pesquisaTel1.getText()+"%'");
        conecBanco.desconectar();
    }//GEN-LAST:event_ct_pesquisaTel1KeyReleased

    private void tbl_telefoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_telefoneMouseClicked
        modoNavegar = "Navegar";
        manipularInterface();
        String numero_tel =""+ tbl_telefone.getValueAt(tbl_telefone.getSelectedRow(), 1);
        conecBanco.conexaoBanco();
        try {
            conecBanco.executaSQL("select * from telefone where numero_tel='"+numero_tel+"'");
            conecBanco.rs.first();
            ct_codigo.setText(String.valueOf(conecBanco.rs.getInt("id_telefone")));
            ctFor_numero1.setText(conecBanco.rs.getString("numero_tel"));
            ctFor_numero2.setText(conecBanco.rs.getString("numero_whats"));

            // JOptionPane.showMessageDialog(rootPane, nome_tabela);
        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(rootPane, "Erro ao Selecionar os Dados!"+ex);
        }
        conecBanco.desconectar();

    }//GEN-LAST:event_tbl_telefoneMouseClicked

    private void ctFor_numero1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ctFor_numero1KeyReleased

    }//GEN-LAST:event_ctFor_numero1KeyReleased

    private void ctFor_numero2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ctFor_numero2KeyReleased
 
    }//GEN-LAST:event_ctFor_numero2KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_salvar;
    private javax.swing.JFormattedTextField ctFor_numero1;
    private javax.swing.JFormattedTextField ctFor_numero2;
    private javax.swing.JTextField ct_codigo;
    private javax.swing.JTextField ct_pesquisaTel1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel101;
    private javax.swing.JPanel jPanel102;
    private javax.swing.JPanel jPanel103;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_telefone;
    // End of variables declaration//GEN-END:variables
}
