/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ConectaBanco;
import Controle.ModeloTabela;
import com.lowagie.text.Font;
import java.awt.Color;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author NOTBOOK DE MAYCON
 */
public class ListaProdutos extends javax.swing.JInternalFrame {
    ConectaBanco conecBanc = new ConectaBanco();
    ConectaBanco conecPesq= new ConectaBanco();
   int idMarcaPesq;
   int click;
   int opcPesquisa;
  
   
         NumberFormat numberFormat = NumberFormat.getCurrencyInstance(new Locale("pt", "BR"));
         NumberFormat numberFormat2 = NumberFormat.getNumberInstance(new Locale("en", "US"));
         
    public ListaProdutos() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ct_pesquisar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cbox_marca = new javax.swing.JComboBox<>();
        btn_marca = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        cbox_grupo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btn_grupo = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_produtos = new javax.swing.JTable();

        setClosable(true);
        setTitle("LISTA DE PRODUTOS");

        jPanel2.setBackground(new java.awt.Color(197, 196, 195));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel2MouseMoved(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(197, 196, 195));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ct_pesquisar.setBackground(new java.awt.Color(0, 238, 255));
        ct_pesquisar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ct_pesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ct_pesquisarKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Descrição ");

        jPanel3.setBackground(new java.awt.Color(197, 196, 195));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbox_marca.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        cbox_marca.setMaximumRowCount(7);
        cbox_marca.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbox_marca.setEnabled(false);
        cbox_marca.setLightWeightPopupEnabled(false);
        cbox_marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbox_marcaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbox_marcaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cbox_marcaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbox_marcaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cbox_marcaMouseReleased(evt);
            }
        });
        cbox_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_marcaActionPerformed(evt);
            }
        });
        cbox_marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbox_marcaKeyReleased(evt);
            }
        });

        btn_marca.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btn_marca.setText("OFF");
        btn_marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_marcaMousePressed(evt);
            }
        });
        btn_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_marcaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Marca");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btn_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(cbox_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(btn_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setBackground(new java.awt.Color(197, 196, 195));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cbox_grupo.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        cbox_grupo.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("Grupo");

        btn_grupo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btn_grupo.setText("OFF");
        btn_grupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_grupoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btn_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbox_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(btn_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ct_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ct_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        tbl_produtos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tbl_produtos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_produtos.setIntercellSpacing(new java.awt.Dimension(0, 4));
        tbl_produtos.setOpaque(false);
        tbl_produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_produtosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_produtos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 960, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1032, 545));
    }// </editor-fold>//GEN-END:initComponents

    
            public void preecherTabela(String SQL){ // METODO PARA PREENCHER TABELA NA INTERFACE
        ArrayList dados = new ArrayList();
        
        String [] Colunas  = new String []{"Cod. Barra","Produto","Marca","QTD","Pre. Compra","Pre. Venda"};
        conecBanc.conexaoBanco();
        conecPesq.conexaoBanco();
        conecBanc.executaSQL(SQL);
        
      try {
          conecBanc.rs.first();
          do {
             conecPesq.executaSQL("select * from marca where id_marca='"+conecBanc.rs.getInt("id_marca")+"'");
             conecPesq.rs.first();
             String nomeMarca= conecPesq.rs.getString("nome_marca");
              
              dados.add(new Object[]{conecBanc.rs.getString("codbarra"), conecBanc.rs.getString("nome_produto"),nomeMarca,conecBanc.rs.getInt("quantidade"),(numberFormat.format(conecBanc.rs.getFloat("preco_compra"))),(numberFormat.format(conecBanc.rs.getFloat("preco_venda")))});
              
          }while (conecBanc.rs.next());
          
      } catch (SQLException ex) {
//         JOptionPane.showMessageDialog(rootPane, "Erro ao Preencher o ArrayList! \n"+ ex);
      }
      
       ModeloTabela modelo = new ModeloTabela(dados,Colunas);
       
        tbl_produtos.setModel(modelo);
        DefaultTableCellRenderer headerRenderer2 = new DefaultTableCellRenderer(); 
        headerRenderer2.setOpaque(true); 
        headerRenderer2.setBackground(new Color(0,0,51));
        headerRenderer2.setFont(new java.awt.Font("Arial Black", Font.BOLD, 23));
        headerRenderer2.setForeground(new Color(255,255,255));
        for (int i = 0; i < tbl_produtos.getModel().getColumnCount(); 
         i++) { tbl_produtos.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer2); }

          tbl_produtos.setRowHeight(40); //  TAMANHO DA JANELA PRA CADA ITEM
        tbl_produtos.getColumnModel().getColumn(0).setPreferredWidth(120);
        tbl_produtos.getColumnModel().getColumn(0).setResizable(false);
        tbl_produtos.getColumnModel().getColumn(1).setPreferredWidth(400);
        tbl_produtos.getColumnModel().getColumn(1).setResizable(false);
        tbl_produtos.getColumnModel().getColumn(2).setPreferredWidth(160);
        tbl_produtos.getColumnModel().getColumn(2).setResizable(false); 
        tbl_produtos.getColumnModel().getColumn(3).setPreferredWidth(60);
        tbl_produtos.getColumnModel().getColumn(3).setResizable(false);
        tbl_produtos.getColumnModel().getColumn(4).setPreferredWidth(95);
        tbl_produtos.getColumnModel().getColumn(4).setResizable(false);
        tbl_produtos.getColumnModel().getColumn(5).setPreferredWidth(95);
        tbl_produtos.getColumnModel().getColumn(5).setResizable(false);
        tbl_produtos.getTableHeader().setReorderingAllowed(false);
//        tbl_produtos.setAutoResizeMode(tbl_produtos.AUTO_RESIZE_OFF);
        tbl_produtos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        conecBanc.desconectar();
        conecPesq.desconectar();
    }//  FINAL METODO PARA IMPRIMIR TABELA NA INTERFACE
            
    private void cbox_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_marcaActionPerformed

       
    }//GEN-LAST:event_cbox_marcaActionPerformed

    private void cbox_marcaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbox_marcaMousePressed

    }//GEN-LAST:event_cbox_marcaMousePressed

    private void cbox_marcaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbox_marcaMouseReleased

    }//GEN-LAST:event_cbox_marcaMouseReleased

    private void cbox_marcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbox_marcaMouseClicked

    }//GEN-LAST:event_cbox_marcaMouseClicked

    private void cbox_marcaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbox_marcaMouseEntered

    }//GEN-LAST:event_cbox_marcaMouseEntered

    private void cbox_marcaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbox_marcaMouseExited

    }//GEN-LAST:event_cbox_marcaMouseExited

    private void cbox_marcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbox_marcaKeyReleased

    }//GEN-LAST:event_cbox_marcaKeyReleased

    private void tbl_produtosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_produtosMouseClicked
        float desconto=0;
        String nome_produto =""+ tbl_produtos.getValueAt(tbl_produtos.getSelectedRow(), 1);
        conecBanc.conexaoBanco();
        conecBanc.executaSQL("select * from produto where nome_produto='" +nome_produto+"'");
        try {
            conecBanc.rs.first();
            ct_pesquisar.setText(conecBanc.rs.getString("nome_produto"));
//            ct_preco.setText((String.valueOf(numberFormat.format(conecBanc.rs.getFloat("preco_venda")))));

            float valorVenda= conecBanc.rs.getFloat("preco_venda");
            float div = (float) 4/100;

            desconto = valorVenda-(div * valorVenda);

//            ct_desconto.setText(String.valueOf(numberFormat.format(desconto)));
            conecBanc.desconectar();

        } catch (SQLException ex) {

        }
    }//GEN-LAST:event_tbl_produtosMouseClicked

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
if(click==1){
conecBanc.conexaoBanco();
 preecherTabela("select * from  produto inner join marca on marca.id_marca=produto.id_marca where nome_marca='"+cbox_marca.getSelectedItem()+"'");
conecBanc.desconectar();
}
    }//GEN-LAST:event_jPanel2MouseEntered

    private void btn_marcaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_marcaMousePressed
       if(btn_marca.getText().equals("OF")){
        btn_marca.setText("ON");
        cbox_marca.setEnabled(false);
        cbox_marca.setSelectedItem(null);
         opcPesquisa=0;
         click=0;
        }else{
          btn_marca.setText("OF");
          preencheComboMarca();
          cbox_marca.setEnabled(true);
          opcPesquisa =1;
          click=1;
        } 
    }//GEN-LAST:event_btn_marcaMousePressed

    private void btn_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_marcaActionPerformed

    private void btn_grupoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_grupoMousePressed
        if(btn_grupo.getText().equals("OF")){
        btn_grupo.setText("ON");
        cbox_grupo.setEnabled(false);
        cbox_grupo.setSelectedItem(null);
        opcPesquisa=0;
        }else{
          btn_grupo.setText("OF");
          preencheComboGrupo();
          cbox_grupo.setEnabled(true);
          opcPesquisa=2;
        }
    }//GEN-LAST:event_btn_grupoMousePressed

    private void ct_pesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ct_pesquisarKeyReleased

   preecherTabela("select * from produto where nome_produto like '%" + ct_pesquisar.getText() + "%' or codbarra like '%"+ct_pesquisar.getText()+"'");
        
    }//GEN-LAST:event_ct_pesquisarKeyReleased

    private void jPanel2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseMoved
if(click==1){
conecBanc.conexaoBanco();
 preecherTabela("select * from  produto inner join marca on marca.id_marca=produto.id_marca where nome_marca='"+cbox_marca.getSelectedItem()+"'");
conecBanc.desconectar();
}
    }//GEN-LAST:event_jPanel2MouseMoved

    public void achaMarca(String nomeMarca){
    conecBanc.conexaoBanco();
        try {
            conecBanc.executaSQL("select * from marca where nome_marca='"+nomeMarca+"'");
            conecBanc.rs.first();
            idMarcaPesq= conecBanc.rs.getInt("id_marca");
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null,"Erro ao procurar marca! \n Erro: "+ex);
        }
    conecBanc.desconectar();
   
}
    
           public void preencheComboMarca(){
        conecBanc.conexaoBanco();
        conecBanc.executaSQL("select * from marca order by nome_marca");
         try {
             conecBanc.rs.first();
             cbox_marca.removeAllItems();
             do{
                 cbox_marca.addItem(conecBanc.rs.getString("nome_marca"));
 
             } while(conecBanc.rs.next());
         } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane, "Erro a o Preencher Combobox Marca"+ ex);
         }
         conecBanc.desconectar();
    }       

             public void preencheComboGrupo(){
        conecBanc.conexaoBanco();
        conecBanc.executaSQL("select * from grupo_produto order by nome_grupo");
         try {
             conecBanc.rs.first();
             cbox_grupo.removeAllItems();
             do{
                 cbox_grupo.addItem(conecBanc.rs.getString("nome_grupo"));
 
             } while(conecBanc.rs.next());
         } catch (SQLException ex) {
             JOptionPane.showMessageDialog(rootPane, "Erro a o Preencher Combobox"+ ex);
         }
         conecBanc.desconectar();
    }     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_grupo;
    private javax.swing.JToggleButton btn_marca;
    private javax.swing.JComboBox<String> cbox_grupo;
    private javax.swing.JComboBox<String> cbox_marca;
    private javax.swing.JTextField ct_pesquisar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_produtos;
    // End of variables declaration//GEN-END:variables
}
